[package]
name = "renox-macros"
description = "Procedural macros for the Renox web framework: #[derive(Model)] and migrations!()."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "2", features = ["full"] }
