[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/arif-rachim/renox"
homepage = "https://github.com/arif-rachim/renox"
keywords = ["web", "framework", "htmx", "axum", "sqlite"]
categories = ["web-programming::http-server"]

[workspace.dependencies]
renox = { path = "crates/renox", version = "0.0.1" }
renox-core = { path = "crates/renox-core", version = "0.0.1" }
