//! `db:diff` writes migration files for what changed in the models.

use std::fs;
use std::path::Path;

use renox::db::{Migration, Model};
use renox::prelude::*;
use renox::testing::TestApp;

#[derive(Model, Debug, Clone, Default)]
#[model(table = "posts")]
struct PostV1 {
    id: i64,
    title: String,
}

#[derive(Model, Debug, Clone, Default)]
#[model(table = "posts")]
struct PostV2 {
    id: i64,
    title: String,
    body: Option<String>,
}

#[derive(Model, Debug, Clone, Default)]
#[model(table = "posts")]
struct PostRenamed {
    id: i64,
    name: Option<String>,
}

#[derive(Model, Debug, Clone, Default)]
#[model(table = "posts")]
struct PostOptional {
    id: i64,
    title: Option<String>,
}

#[derive(Model, Debug, Clone, Default)]
#[model(table = "posts")]
struct PostNoDefault {
    id: i64,
    title: String,
    views: i64,
}

#[derive(Model, Debug, Clone, Default)]
#[model(table = "posts")]
struct PostDropped {
    id: i64,
}

const WITH_INDEX: Migration = Migration::new("20300101000000_posts", "", Some("DROP TABLE posts;"))
    .sqlite(
        "CREATE TABLE posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL);
         CREATE INDEX posts_title_index ON posts (title);",
        None,
    )
    .postgres(
        "CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL);
         CREATE INDEX posts_title_index ON posts (title);",
        None,
    );

fn config(dir: &Path) -> Config {
    let mut config = Config::default();
    config.storage_path = dir.join("storage");
    config
}

fn leak(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}

/// The migrations in `dir`, as `migrations!()` would load them.
fn load(dir: &Path) -> Vec<Migration> {
    let mut stems: Vec<String> = fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter_map(|e| {
            let name = e.file_name().into_string().ok()?;
            name.strip_suffix(".up.sql")
                .filter(|s| !s.ends_with(".postgres"))
                .map(str::to_owned)
        })
        .collect();
    stems.sort();
    let read = |file: String| fs::read_to_string(dir.join(file)).ok().map(leak);
    stems
        .into_iter()
        .map(|stem| {
            let up = read(format!("{stem}.up.sql")).unwrap();
            let down = read(format!("{stem}.down.sql"));
            let mut m = Migration::new(leak(stem.clone()), up, down);
            if let Some(pg_up) = read(format!("{stem}.postgres.up.sql")) {
                m = m.postgres(pg_up, read(format!("{stem}.postgres.down.sql")));
            }
            m
        })
        .collect()
}

fn files(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(dir)
        .map(|rd| {
            rd.flatten()
                .filter_map(|e| e.file_name().into_string().ok())
                .collect()
        })
        .unwrap_or_default();
    names.sort();
    names
}

fn app<M: Model>(dir: &Path, migrations: &[Migration]) -> App {
    App::new()
        .config(config(dir))
        .migrations(migrations)
        .model::<M>()
}

async fn diff<M: Model>(
    dir: &Path,
    out: &Path,
    name: &str,
    extra: &[&str],
    answers: &[&str],
) -> renox::Result {
    let migrations = load(out);
    let mut args = vec![
        "db:diff".to_owned(),
        name.to_owned(),
        "--path".to_owned(),
        out.display().to_string(),
    ];
    args.extend(extra.iter().map(|a| (*a).to_owned()));
    renox::prompt::answering(
        answers.iter().map(|a| (*a).to_owned()).collect::<Vec<_>>(),
        app::<M>(dir, &migrations).run_args(args),
    )
    .await
}

async fn matches<M: Model>(dir: &Path, out: &Path) {
    let app = TestApp::new(
        App::new()
            .config(config(dir))
            .migrations(&load(out))
            .model::<M>(),
    )
    .await;
    app.assert_models_match_schema().await;
}

fn all_sql(out: &Path) -> String {
    files(out)
        .iter()
        .map(|f| fs::read_to_string(out.join(f)).unwrap())
        .collect::<Vec<_>>()
        .join("\n")
}

#[renox::test]
async fn a_model_without_a_table_gets_a_create_migration() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    diff::<PostV1>(dir.path(), &out, "create_posts", &[], &[])
        .await
        .unwrap();
    let names = files(&out);
    assert!(names.iter().any(|n| n.ends_with("_create_posts.up.sql")));
    assert!(names.iter().any(|n| n.ends_with("_create_posts.down.sql")));
    assert!(all_sql(&out).contains("CREATE TABLE"));
    matches::<PostV1>(dir.path(), &out).await;
}

#[renox::test]
async fn a_second_run_has_nothing_to_change() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    diff::<PostV1>(dir.path(), &out, "create_posts", &[], &[])
        .await
        .unwrap();
    let before = files(&out);
    diff::<PostV1>(dir.path(), &out, "again", &[], &[])
        .await
        .unwrap();
    assert_eq!(files(&out), before);
}

#[renox::test]
async fn a_new_field_adds_a_column() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    diff::<PostV1>(dir.path(), &out, "create_posts", &[], &[])
        .await
        .unwrap();
    diff::<PostV2>(dir.path(), &out, "add_body", &[], &[])
        .await
        .unwrap();
    assert!(all_sql(&out).contains("ADD COLUMN"));
    matches::<PostV2>(dir.path(), &out).await;
    let before = files(&out);
    diff::<PostV2>(dir.path(), &out, "again", &[], &[])
        .await
        .unwrap();
    assert_eq!(files(&out), before);
}

#[renox::test]
async fn an_accepted_rename_renames_the_column() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    diff::<PostOptional>(dir.path(), &out, "create_posts", &[], &[])
        .await
        .unwrap();
    diff::<PostRenamed>(dir.path(), &out, "rename_title", &[], &["yes"])
        .await
        .unwrap();
    assert!(all_sql(&out).contains("RENAME COLUMN"));
    matches::<PostRenamed>(dir.path(), &out).await;
}

#[renox::test]
async fn yes_refuses_to_drop() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    diff::<PostV1>(dir.path(), &out, "create_posts", &[], &[])
        .await
        .unwrap();
    let before = files(&out);
    let err = diff::<PostDropped>(dir.path(), &out, "drop_title", &["--yes"], &[])
        .await
        .unwrap_err();
    assert!(err.to_string().contains("posts.title"), "{err}");
    assert_eq!(files(&out), before);
}

#[renox::test]
async fn a_not_null_column_without_a_default_is_an_error() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    diff::<PostV1>(dir.path(), &out, "create_posts", &[], &[])
        .await
        .unwrap();
    let err = diff::<PostNoDefault>(dir.path(), &out, "add_views", &[], &[])
        .await
        .unwrap_err();
    assert!(err.to_string().contains("default"), "{err}");
}

#[renox::test]
async fn an_undeclared_index_is_kept_without_an_answer() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("migrations");
    fs::create_dir_all(&out).unwrap();
    let app = App::new()
        .config(config(dir.path()))
        .migrations(&[WITH_INDEX])
        .model::<PostV1>();
    renox::prompt::answering(
        [] as [&str; 0],
        app.run_args(["db:diff", "x", "--path", &out.display().to_string()]),
    )
    .await
    .unwrap();
    assert!(files(&out).is_empty());
}
