//! Negative flows in background work: queue, scheduler, events, mail,
//! notifications and webhooks. Started as the probes of the pre-1.0 review
//! (`docs/audit/2026-09-pre-1.0.md`, D*); every test asserts the robust
//! behaviour.

use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use renox::Kernel;
use renox::db::Dialect;
use renox::mail::Mail;
use renox::prelude::*;
use renox::testing::TestApp;
use serde::{Deserialize, Serialize};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};

use crate::data_resilience::config;

async fn log(state: &AppState, message: &str) -> Result {
    renox::db::sql("INSERT INTO log (message) VALUES (?)")
        .bind(message.to_owned())
        .execute(&state.db)
        .await?;
    Ok(())
}

async fn logged(db: &Db) -> Vec<String> {
    renox::db::sql("SELECT message FROM log ORDER BY id")
        .scalars(db)
        .await
        .unwrap()
}

async fn create_log(db: &Db) {
    renox::db::sql(match db.dialect() {
        Dialect::Sqlite => "CREATE TABLE log (id INTEGER PRIMARY KEY, message TEXT NOT NULL)",
        Dialect::Postgres => {
            "CREATE TABLE log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, message TEXT NOT NULL)"
        }
    })
    .execute(db)
    .await
    .unwrap();
}

#[derive(Serialize, Deserialize)]
struct Greet {
    name: String,
}
impl Job for Greet {
    const NAME: &'static str = "probe-greet";
    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, &format!("halo {}", self.name)).await
    }
}

#[derive(Serialize, Deserialize)]
struct Panicky;
impl Job for Panicky {
    const NAME: &'static str = "probe-panicky";
    const MAX_ATTEMPTS: u32 = 2;
    fn backoff(_: u32) -> Duration {
        Duration::ZERO
    }
    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, &format!("panicky attempt {}", ctx.attempt)).await?;
        panic!("the job panicked");
    }
}

/// Takes longer than it's allowed to be reserved (TIMEOUT > RESERVATION = 15 min).
#[derive(Serialize, Deserialize)]
struct LongJob;
impl Job for LongJob {
    const NAME: &'static str = "probe-long";
    const TIMEOUT: Duration = Duration::from_secs(30 * 60);
    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, &format!("long start (attempt {})", ctx.attempt)).await?;
        tokio::time::sleep(Duration::from_secs(2)).await;
        log(&ctx.state, "long end").await
    }
}

async fn kernel_cfg(config: Config) -> Kernel {
    let k = App::with_config(config)
        .job::<Greet>()
        .job::<Panicky>()
        .job::<LongJob>()
        .boot()
        .await
        .unwrap();
    k.migrate().await.unwrap();
    create_log(k.db()).await;
    k
}

async fn kernel() -> Kernel {
    kernel_cfg(config()).await
}

async fn wait_for(db: &Db, what: &str, secs: u64) -> bool {
    let until = Instant::now() + Duration::from_secs(secs);
    while Instant::now() < until {
        if logged(db).await.iter().any(|m| m.contains(what)) {
            return true;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    false
}

async fn scalar(db: &Db, sql: &str) -> i64 {
    renox::db::sql(sql).scalar(db).await.unwrap()
}

// ---------------------------------------------------------------- 4. queue

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn worker_survives_a_panicking_job() {
    let k = kernel().await;
    let (stop, stopped) = tokio::sync::watch::channel(false);
    let worker = tokio::spawn(k.worker(Vec::new()).run(1, stopped));
    k.state().dispatch(Panicky).await.unwrap();
    assert!(wait_for(k.db(), "panicky attempt 1", 5).await);
    tokio::time::sleep(Duration::from_millis(300)).await;
    k.state()
        .dispatch(Greet {
            name: "after".into(),
        })
        .await
        .unwrap();
    let ran = wait_for(k.db(), "halo after", 4).await;
    let jobs: Vec<String> = renox::db::sql(
        "SELECT job || ' attempts=' || attempts || ' reserved=' || COALESCE(CAST(reserved_at AS TEXT), 'null') FROM jobs",
    )
    .scalars(k.db())
    .await
    .unwrap();
    let failed = scalar(k.db(), "SELECT COUNT(*) FROM failed_jobs").await;
    eprintln!(
        "after a panicking job: next job ran = {ran}; jobs = {jobs:?}; failed_jobs = {failed}; log = {:?}",
        logged(k.db()).await
    );
    stop.send(true).unwrap();
    let joined = tokio::time::timeout(Duration::from_secs(3), worker).await;
    eprintln!("worker shutdown after panic: {joined:?}");
    assert!(
        ran,
        "the worker loop died with the panicking job; later jobs never run"
    );
}

#[renox::test]
async fn undeserializable_payload_fails_at_once() {
    let k = kernel().await;
    renox::db::sql(
        "INSERT INTO jobs (queue, job, payload, max_attempts, available_at, created_at) \
         VALUES ('default', 'probe-greet', '{\"nom\": 1}', 3, 0, 0)",
    )
    .execute(k.db())
    .await
    .unwrap();
    k.run_jobs().await.unwrap();
    let failed = scalar(k.db(), "SELECT COUNT(*) FROM failed_jobs").await;
    let waiting: Vec<i64> = renox::db::sql("SELECT available_at FROM jobs")
        .scalars(k.db())
        .await
        .unwrap();
    eprintln!("bad payload: failed_jobs={failed}, still queued (available_at) = {waiting:?}");
    assert_eq!(
        failed, 1,
        "a payload that can't be decoded never will: fail it without retries"
    );
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn job_longer_than_the_reservation_runs_once() {
    let k = kernel().await;
    let (stop, stopped) = tokio::sync::watch::channel(false);
    let worker = tokio::spawn(k.worker(Vec::new()).run(1, stopped));
    k.state().dispatch(LongJob).await.unwrap();
    assert!(wait_for(k.db(), "long start", 5).await);
    // Simulate 16 minutes passing while the (legal, TIMEOUT = 30 min) job runs.
    renox::db::sql("UPDATE jobs SET reserved_at = reserved_at - 960")
        .execute(k.db())
        .await
        .unwrap();
    let second = k.worker(Vec::new());
    let ran = tokio::spawn(async move { second.run_next().await });
    tokio::time::sleep(Duration::from_secs(3)).await;
    let _ = ran.await;
    stop.send(true).unwrap();
    let _ = worker.await;
    let starts = logged(k.db())
        .await
        .into_iter()
        .filter(|m| m.starts_with("long start"))
        .collect::<Vec<_>>();
    eprintln!("TIMEOUT > RESERVATION: starts = {starts:?}");
    assert_eq!(
        starts.len(),
        1,
        "a running job was picked up by a second worker"
    );
}

#[renox::test]
async fn crashed_final_attempt_is_not_run_again() {
    // The worker crashed (SIGKILL/OOM) during the last allowed attempt.
    let k = kernel().await;
    k.state()
        .dispatch(Greet {
            name: "crash".into(),
        })
        .await
        .unwrap();
    renox::db::sql("UPDATE jobs SET attempts = max_attempts, reserved_at = ?")
        .bind(renox::chrono::Utc::now().timestamp() - 3600)
        .execute(k.db())
        .await
        .unwrap();
    k.run_jobs().await.unwrap();
    let log = logged(k.db()).await;
    let failed = scalar(k.db(), "SELECT COUNT(*) FROM failed_jobs").await;
    eprintln!("reclaimed job at attempts=max: log={log:?} failed_jobs={failed}");
    assert!(
        log.is_empty(),
        "ran attempt max+1 (a poison job that kills workers runs forever)"
    );
}

#[renox::test]
async fn retry_and_flush_edges() {
    let k = kernel().await;
    let q = &k.state().queue;
    assert_eq!(q.retry(Some(987_654)).await.unwrap(), 0);
    assert_eq!(q.retry(None).await.unwrap(), 0);
    assert_eq!(q.flush_failed().await.unwrap(), 0);
}

async fn two_workers(k: &Kernel, jobs: usize) {
    for i in 0..jobs {
        k.state()
            .dispatch(Greet {
                name: format!("j{i}"),
            })
            .await
            .unwrap();
    }
    let (stop, stopped) = tokio::sync::watch::channel(false);
    let a = tokio::spawn(k.worker(Vec::new()).run(4, stopped.clone()));
    let b = tokio::spawn(k.worker(Vec::new()).run(4, stopped));
    let until = Instant::now() + Duration::from_secs(60);
    while Instant::now() < until && k.state().queue.pending().await.unwrap_or(1) > 0 {
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    stop.send(true).unwrap();
    let _ = (a.await, b.await);
    let log = logged(k.db()).await;
    let unique: std::collections::HashSet<_> = log.iter().collect();
    let failed = scalar(k.db(), "SELECT COUNT(*) FROM failed_jobs").await;
    eprintln!(
        "2 workers x 4 loops on {:?}: ran {} ({} unique) of {jobs}; pending {}; failed {failed}",
        k.db().dialect(),
        log.len(),
        unique.len(),
        k.state().queue.pending().await.unwrap()
    );
    assert_eq!((log.len(), unique.len(), failed), (jobs, jobs, 0));
}

#[renox::test(flavor = "multi_thread", worker_threads = 8)]
async fn two_workers_file_sqlite() {
    let dir = tempfile::tempdir().unwrap();
    let k = kernel_cfg({
        let mut c = config();
        c.database_url = format!("sqlite://{}/q.db", dir.path().display());
        c
    })
    .await;
    two_workers(&k, 300).await;
}

#[renox::test(flavor = "multi_thread", worker_threads = 8)]
async fn two_workers_default_db() {
    // In-memory SQLite, or a PostgreSQL schema with TEST_DATABASE_URL (SKIP LOCKED).
    let k = kernel().await;
    two_workers(&k, 300).await;
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn dispatch_in_a_rolled_back_transaction_is_dropped() {
    let dir = tempfile::tempdir().unwrap();
    let mut results = Vec::new();
    for (label, cfg) in [
        ("default", config()),
        ("file-sqlite", {
            let mut c = config();
            c.database_url = format!("sqlite://{}/t.db", dir.path().display());
            c
        }),
    ] {
        let k = kernel_cfg(cfg).await;
        let mut tx = k.db().begin().await.unwrap();
        renox::db::sql("INSERT INTO log (message) VALUES ('order row')")
            .execute(&mut tx)
            .await
            .unwrap();
        let started = Instant::now();
        let dispatched = tokio::time::timeout(
            Duration::from_secs(8),
            k.state().queue.dispatch_in(
                &mut tx,
                Greet {
                    name: "receipt".into(),
                },
            ),
        )
        .await;
        let took = started.elapsed();
        tx.rollback().await.unwrap();
        let queued = k.state().queue.pending().await.unwrap();
        eprintln!(
            "dispatch inside tx ({label}, {:?}): {} after {took:?}; after rollback jobs queued = {queued}",
            k.db().dialect(),
            match &dispatched {
                Err(_) => "HUNG".to_owned(),
                Ok(Ok(id)) => format!("ok id {id}"),
                Ok(Err(e)) => format!("error {e:?}"),
            }
        );
        results.push((label, matches!(dispatched, Ok(Ok(_))), queued));
    }
    for (label, ok, queued) in results {
        assert!(
            ok,
            "{label}: dispatch while a transaction is open failed/hung"
        );
        assert_eq!(
            queued, 0,
            "{label}: the job outlives the rolled-back transaction (no afterCommit)"
        );
    }
}

// ---------------------------------------------------------------- 5. scheduler

static SCHED_PANIC: AtomicUsize = AtomicUsize::new(0);
static SCHED_ERR: AtomicUsize = AtomicUsize::new(0);
static SCHED_SLOW: AtomicUsize = AtomicUsize::new(0);

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn scheduler_task_that_panics_keeps_running() {
    let dir = tempfile::tempdir().unwrap();
    let port = std::net::TcpListener::bind("127.0.0.1:0")
        .unwrap()
        .local_addr()
        .unwrap()
        .port();
    let cfg = {
        let mut c = config();
        c.database_url = format!("sqlite://{}/s.db", dir.path().display());
        c.port = port;
        c.scheduler = true;
        c.storage_path = dir.path().join("storage");
        c
    };
    let k = App::with_config(cfg.clone()).boot().await.unwrap();
    k.migrate().await.unwrap();
    k.db().close().await;
    let app = App::with_config(cfg).schedule(|s| {
        s.every(Duration::from_secs(1), "probe-panic", |_| async {
            SCHED_PANIC.fetch_add(1, Ordering::SeqCst);
            panic!("scheduled task panicked");
        });
        s.every(Duration::from_secs(1), "probe-err", |_| async {
            SCHED_ERR.fetch_add(1, Ordering::SeqCst);
            Err(Error::BadRequest("task failed".into()))
        });
        s.every(Duration::from_secs(1), "probe-slow", |_| async {
            SCHED_SLOW.fetch_add(1, Ordering::SeqCst);
            tokio::time::sleep(Duration::from_millis(2500)).await;
            Ok(())
        });
    });
    let server = tokio::spawn(app.serve());
    // Wait for enough runs (slow machines take longer), up to 30 s.
    let started = Instant::now();
    while started.elapsed() < Duration::from_secs(30)
        && (SCHED_PANIC.load(Ordering::SeqCst) < 4 || SCHED_ERR.load(Ordering::SeqCst) < 4)
    {
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
    let elapsed = started.elapsed().as_secs_f64();
    server.abort();
    let k = App::with_config({
        let mut c = config();
        c.database_url = format!("sqlite://{}/s.db", dir.path().display());
        c
    })
    .boot()
    .await
    .unwrap();
    let claims = scalar(
        k.db(),
        "SELECT COUNT(*) FROM cache WHERE key LIKE 'renox:schedule:%'",
    )
    .await;
    let (p, e, s) = (
        SCHED_PANIC.load(Ordering::SeqCst),
        SCHED_ERR.load(Ordering::SeqCst),
        SCHED_SLOW.load(Ordering::SeqCst),
    );
    eprintln!(
        "scheduler: panic-task runs={p}, err-task runs={e}, slow(2.5s)-task runs={s}, claim rows={claims}"
    );
    assert!(e >= 4, "an erroring task keeps its schedule");
    // A 2.5 s task started every second runs at most once per 2.5 s.
    assert!(
        (s as f64) <= elapsed / 2.5 + 1.0,
        "overlapping runs are skipped ({s} runs in {elapsed:.1}s)"
    );
    assert!(
        p >= 4,
        "a task that panicked once never runs again (its `running` flag stays set)"
    );
}

// ---------------------------------------------------------------- 6. events

#[derive(Clone)]
struct Boom;
impl Event for Boom {}

#[renox::test]
async fn listener_panic_does_not_skip_other_listeners() {
    let k = App::with_config(config())
        .listen(|_: Boom, _| async move {
            if true {
                panic!("listener panicked");
            }
            Ok(())
        })
        .listen(|_: Boom, state| async move { log(&state, "second listener").await })
        .boot()
        .await
        .unwrap();
    k.migrate().await.unwrap();
    create_log(k.db()).await;
    let st = k.state().clone();
    let r = tokio::spawn(async move { st.emit(Boom).await }).await;
    let log = logged(k.db()).await;
    eprintln!(
        "emit with a panicking listener: {}; later listeners ran: {log:?}",
        match &r {
            Ok(Ok(())) => "ok".to_owned(),
            Ok(Err(e)) => format!("error {e:?}"),
            Err(e) => format!("PANIC {e}"),
        }
    );
    assert!(
        matches!(r, Ok(Err(_))),
        "emit should turn a listener panic into an error"
    );
    assert_eq!(log, ["second listener"]);
}

// ---------------------------------------------------------------- 7. mail

#[derive(Default)]
struct Smtp {
    commands: Vec<String>,
    data: Vec<String>,
}

/// A minimal SMTP server that records what it's sent.
async fn fake_smtp() -> (u16, Arc<Mutex<Smtp>>) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let seen = Arc::new(Mutex::new(Smtp::default()));
    let record = seen.clone();
    tokio::spawn(async move {
        while let Ok((stream, _)) = listener.accept().await {
            let record = record.clone();
            tokio::spawn(async move {
                let (read, mut write) = stream.into_split();
                let mut lines = BufReader::new(read).lines();
                write.write_all(b"220 fake ESMTP\r\n").await.ok();
                let mut in_data = false;
                let mut data = String::new();
                while let Ok(Some(line)) = lines.next_line().await {
                    if in_data {
                        if line == "." {
                            in_data = false;
                            record.lock().unwrap().data.push(std::mem::take(&mut data));
                            write.write_all(b"250 queued\r\n").await.ok();
                        } else {
                            data.push_str(&line);
                            data.push('\n');
                        }
                        continue;
                    }
                    record.lock().unwrap().commands.push(line.clone());
                    let upper = line.to_ascii_uppercase();
                    let reply: &[u8] = if upper.starts_with("EHLO") || upper.starts_with("HELO") {
                        b"250 fake\r\n"
                    } else if upper.starts_with("DATA") {
                        in_data = true;
                        b"354 go ahead\r\n"
                    } else if upper.starts_with("QUIT") {
                        write.write_all(b"221 bye\r\n").await.ok();
                        break;
                    } else {
                        b"250 ok\r\n"
                    };
                    write.write_all(reply).await.ok();
                }
            });
        }
    });
    (port, seen)
}

fn smtp_config(port: u16) -> Config {
    let mut c = config();
    c.mail.mailer = "smtp".into();
    c.mail.host = "127.0.0.1".into();
    c.mail.port = Some(port);
    c.mail.encryption = "none".into();
    c.mail.from_address = "app@example.com".into();
    c
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn mail_subject_header_injection() {
    let (port, seen) = fake_smtp().await;
    let k = kernel_cfg(smtp_config(port)).await;
    k.mailer()
        .send(Mail::new(
            "to@example.com",
            "Hello\r\nBcc: victim@evil.example\r\nX-Injected: yes",
            "body",
        ))
        .await
        .unwrap();
    let seen = seen.lock().unwrap();
    let data = seen.data.join("\n---\n");
    eprintln!("SMTP commands: {:?}", seen.commands);
    eprintln!(
        "message headers:\n{}",
        data.split("\n\n").next().unwrap_or("")
    );
    assert!(!seen.commands.iter().any(|c| c.contains("victim")));
    assert!(
        !data
            .lines()
            .any(|l| l.to_ascii_lowercase().starts_with("bcc:") || l.starts_with("X-Injected"))
    );
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn mail_bad_addresses_and_unreachable_smtp() {
    let (port, _) = fake_smtp().await;
    let k = kernel_cfg(smtp_config(port)).await;
    for to in [
        "not-an-email",
        "a@example.com\r\nBcc: x@evil.example",
        "a@example.com, b@example.com",
        "",
    ] {
        let r = k.mailer().send(Mail::new(to, "s", "t")).await;
        eprintln!(
            "send to {to:?}: {:?}",
            r.as_ref().map_err(|e| format!("{e:?}"))
        );
        assert!(r.is_err(), "{to:?} accepted");
    }

    // Closed port.
    let closed = {
        let l = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        l.local_addr().unwrap().port()
    };
    let k = kernel_cfg(smtp_config(closed)).await;
    let started = Instant::now();
    let direct = k.mailer().send(Mail::new("to@example.com", "s", "t")).await;
    eprintln!(
        "direct send to a closed SMTP port: {:?} after {:?}",
        direct.as_ref().map_err(|e| format!("{e:?}")),
        started.elapsed()
    );
    assert!(direct.is_err());

    k.state()
        .queue_mail(Mail::new("to@example.com", "queued", "t"))
        .await
        .unwrap();
    for _ in 0..5 {
        k.run_jobs().await.unwrap();
        renox::db::sql("UPDATE jobs SET available_at = 0")
            .execute(k.db())
            .await
            .unwrap();
    }
    let failed = k.state().queue.failed().await.unwrap();
    eprintln!(
        "queued mail to closed port after 5 attempts: failed_jobs = {:?}",
        failed
            .iter()
            .map(|f| f.error.lines().next().unwrap_or("").to_owned())
            .collect::<Vec<_>>()
    );
    assert_eq!(failed.len(), 1);

    // An invalid address through the queue is retried 5 times for nothing.
    let (port, _) = fake_smtp().await;
    let k = kernel_cfg(smtp_config(port)).await;
    k.state()
        .queue_mail(Mail::new("not-an-email", "queued", "t"))
        .await
        .unwrap();
    k.run_jobs().await.unwrap();
    let failed_now = k.state().queue.failed().await.unwrap().len();
    eprintln!(
        "queued mail to an invalid address: failed at once = {}",
        failed_now == 1
    );
    assert_eq!(
        failed_now, 1,
        "a permanent error (bad address) is retried with backoff"
    );
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn mail_to_a_silent_smtp_server_times_out() {
    // Accepts TCP but never speaks: how long does send() take?
    let l = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = l.local_addr().unwrap().port();
    tokio::spawn(async move {
        let mut keep = Vec::new();
        while let Ok((s, _)) = l.accept().await {
            keep.push(s);
        }
    });
    let k = kernel_cfg(smtp_config(port)).await;
    let started = Instant::now();
    // MAIL_TIMEOUT defaults to 10 s.
    let r = tokio::time::timeout(
        Duration::from_secs(15),
        k.mailer().send(Mail::new("to@example.com", "s", "t")),
    )
    .await;
    eprintln!(
        "send to a silent SMTP server: {} after {:?}",
        match &r {
            Err(_) => "still waiting (>8s)".to_owned(),
            Ok(r) => format!("{:?}", r.as_ref().map_err(|e| format!("{e:?}"))),
        },
        started.elapsed()
    );
    assert!(
        r.is_ok(),
        "no short SMTP timeout: a request sending mail directly hangs"
    );
}

#[renox::test]
async fn mail_view_templates() {
    let views = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(views.path().join("mail")).unwrap();
    std::fs::write(
        views.path().join("mail/only_html.html"),
        "<p>Hi {{ name }}</p>",
    )
    .unwrap();
    let app = TestApp::with_config(App::new(), |c| c.views_path = views.path().to_path_buf()).await;
    let mail = app
        .state()
        .mail_view(
            "a@example.com",
            "s",
            "mail/only_html",
            context! { name => "Budi" },
        )
        .unwrap();
    assert_eq!(
        mail.text, "Hi Budi",
        "missing .txt falls back to text from the HTML"
    );
    assert!(
        app.state()
            .mail_view("a@example.com", "s", "mail/nope", context! {})
            .is_err()
    );
}

// ---------------------------------------------------------------- notifications

struct Shipped;
impl renox::auth::Notification for Shipped {
    fn kind(&self) -> &'static str {
        "shipped"
    }
    fn channels(&self) -> Vec<renox::auth::Channel> {
        vec![renox::auth::Channel::Mail, renox::auth::Channel::Database]
    }
    fn to_mail(&self, to: &renox::auth::Recipient, _: &AppState) -> Result<Mail> {
        Ok(Mail::new(
            to.email().unwrap_or_default(),
            "Shipped",
            "on its way",
        ))
    }
    fn to_database(&self, _: &renox::auth::Recipient) -> renox::serde_json::Value {
        json!({"order": 1})
    }
}

#[renox::test]
async fn notification_failing_halfway_sends_no_mail() {
    let app = TestApp::new(App::new().module(Auth::new())).await;
    let user = User::register(app.db(), "Budi", "budi@example.com", "password123")
        .await
        .unwrap();
    renox::db::sql("DROP TABLE notifications")
        .execute(app.db())
        .await
        .unwrap();
    let r = app.state().notify(&user, &Shipped).await;
    let mails = app.sent_mail().len();
    eprintln!(
        "notify with a broken database channel: {:?}; mails sent = {mails}",
        r.as_ref().map_err(|e| e.status())
    );
    // Retrying the failed notify re-sends the mail.
    let _ = app.state().notify(&user, &Shipped).await;
    eprintln!("after a retry: mails sent = {}", app.sent_mail().len());
    assert!(r.is_err());
    assert_eq!(
        app.sent_mail().len(),
        0,
        "mail went out although the notification failed"
    );
}

// ---------------------------------------------------------------- 10. webhooks

static HANDLED: AtomicUsize = AtomicUsize::new(0);
static PANIC_NEXT: AtomicBool = AtomicBool::new(false);
static LAST_PAYLOAD: Mutex<Vec<u8>> = Mutex::new(Vec::new());

/// Unsigned provider whose event id is in a header (like X-GitHub-Delivery).
struct Hook;
impl Webhook for Hook {
    const PROVIDER: &'static str = "probe-hook";
    fn verify(request: &WebhookRequest, _: &AppState) -> Result {
        renox::webhook::ensure(request.header("x-token") == Some("t"))
    }
    fn event_id(request: &WebhookRequest) -> Result<String> {
        Ok(request.header("x-event-id").unwrap_or_default().to_owned())
    }
    async fn handle(call: WebhookCall, _: JobContext) -> Result {
        HANDLED.fetch_add(1, Ordering::SeqCst);
        *LAST_PAYLOAD.lock().unwrap() = call.payload.clone();
        if PANIC_NEXT.swap(false, Ordering::SeqCst) {
            panic!("webhook handler panicked");
        }
        Ok(())
    }
}

struct Hooks;
impl Module for Hooks {
    fn name(&self) -> &'static str {
        "hooks"
    }
    fn routes(&self) -> Routes {
        Routes::new().webhook::<Hook>("/wh")
    }
    fn register(&self, app: &mut Registry) {
        app.webhook::<Hook>();
    }
}

async fn hook_app() -> TestApp {
    TestApp::new(App::new().module(Hooks)).await
}

async fn deliver(
    app: &TestApp,
    id: &str,
    body: impl Into<Vec<u8>>,
) -> renox::testing::TestResponse {
    app.request()
        .without_csrf()
        .header("x-token", "t")
        .header("x-event-id", id)
        .post_body("/wh", "application/octet-stream", body)
        .await
}

/// One test so the statics aren't shared between parallel tests.
#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn webhook_edge_cases() {
    let app = Arc::new(hook_app().await);

    // Huge body.
    let r = deliver(&app, "big", vec![b'x'; 11 * 1024 * 1024]).await;
    eprintln!("11 MB webhook body -> {}", r.status);
    assert_eq!(r.status, StatusCode::PAYLOAD_TOO_LARGE);

    // Invalid UTF-8 body: stored exactly?
    let raw = b"{\"amount\":\"\xff\xfe\"}".to_vec();
    deliver(&app, "utf8", raw.clone()).await.assert_ok();
    app.run_jobs().await;
    let stored = LAST_PAYLOAD.lock().unwrap().clone();
    eprintln!(
        "invalid UTF-8 body: stored bytes equal = {}; stored = {:?}",
        stored == raw,
        String::from_utf8_lossy(&stored)
    );
    let utf8_exact = stored == raw;

    // A NUL byte in the body.
    let r = deliver(&app, "nul", b"{\"a\":\"\x00\"}".to_vec()).await;
    eprintln!("body with a raw NUL byte -> {}", r.status);
    let nul_ok = r.status == StatusCode::OK;

    // Replay after processed.
    app.run_jobs().await;
    let before = HANDLED.load(Ordering::SeqCst);
    deliver(&app, "once", "{}").await.assert_ok();
    app.run_jobs().await;
    let replay = deliver(&app, "once", "{}").await;
    app.run_jobs().await;
    assert_eq!(replay.text(), "already received");
    assert_eq!(
        HANDLED.load(Ordering::SeqCst),
        before + 1,
        "replay not processed again"
    );

    // webhook:retry on a processed call.
    let id: i64 = renox::db::sql("SELECT id FROM webhook_calls WHERE event_id = 'once'")
        .scalar(app.db())
        .await
        .unwrap();
    let retried = renox::webhook::retry(app.state(), id).await.unwrap();
    app.run_jobs().await;
    eprintln!(
        "webhook:retry on a processed call: accepted={retried}; handled again = {}",
        HANDLED.load(Ordering::SeqCst) == before + 2
    );

    // Very long event id.
    let long = "e".repeat(10_000);
    let r = deliver(&app, &long, "{}").await;
    eprintln!("10 000-char event id -> {}", r.status);
    let long_ok = r.status == StatusCode::OK;

    // Concurrent identical deliveries.
    let mut tasks = Vec::new();
    for _ in 0..20 {
        let app = app.clone();
        tasks.push(tokio::spawn(async move {
            deliver(&app, "same", "{}").await.status
        }));
    }
    let mut statuses = Vec::new();
    for t in tasks {
        statuses.push(t.await.unwrap().as_u16());
    }
    let rows: i64 = renox::db::sql("SELECT COUNT(*) FROM webhook_calls WHERE event_id = 'same'")
        .scalar(app.db())
        .await
        .unwrap();
    eprintln!("20 concurrent identical deliveries: statuses {statuses:?}; rows {rows}");
    assert_eq!(rows, 1);
    assert!(statuses.iter().all(|s| *s == 200));

    // Handler panic.
    app.run_jobs().await;
    PANIC_NEXT.store(true, Ordering::SeqCst);
    deliver(&app, "panics", "{}").await.assert_ok();
    let k = app.clone();
    let joined = tokio::spawn(async move { k.kernel().run_jobs().await }).await;
    let status: String =
        renox::db::sql("SELECT status FROM webhook_calls WHERE event_id = 'panics'")
            .scalar(app.db())
            .await
            .unwrap();
    let job: Option<String> = renox::db::sql(
        "SELECT 'attempts=' || attempts || ' reserved=' || COALESCE(CAST(reserved_at AS TEXT),'null') FROM jobs",
    )
    .scalar_optional(app.db())
    .await
    .unwrap();
    eprintln!(
        "webhook handler panic: run_jobs {}; call status = {status}; job = {job:?}",
        if joined.is_err() {
            "PANICKED"
        } else {
            "returned"
        }
    );

    assert!(
        utf8_exact,
        "invalid UTF-8 is replaced (U+FFFD): the handler can't re-verify or decode the original bytes"
    );
    assert!(nul_ok, "a NUL byte in the body is refused by the database");
    assert!(long_ok, "a long event id is refused by the database");
    assert_eq!(
        status, "failed",
        "a panicking handler leaves the call `received` forever"
    );
}

#[renox::test]
async fn webhook_long_random_event_id() {
    let app = hook_app().await;
    // 10 000 non-repeating characters (a long provider id; doesn't compress).
    let mut x: u64 = 0x9E37_79B9_7F4A_7C15;
    let id: String = (0..10_000)
        .map(|_| {
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            char::from(b'a' + (x % 26) as u8)
        })
        .collect();
    let r = deliver(&app, &id, "{}").await;
    eprintln!(
        "10 000-char random event id on {:?} -> {} {}",
        app.db().dialect(),
        r.status,
        r.text()
    );
    assert_eq!(r.status, StatusCode::OK);
}
