//! M26c: the app binary's own commands through `App::run_args` (what
//! `my-app migrate:status` runs), `DbError`'s questions, `db::Json` and
//! `renox::Path`'s rejections.

use renox::db::{Json, Migration};
use renox::prelude::*;
use renox::testing::TestApp;

const SCHEMA: Migration = Migration::new(
    "20300101000000_notes",
    "",
    Some("DROP TABLE notes; DROP TABLE tags;"),
)
.sqlite(
    "CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL UNIQUE,
                 meta TEXT NOT NULL DEFAULT '{}');
             CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT,
                 note_id INTEGER NOT NULL REFERENCES notes (id));",
    None,
)
.postgres(
    "CREATE TABLE notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 title TEXT NOT NULL UNIQUE, meta JSONB NOT NULL DEFAULT '{}');
             CREATE TABLE tags (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 note_id BIGINT NOT NULL REFERENCES notes (id));",
    None,
);

#[derive(serde::Serialize, serde::Deserialize, Default, Debug, Clone, PartialEq)]
struct Meta {
    pinned: bool,
    tags: Vec<String>,
}

#[derive(Model, serde::Serialize, Default, Debug, Clone, PartialEq)]
#[model(table = "notes")]
struct Note {
    id: i64,
    title: String,
    meta: Json<Meta>,
}

struct Notes;

impl Module for Notes {
    fn name(&self) -> &'static str {
        "notes"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get("/notes/{id}", |Path(id): Path<i64>| async move {
                format!("note {id}")
            })
            .name("notes.show")
            // A handler asking for a parameter its route doesn't have: an
            // app mistake, a 500, not a visitor's 404.
            .get(
                "/broken",
                |Path(id): Path<i64>| async move { format!("{id}") },
            )
    }

    fn register(&self, app: &mut Registry) {
        app.schedule()
            .daily_at("03:00", "tidy-notes", |_| async { Ok(()) });
    }
}

/// A file database and storage directory, so commands see each other's work.
fn config(dir: &std::path::Path) -> Config {
    let mut config = Config::default();
    config.database_url = format!("sqlite://{}", dir.join("app.db").display());
    config.storage_path = dir.join("storage");
    config
}

fn app(dir: &std::path::Path) -> App {
    App::with_config(config(dir))
        .migrations(&[SCHEMA])
        .module(Notes)
}

#[renox::test]
async fn the_binarys_commands_run_through_run_args() {
    if std::env::var("TEST_DATABASE_URL").is_ok() {
        return; // file databases only; the commands are the same on PostgreSQL
    }
    let dir = tempfile::tempdir().unwrap();
    let run = |args: &'static [&'static str]| app(dir.path()).run_args(args.iter().copied());
    run(&["help"]).await.unwrap();
    run(&["migrate"]).await.unwrap();
    run(&["migrate:status"]).await.unwrap();
    run(&["route:list"]).await.unwrap();
    run(&["schedule:list"]).await.unwrap();
    run(&["schedule:run", "tidy-notes"]).await.unwrap();
    assert!(
        run(&["schedule:run", "nope"]).await.is_err(),
        "unknown task"
    );
    run(&["queue:failed"]).await.unwrap();
    run(&["queue:flush"]).await.unwrap();
    run(&["queue:prune-failed"]).await.unwrap();
    run(&["queue:prune-batches"]).await.unwrap();
    run(&["webhook:failed"]).await.unwrap();
    run(&["cache:prune"]).await.unwrap();
    run(&["session:prune"]).await.unwrap();
    assert!(run(&["queue:retry"]).await.is_err(), "needs an id or `all`");

    // Maintenance mode is a file in storage/framework.
    run(&["down"]).await.unwrap();
    assert!(dir.path().join("storage/framework/down").exists());
    run(&["up"]).await.unwrap();
    assert!(!dir.path().join("storage/framework/down").exists());

    // Seeded and rolled back.
    run(&["migrate:rollback"]).await.unwrap();
    run(&["migrate:fresh"]).await.unwrap();
    let kernel = app(dir.path()).boot().await.unwrap();
    let tables: i64 = renox::db::sql(
        "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = 'notes'",
    )
    .scalar(kernel.db())
    .await
    .unwrap();
    assert_eq!(tables, 1, "fresh ran every migration again");

    assert!(run(&["no-such-command"]).await.is_err());
}

#[renox::test]
async fn database_errors_say_what_went_wrong() {
    let app = TestApp::new(App::new().migrations(&[SCHEMA])).await;
    let db = app.db();
    Note::create(
        db,
        Note {
            title: "Coffee".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();

    let duplicate = renox::db::sql("INSERT INTO notes (title) VALUES ('Coffee')")
        .execute(db)
        .await
        .unwrap_err();
    assert!(duplicate.is_unique_violation());
    assert!(!duplicate.is_foreign_key_violation() && !duplicate.is_row_not_found());
    assert!(!duplicate.is_retryable() && !duplicate.is_timeout());
    assert!(format!("{duplicate}").contains("UNIQUE") || format!("{duplicate}").contains("unique"));
    assert!(std::error::Error::source(&duplicate).is_some());
    assert!(matches!(
        duplicate.sqlx(),
        renox::db::sqlx::Error::Database(_)
    ));

    let orphan = renox::db::sql("INSERT INTO tags (note_id) VALUES (999)")
        .execute(db)
        .await
        .unwrap_err();
    assert!(orphan.is_foreign_key_violation(), "{orphan:?}");

    let missing = renox::db::sql("SELECT title FROM notes WHERE id = 999")
        .fetch_one(db)
        .await
        .unwrap_err();
    assert!(missing.is_row_not_found());
    // As an app error, a duplicate is a 409; a row missing from raw SQL is a
    // 500 (`find_or_404` and `first_or_404` are the ones that answer 404).
    assert_eq!(
        Error::from(missing).status(),
        StatusCode::INTERNAL_SERVER_ERROR
    );
    assert_eq!(Error::from(duplicate).status(), StatusCode::CONFLICT);
}

#[renox::test]
async fn json_columns_round_trip() {
    let app = TestApp::new(App::new().migrations(&[SCHEMA])).await;
    let db = app.db();
    let mut note = Note::create(
        db,
        Note {
            title: "Tea".into(),
            meta: Json(Meta {
                pinned: true,
                tags: vec!["daily".into()],
            }),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    let found = Note::find_or_404(db, note.id).await.unwrap();
    assert_eq!(found, note);
    assert!(found.meta.pinned); // `Deref` to the value

    // `DerefMut`, and `From`.
    note.meta.tags.push("green".into());
    note.save(db).await.unwrap();
    assert_eq!(
        Note::find_or_404(db, note.id).await.unwrap().meta.tags,
        ["daily", "green"]
    );
    let from: Json<Meta> = Meta::default().into();
    assert!(!from.pinned);

    // A value that isn't the struct's shape is an error, not a panic.
    renox::db::sql("UPDATE notes SET meta = '{\"pinned\": \"yes\"}'")
        .execute(db)
        .await
        .unwrap();
    assert!(Note::find(db, note.id).await.is_err());
}

#[renox::test]
async fn paths_that_dont_parse_are_404s_and_missing_parameters_500s() {
    let app = TestApp::new(App::new().module(Notes)).await;
    app.get("/notes/7").await.assert_ok().assert_see("note 7");
    app.get("/notes/seven").await.assert_not_found();
    app.get("/broken").await.assert_status(500);
}
