//! M26c: the app binary's own commands through `App::run_args` (what
//! `my-app migrate:status` runs), `DbError`'s questions, `db::Json` and
//! `renox::Path`'s rejections.

use renox::db::{Json, Migration};
use renox::prelude::*;
use renox::testing::TestApp;

const SCHEMA: Migration = Migration::new(
    "20300101000000_notes",
    "",
    Some("DROP TABLE tags; DROP TABLE notes;"),
)
.sqlite(
    "CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL UNIQUE,
                 meta TEXT NOT NULL DEFAULT '{}');
             CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT,
                 note_id INTEGER NOT NULL REFERENCES notes (id));",
    None,
)
.postgres(
    "CREATE TABLE notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 title TEXT NOT NULL UNIQUE, meta JSONB NOT NULL DEFAULT '{}');
             CREATE TABLE tags (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 note_id BIGINT NOT NULL REFERENCES notes (id));",
    None,
);

#[derive(serde::Serialize, serde::Deserialize, Default, Debug, Clone, PartialEq)]
struct Meta {
    pinned: bool,
    tags: Vec<String>,
}

#[derive(Model, serde::Serialize, Default, Debug, Clone, PartialEq)]
#[model(table = "notes")]
struct Note {
    id: i64,
    title: String,
    meta: Json<Meta>,
}

struct Notes;

impl Module for Notes {
    fn name(&self) -> &'static str {
        "notes"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get("/notes/{id}", |Path(id): Path<i64>| async move {
                format!("note {id}")
            })
            .name("notes.show")
            // A handler asking for a parameter its route doesn't have: an
            // app mistake, a 500, not a visitor's 404.
            .get(
                "/broken",
                |Path(id): Path<i64>| async move { format!("{id}") },
            )
    }

    fn register(&self, app: &mut Registry) {
        app.schedule()
            .daily_at("03:00", "tidy-notes", |_| async { Ok(()) });
    }
}

/// A database every boot of the test shares, so commands see each other's
/// work: a file on SQLite; on PostgreSQL (with `TEST_DATABASE_URL`) a
/// schema of the test's own, named in the URL, so the test swap that gives
/// each boot a fresh schema doesn't apply. And a storage directory.
fn config(dir: &std::path::Path) -> Config {
    let mut config = Config::default();
    config.database_url = shared_database(dir);
    config.storage_path = dir.join("storage");
    config
}

fn shared_database(dir: &std::path::Path) -> String {
    let file = format!("sqlite://{}", dir.join("app.db").display());
    let Some(url) = std::env::var("TEST_DATABASE_URL")
        .ok()
        .filter(|url| url.starts_with("postgres"))
    else {
        return file;
    };
    // The schema is named after the temporary directory, so each test has
    // its own; it's made by the first command (see `make_schema`).
    let schema = format!(
        "renox_cmd_{}",
        dir.file_name()
            .unwrap()
            .to_string_lossy()
            .to_ascii_lowercase()
            .replace(|c: char| !c.is_ascii_alphanumeric(), "_")
    );
    let glue = if url.contains('?') { '&' } else { '?' };
    format!("{url}{glue}options=-c%20search_path%3D{schema}")
}

/// Creates the PostgreSQL schema `shared_database` names (nothing on SQLite).
async fn make_schema(dir: &std::path::Path) {
    on_schema(dir, "CREATE SCHEMA IF NOT EXISTS").await;
}

/// Drops it again at the end of the test.
async fn drop_schema(dir: &std::path::Path) {
    on_schema(dir, "DROP SCHEMA IF EXISTS").await;
}

async fn on_schema(dir: &std::path::Path, statement: &str) {
    let url = shared_database(dir);
    let Some((base, schema)) = url.split_once("options=-c%20search_path%3D") else {
        return;
    };
    let mut config = Config::default();
    config.database_url = base.trim_end_matches(['?', '&']).to_owned();
    let kernel = App::with_config(config).boot().await.unwrap();
    let cascade = if statement.starts_with("DROP") {
        " CASCADE"
    } else {
        ""
    };
    renox::db::sql(format!("{statement} {schema}{cascade}"))
        .execute(kernel.db())
        .await
        .unwrap();
    kernel.db().close().await;
}

async fn table_count(kernel: &renox::Kernel, table: &str) -> i64 {
    let sql = match kernel.db().dialect() {
        renox::db::Dialect::Postgres => {
            "SELECT COUNT(*) FROM pg_tables WHERE schemaname = current_schema() AND tablename = ?"
        }
        _ => "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = ?",
    };
    renox::db::sql(sql)
        .bind(table)
        .scalar(kernel.db())
        .await
        .unwrap()
}

fn app(dir: &std::path::Path) -> App {
    App::with_config(config(dir))
        .migrations(&[SCHEMA])
        .module(Notes)
}

#[renox::test]
async fn the_binarys_commands_run_through_run_args() {
    let dir = tempfile::tempdir().unwrap();
    make_schema(dir.path()).await;
    let run = |args: &'static [&'static str]| app(dir.path()).run_args(args.iter().copied());
    run(&["help"]).await.unwrap();
    run(&["migrate"]).await.unwrap();
    run(&["migrate:status"]).await.unwrap();
    run(&["route:list"]).await.unwrap();
    run(&["schedule:list"]).await.unwrap();
    run(&["schedule:run", "tidy-notes"]).await.unwrap();
    assert!(
        run(&["schedule:run", "nope"]).await.is_err(),
        "unknown task"
    );
    run(&["queue:failed"]).await.unwrap();
    run(&["queue:flush"]).await.unwrap();
    run(&["queue:prune-failed"]).await.unwrap();
    run(&["queue:prune-batches"]).await.unwrap();
    run(&["webhook:failed"]).await.unwrap();
    run(&["cache:prune"]).await.unwrap();
    run(&["session:prune"]).await.unwrap();
    assert!(run(&["queue:retry"]).await.is_err(), "needs an id or `all`");

    // Maintenance mode is a file in storage/framework.
    run(&["down"]).await.unwrap();
    assert!(dir.path().join("storage/framework/down").exists());
    run(&["up"]).await.unwrap();
    assert!(!dir.path().join("storage/framework/down").exists());

    // Seeded and rolled back.
    run(&["migrate:rollback"]).await.unwrap();
    run(&["migrate:fresh"]).await.unwrap();
    let kernel = app(dir.path()).boot().await.unwrap();
    assert_eq!(
        table_count(&kernel, "notes").await,
        1,
        "fresh ran every migration again"
    );

    assert!(run(&["no-such-command"]).await.is_err());
    drop_schema(dir.path()).await;
}

#[renox::test]
async fn database_errors_say_what_went_wrong() {
    let app = TestApp::new(App::new().migrations(&[SCHEMA])).await;
    let db = app.db();
    Note::create(
        db,
        Note {
            title: "Coffee".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();

    let duplicate = renox::db::sql("INSERT INTO notes (title) VALUES ('Coffee')")
        .execute(db)
        .await
        .unwrap_err();
    assert!(duplicate.is_unique_violation());
    assert!(!duplicate.is_foreign_key_violation() && !duplicate.is_row_not_found());
    assert!(!duplicate.is_retryable() && !duplicate.is_timeout());
    assert!(format!("{duplicate}").contains("UNIQUE") || format!("{duplicate}").contains("unique"));
    assert!(std::error::Error::source(&duplicate).is_some());
    assert!(matches!(
        duplicate.sqlx(),
        renox::db::sqlx::Error::Database(_)
    ));

    let orphan = renox::db::sql("INSERT INTO tags (note_id) VALUES (999)")
        .execute(db)
        .await
        .unwrap_err();
    assert!(orphan.is_foreign_key_violation(), "{orphan:?}");

    let missing = renox::db::sql("SELECT title FROM notes WHERE id = 999")
        .fetch_one(db)
        .await
        .unwrap_err();
    assert!(missing.is_row_not_found());
    // As an app error, a duplicate is a 409; a row missing from raw SQL is a
    // 500 (`find_or_404` and `first_or_404` are the ones that answer 404).
    assert_eq!(
        Error::from(missing).status(),
        StatusCode::INTERNAL_SERVER_ERROR
    );
    assert_eq!(Error::from(duplicate).status(), StatusCode::CONFLICT);
}

#[renox::test]
async fn json_columns_round_trip() {
    let app = TestApp::new(App::new().migrations(&[SCHEMA])).await;
    let db = app.db();
    let mut note = Note::create(
        db,
        Note {
            title: "Tea".into(),
            meta: Json(Meta {
                pinned: true,
                tags: vec!["daily".into()],
            }),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    let found = Note::find_or_404(db, note.id).await.unwrap();
    assert_eq!(found, note);
    assert!(found.meta.pinned); // `Deref` to the value

    // `DerefMut`, and `From`.
    note.meta.tags.push("green".into());
    note.save(db).await.unwrap();
    assert_eq!(
        Note::find_or_404(db, note.id).await.unwrap().meta.tags,
        ["daily", "green"]
    );
    let from: Json<Meta> = Meta::default().into();
    assert!(!from.pinned);

    // A value that isn't the struct's shape is an error, not a panic.
    renox::db::sql("UPDATE notes SET meta = '{\"pinned\": \"yes\"}'")
        .execute(db)
        .await
        .unwrap();
    assert!(Note::find(db, note.id).await.is_err());
}

#[renox::test]
async fn paths_that_dont_parse_are_404s_and_missing_parameters_500s() {
    let app = TestApp::new(App::new().module(Notes)).await;
    app.get("/notes/7").await.assert_ok().assert_see("note 7");
    app.get("/notes/seven").await.assert_not_found();
    app.get("/broken").await.assert_status(500);
}

// ---------- #249: the commands and branches the test above doesn't run ----------

/// Fails every time, once: fills `failed_jobs` for the queue commands.
#[derive(serde::Serialize, serde::Deserialize)]
struct Broken;

impl Job for Broken {
    const NAME: &'static str = "broken";
    const MAX_ATTEMPTS: u32 = 1;
    async fn handle(self, _ctx: JobContext) -> Result {
        Err(Error::BadRequest("always fails".into()))
    }
}

static ECHOED: std::sync::Mutex<Vec<String>> = std::sync::Mutex::new(Vec::new());

fn full_app(dir: &std::path::Path) -> App {
    let mut config = config(dir);
    config.views_path = dir.join("views");
    config.public_path = dir.join("public");
    App::with_config(config)
        .migrations(&[SCHEMA])
        .module(Notes)
        .job::<Broken>()
        .seeder(|state| async move {
            renox::db::sql("INSERT INTO notes (title) VALUES ('seeded')")
                .execute(&state.db)
                .await?;
            Ok(())
        })
        .command(
            "notes:echo",
            "Echoes its words",
            |args, _state| async move {
                ECHOED
                    .lock()
                    .unwrap()
                    .extend(args.positional().iter().map(|w| (*w).to_owned()));
                Ok(())
            },
        )
}

async fn notes(dir: &std::path::Path) -> i64 {
    let kernel = full_app(dir).boot().await.unwrap();
    renox::db::sql("SELECT COUNT(*) FROM notes")
        .scalar(kernel.db())
        .await
        .unwrap()
}

async fn failed_jobs(dir: &std::path::Path) -> i64 {
    let kernel = full_app(dir).boot().await.unwrap();
    renox::db::sql("SELECT COUNT(*) FROM failed_jobs")
        .scalar(kernel.db())
        .await
        .unwrap()
}

#[renox::test]
async fn the_rest_of_the_binarys_commands() {
    let dir = tempfile::tempdir().unwrap();
    make_schema(dir.path()).await;
    let run = |args: &'static [&'static str]| full_app(dir.path()).run_args(args.iter().copied());
    run(&["help"]).await.unwrap();
    run(&["migrate"]).await.unwrap();
    run(&["migrate"]).await.unwrap(); // nothing to do

    // Seeding, alone and after a fresh start.
    run(&["db:seed"]).await.unwrap();
    assert_eq!(notes(dir.path()).await, 1);
    run(&["migrate:fresh", "--seed"]).await.unwrap();
    assert_eq!(notes(dir.path()).await, 1);

    // Rolling back by steps, and a step that isn't a number.
    assert!(run(&["migrate:rollback", "--step", "x"]).await.is_err());
    run(&["migrate:rollback", "--step", "2"]).await.unwrap();
    run(&["migrate:status"]).await.unwrap(); // pending ones listed
    run(&["migrate"]).await.unwrap();

    // The queue: a job that fails, worked once on the named queues.
    full_app(dir.path())
        .boot()
        .await
        .unwrap()
        .state()
        .dispatch(Broken)
        .await
        .unwrap();
    run(&["queue:work", "--once", "--queue", "default,mail"])
        .await
        .unwrap();
    assert_eq!(failed_jobs(dir.path()).await, 1);
    run(&["queue:failed"]).await.unwrap(); // with a row to print
    assert!(run(&["queue:retry", "abc"]).await.is_err());
    run(&["queue:retry", "all"]).await.unwrap();
    assert_eq!(failed_jobs(dir.path()).await, 0);
    run(&["queue:work", "--once"]).await.unwrap();
    let id = {
        let kernel = full_app(dir.path()).boot().await.unwrap();
        renox::db::sql("SELECT id FROM failed_jobs")
            .scalar::<i64>(kernel.db())
            .await
            .unwrap()
    };
    full_app(dir.path())
        .run_args(["queue:retry".to_owned(), id.to_string()])
        .await
        .unwrap();
    run(&["queue:work", "--once"]).await.unwrap();
    assert!(run(&["queue:forget"]).await.is_err(), "needs an id");
    assert!(
        run(&["queue:forget", "987654"]).await.is_err(),
        "no such job"
    );
    let id = {
        let kernel = full_app(dir.path()).boot().await.unwrap();
        renox::db::sql("SELECT id FROM failed_jobs")
            .scalar::<i64>(kernel.db())
            .await
            .unwrap()
    };
    full_app(dir.path())
        .run_args(["queue:forget".to_owned(), id.to_string()])
        .await
        .unwrap();
    assert_eq!(failed_jobs(dir.path()).await, 0);

    // Webhook calls that failed, listed and retried.
    {
        let kernel = full_app(dir.path()).boot().await.unwrap();
        renox::db::sql(
            "INSERT INTO webhook_calls (provider, event_id, payload, status, error, received_at) \
             VALUES ('pay', 'evt_1', ?, 'failed', 'the shop is closed', ?)",
        )
        .bind(b"{}".to_vec())
        .bind(renox::db::now().timestamp())
        .execute(kernel.db())
        .await
        .unwrap();
    }
    run(&["webhook:failed"]).await.unwrap();
    assert!(run(&["webhook:retry"]).await.is_err(), "needs an id");
    assert!(run(&["webhook:retry", "abc"]).await.is_err());
    assert!(
        run(&["webhook:retry", "987654"]).await.is_err(),
        "no such call"
    );
    run(&["webhook:retry", "1"]).await.unwrap();

    // The UI kit copied into the app, once; again only with --force.
    run(&["ui:publish"]).await.unwrap();
    assert!(dir.path().join("views/components/ui.html").exists());
    assert!(dir.path().join("public/css/renox-ui.css").exists());
    assert!(
        run(&["ui:publish"]).await.is_err(),
        "exists without --force"
    );
    run(&["ui:publish", "--force"]).await.unwrap();

    // Maintenance with a bypass secret and a retry time; up when not down.
    run(&["down", "--secret", "let-me-in", "--retry", "60"])
        .await
        .unwrap();
    let down = std::fs::read_to_string(dir.path().join("storage/framework/down")).unwrap();
    assert!(down.contains("let-me-in") && down.contains("60"), "{down}");
    run(&["up"]).await.unwrap();
    run(&["up"]).await.unwrap(); // was not down

    // The scheduler's usage error, and an app command with its words.
    assert!(run(&["schedule:run"]).await.is_err());
    run(&["notes:echo", "one", "two"]).await.unwrap();
    assert_eq!(*ECHOED.lock().unwrap(), ["one", "two"]);
    drop_schema(dir.path()).await;
}

#[renox::test]
async fn schedule_list_and_route_list_with_little_to_show() {
    let dir = tempfile::tempdir().unwrap();
    let mut config = Config::default();
    config.database_url = format!("sqlite://{}", dir.path().join("app.db").display());
    // No scheduled tasks; a route on its own domain shows the DOMAIN column.
    let app = || App::with_config(config.clone()).module(Hosted);
    app().run_args(["schedule:list"]).await.unwrap();
    app().run_args(["route:list"]).await.unwrap();
}

struct Hosted;

impl Module for Hosted {
    fn name(&self) -> &'static str {
        "hosted"
    }

    fn routes(&self) -> Routes {
        Routes::new().domain(
            "{team}.example.com",
            Routes::new().get("/", || async { "team" }),
        )
    }
}

// ---------- #249: what App::boot refuses, and what it wires up ----------

struct Fallback(&'static str);

impl Module for Fallback {
    fn name(&self) -> &'static str {
        self.0
    }

    fn routes(&self) -> Routes {
        Routes::new().fallback(|| async { "not here" })
    }
}

struct DomainFallback(&'static str);

impl Module for DomainFallback {
    fn name(&self) -> &'static str {
        self.0
    }

    fn routes(&self) -> Routes {
        Routes::new().domain(
            "admin.example.com",
            Routes::new()
                .get(&format!("/{}", self.0), || async { "admin" })
                .fallback(|| async { "admin 404" }),
        )
    }
}

struct Nested;

impl Module for Nested {
    fn name(&self) -> &'static str {
        "nested"
    }

    fn routes(&self) -> Routes {
        Routes::new().domain(
            "{team}.example.com",
            Routes::new().domain(
                "deeper.example.com",
                Routes::new().get("/", || async { "x" }),
            ),
        )
    }
}

/// Two modules whose routes axum can't merge (one path, a wildcard each).
struct Wild(&'static str);

impl Module for Wild {
    fn name(&self) -> &'static str {
        self.0
    }

    fn routes(&self) -> Routes {
        Routes::from(renox::axum::Router::new().route(
            "/files/{*rest}",
            renox::axum::routing::get(|| async { "files" }),
        ))
    }
}

async fn boot_error(app: App) -> String {
    match app.boot().await {
        Ok(_) => panic!("booted"),
        Err(err) => format!("{err:?}"),
    }
}

#[renox::test]
async fn boot_refuses_routes_that_cant_be_put_together() {
    let err = boot_error(App::new().module(Fallback("one")).module(Fallback("two"))).await;
    assert!(
        err.contains("two modules set a fallback route (`two` is the second)"),
        "{err}"
    );
    let err = boot_error(
        App::new()
            .module(DomainFallback("a"))
            .module(DomainFallback("b")),
    )
    .await;
    assert!(
        err.contains("two fallbacks for the domain `admin.example.com` (module `b`)"),
        "{err}"
    );
    let err = boot_error(App::new().module(Nested)).await;
    assert!(
        err.contains("inside another domain (module `nested`)"),
        "{err}"
    );
    let err = boot_error(App::new().module(Wild("left")).module(Wild("right"))).await;
    assert!(
        err.contains("the routes of the `right` module clash"),
        "{err}"
    );
    let err = boot_error(
        App::new()
            .mailer("news", |_| Ok(renox::mail::MailConfig::default()))
            .mailer("news", |_| Ok(renox::mail::MailConfig::default())),
    )
    .await;
    assert!(
        err.contains("two mailers are named `news` (App::mailer)"),
        "{err}"
    );
}

/// `App::layer` wraps the routes of each domain too.
#[renox::test]
async fn app_layers_wrap_domain_routes() {
    use renox::axum::http::{HeaderName, HeaderValue};
    let app = TestApp::new(App::new().module(DomainFallback("a")).layer(
        renox::axum::middleware::map_response(|mut res: Response| async move {
            res.headers_mut().insert(
                HeaderName::from_static("x-layer"),
                HeaderValue::from_static("on"),
            );
            res
        }),
    ))
    .await;
    app.request()
        .header("host", "admin.example.com")
        .get("/a")
        .await
        .assert_see("admin")
        .assert_header("x-layer", "on");
    app.request()
        .header("host", "admin.example.com")
        .get("/missing")
        .await
        .assert_see("admin 404");
}

#[renox::test]
async fn view_check_passes_clean_views_and_fails_broken_ones() {
    let dir = tempfile::tempdir().unwrap();
    let views = dir.path().join("views");
    std::fs::create_dir_all(&views).unwrap();
    std::fs::write(views.join("ok.html"), "<p>{{ 1 + 1 }}</p>").unwrap();
    let make = || {
        let mut config = config(dir.path());
        config.views_path = views.clone();
        App::with_config(config)
    };
    make().run_args(["view:check"]).await.unwrap();

    std::fs::write(views.join("broken.html"), "{% if %}").unwrap();
    assert!(make().run_args(["view:check"]).await.is_err());

    // An app command of the same name runs in place of the built-in one.
    make()
        .command("view:check", "Mine", |_args, _state| async move { Ok(()) })
        .run_args(["view:check"])
        .await
        .unwrap();
}

#[renox::test]
async fn view_data_writes_the_editor_file_with_the_apps_components() {
    let dir = tempfile::tempdir().unwrap();
    let components = dir.path().join("views/components");
    std::fs::create_dir_all(&components).unwrap();
    std::fs::write(
        components.join("price_tag.html"),
        "<rx-props amount currency=\"USD\" />\n<b>{{ amount }}</b>",
    )
    .unwrap();
    std::fs::write(
        components.join("macros.html"),
        "{% macro x() %}{% endmacro %}",
    )
    .unwrap();
    let mut config = config(dir.path());
    config.views_path = dir.path().join("views");
    let out = dir.path().join(".vscode/renox-components.json");
    App::with_config(config)
        .run_args(["view:data", "--out", out.to_str().unwrap()])
        .await
        .unwrap();
    let data: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
    let tags = data["tags"].as_array().unwrap();
    let tag = tags.iter().find(|t| t["name"] == "app-price-tag").unwrap();
    let attrs: Vec<&str> = tag["attributes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| a["name"].as_str().unwrap())
        .collect();
    assert_eq!(attrs, ["amount", "currency"]);
    assert!(tags.iter().any(|t| t["name"] == "rx-table"));
    assert!(!tags.iter().any(|t| t["name"] == "app-macros"));
}
