//! Dashboards: `renox::chart` (`Period`, `Trend`, `Series`), the `chart(…)`
//! template function and the kit's `stat`, `stats`, `dashboard`, `widget`
//! and `period_filter`.

use renox::chart::{Period, Series, Trend};
use renox::chrono::Duration;
use renox::db::{DateTime, Migration, Scripts};
use renox::prelude::*;
use renox::testing::TestApp;
use renox::timezone::Zone;

const SCHEMA: Migration = Migration {
    name: "20300101000000_dash_sales",
    up: "",
    down: Some("DROP TABLE dash_sales;"),
    sqlite: Some(Scripts {
        up: "CREATE TABLE dash_sales (id INTEGER PRIMARY KEY AUTOINCREMENT, status TEXT NOT NULL,
                 total INTEGER NOT NULL, created_at TEXT)",
        down: None,
    }),
    postgres: Some(Scripts {
        up: "CREATE TABLE dash_sales (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 status TEXT NOT NULL, total BIGINT NOT NULL, created_at TIMESTAMPTZ)",
        down: None,
    }),
};

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "dash_sales")]
struct Sale {
    id: i64,
    status: String,
    total: i64,
    created_at: Option<DateTime>,
}

async fn sale(app: &TestApp, status: &str, total: i64, at: DateTime) {
    Sale::create(
        app.db(),
        Sale {
            status: status.into(),
            total,
            created_at: Some(at),
            ..Default::default()
        },
    )
    .await
    .unwrap();
}

struct Pages;

impl Module for Pages {
    fn name(&self) -> &'static str {
        "dash-pages"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get(
                "/trend",
                |State(state): State<AppState>, period: Period| async move {
                    let paid = || Sale::where_eq("status", "paid");
                    let count = Trend::of(paid(), "created_at")
                        .over(period)
                        .count(&state)
                        .await?;
                    let sum = Trend::of(paid(), "created_at")
                        .over(period)
                        .sum(&state, "total")
                        .await?;
                    let before = Trend::of(paid(), "created_at")
                        .over(period.previous())
                        .sum(&state, "total")
                        .await?;
                    let average = Trend::of(paid(), "created_at")
                        .over(period)
                        .average(&state, "total")
                        .await?;
                    Ok::<_, Error>(renox::axum::Json(renox::serde_json::json!({
                        "period": period,
                        "count": count,
                        "sum": sum,
                        "total": sum.total(),
                        "change": sum.change_from(&before),
                        "average": average,
                    })))
                },
            )
            .get("/bad-column", |State(state): State<AppState>| async move {
                Trend::of(Sale::query(), "nope")
                    .count(&state)
                    .await
                    .map(|_| "ok")
            })
            .get("/page", |period: Period| async move {
                let sales = Series::new(
                    vec![
                        "2026-10-01".into(),
                        "2026-10-02".into(),
                        "2026-10-03".into(),
                    ],
                    vec![12_500.0, 30_000.0, 18_000.0],
                )
                .named("Sales");
                view("page.html", context! { period, sales })
            })
            .get("/bad-kind", || async { view("bad.html", context! {}) })
    }
}

const PAGE: &str = r##"{% from "renox/ui.html" import stats, stat, dashboard, widget, period_filter %}
<div id="filter">{{ period_filter(period) }}</div>
{% call stats(3) %}
{{ stat("Revenue", 75000 | money, delta=12.5, trend=sales.values, url="/orders") }}
{{ stat("Refunds", 3, delta=-20, good="down") }}
{{ stat("Visitors", "1,204", delta=0) }}
{{ stat("Plain", "9", hint="Since Monday") }}
{% endcall %}
{% call dashboard(2) %}
{% call widget("Sales", description="Paid orders", span=2) %}<div id="line">{{ chart("line", sales, format="money") }}</div>{% endcall %}
{{ widget("Live", url="/live", poll=30, id="live") }}
{% call widget("Mixed", url="/mixed", poll=15, id="mixed") %}first{% endcall %}
{% endcall %}
<div id="area">{{ chart("area", [1, 2, 3], title="Signups", table=false) }}</div>
<div id="bars">{{ chart("bar", labels=["A", "B"], series=[{"name": "Coffee", "values": [1, 2]}, {"name": "Tea", "values": [3, -1]}], stacked=true) }}</div>
<div id="grouped">{{ chart("bar", labels=["A", "B"], series=[{"name": "Coffee", "values": [1, 2]}, {"name": "Tea", "values": [3, none]}], height=160) }}</div>
<div id="pie">{{ chart("doughnut", labels=["a", "b", "c", "d", "e", "f", "g"], values=[10, 20, 30, 10, 10, 10, 10], title="Mix") }}</div>
<div id="month">{{ chart("bar", labels=["2026-08", "2026-09"], values=[1, 2], x_format="%m/%Y") }}</div>"##;

async fn app(timezone: &str, locale: &str) -> (TestApp, tempfile::TempDir) {
    let views = tempfile::tempdir().unwrap();
    std::fs::write(views.path().join("page.html"), PAGE).unwrap();
    std::fs::write(
        views.path().join("bad.html"),
        r#"{{ chart("radar", [1]) }}"#,
    )
    .unwrap();
    let (path, timezone, locale) = (
        views.path().to_path_buf(),
        timezone.to_owned(),
        locale.to_owned(),
    );
    let app = TestApp::with_config(App::new().migrations(&[SCHEMA]).module(Pages), move |c| {
        c.views_path = path;
        c.timezone = timezone;
        c.locale = locale;
        c.lang_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/lang");
    })
    .await;
    (app, views)
}

#[renox::test]
async fn trends_count_and_add_up_per_day_and_month() {
    let (app, _views) = app("UTC", "en").await;
    let now = renox::db::now();
    sale(&app, "paid", 100, now).await;
    sale(&app, "paid", 50, now).await;
    sale(&app, "paid", 30, now - Duration::days(2)).await;
    sale(&app, "paid", 999, now - Duration::days(40)).await;
    sale(&app, "refunded", 7, now).await;

    let week = app.get("/trend?period=7d").await;
    week.assert_ok().assert_json_path("period", "7d");
    let json: renox::serde_json::Value = week.json();
    let counts: Vec<f64> = renox::serde_json::from_value(json["count"]["values"].clone()).unwrap();
    assert_eq!(counts.len(), 7);
    assert_eq!(
        (counts[6], counts[4], counts.iter().sum::<f64>()),
        (2.0, 1.0, 3.0)
    );
    assert_eq!(
        json["count"]["labels"][6],
        now.format("%Y-%m-%d").to_string()
    );
    assert_eq!(json["total"], 180.0);
    assert_eq!(
        json["change"],
        renox::serde_json::Value::Null,
        "nothing the week before"
    );
    assert_eq!(json["average"]["values"][6], 75.0);

    // 30 days back: 40 days ago is in the period before.
    let month = app
        .get("/trend?period=30d")
        .await
        .json::<renox::serde_json::Value>();
    assert_eq!(month["total"], 180.0);
    let change = month["change"].as_f64().unwrap();
    assert!(
        (change - (180.0 - 999.0) / 999.0 * 100.0).abs() < 1e-9,
        "{change}"
    );

    // Per month over a year; an unknown period is 30 days.
    let year = app
        .get("/trend?period=12m")
        .await
        .json::<renox::serde_json::Value>();
    assert_eq!(year["sum"]["labels"].as_array().unwrap().len(), 12);
    assert_eq!(year["sum"]["labels"][11], now.format("%Y-%m").to_string());
    assert_eq!(year["total"], 1179.0);
    app.get("/trend?period=fortnight")
        .await
        .assert_json_path("period", "30d");

    // Only the model's columns.
    app.get("/bad-column").await.assert_status(500);
}

#[renox::test]
async fn days_are_cut_in_app_timezone() {
    let (app, _views) = app("+07:00", "en").await;
    let zone: Zone = "+07:00".parse().unwrap();
    let (today, _) = Period::days(1).range(zone);
    // Just after local midnight counts today; just before, yesterday.
    sale(&app, "paid", 10, today + Duration::minutes(30)).await;
    sale(&app, "paid", 20, today - Duration::minutes(30)).await;
    let json = app
        .get("/trend?period=7d")
        .await
        .json::<renox::serde_json::Value>();
    assert_eq!(json["sum"]["values"][6], 10.0);
    assert_eq!(json["sum"]["values"][5], 20.0);
}

#[renox::test]
async fn charts_stats_and_widgets_render() {
    let (app, _views) = app("UTC", "en").await;
    let page = app.get("/page?q=coffee&page=3&period=7d").await;
    let html = page.assert_ok().text();
    let has = |needle: &str| assert!(html.contains(needle), "missing {needle}\n{html}");

    // The period filter keeps the query (but the page) and marks the current one.
    has(r#"href="?q=coffee&amp;period=7d" aria-current="page">7 days</a>"#);
    has(r#"href="?q=coffee&amp;period=30d">30 days</a>"#);

    // Figures.
    has(r#"<div class="rx-stats rx-cols-3">"#);
    has(r#"<a class="rx-stat rx-stat--link" href="/orders">"#);
    has(r#"<p class="rx-stat__value">Rp 75,000</p>"#);
    has(r#"rx-stat__delta--good"#);
    has(
        r#"<span class="rx-stat__change">+12.5%</span> <span class="rx-stat__vs">vs previous period</span>"#,
    );
    has(r#"rx-stat__delta--good"><svg"#);
    has(r#"<span class="rx-stat__change">-20.0%</span>"#);
    has("rx-stat__delta--flat");
    has(r#"<p class="rx-stat__vs">Since Monday</p>"#);
    has(r#"<span class="rx-stat__trend"><svg class="rx-spark""#);

    // Widgets: in a grid, lazy and polled, or polled after their first content.
    has(r#"<div class="rx-dashboard rx-cols-2">"#);
    has(r#"<section class="rx-widget rx-span-2" aria-labelledby="#);
    has(r#"<p class="rx-widget__description">Paid orders</p>"#);
    has(r#"id="live" hx-get="/live" hx-trigger="load, every 30s" hx-swap="innerHTML""#);
    has(r#"id="mixed" hx-get="/mixed" hx-trigger="every 15s""#);
    has(">first</div>");

    // A line chart: SVG, axis ticks, labels, an end dot, the table view.
    let line = &html[html.find(r#"<div id="line">"#).unwrap()..];
    let line = &line[..line.find("</figure>").unwrap()];
    assert!(
        line.contains(r#"<figure class="rx-chart rx-chart--line" data-rx-chart=""#),
        "{line}"
    );
    assert!(
        line.contains(r#"<path class="rx-chart__line rx-series-1" d="M0.0,"#),
        "{line}"
    );
    assert!(
        line.contains(">30K</span>") && line.contains(">0</span>"),
        "{line}"
    );
    assert!(
        line.contains(">Oct 1</span>") && line.contains(">Oct 3</span>"),
        "{line}"
    );
    assert!(
        line.contains(r#"class="rx-chart__dot rx-series-1" style="left: 100%"#),
        "{line}"
    );
    assert!(
        line.contains("<td class=\"rx-num\">Rp 30,000</td>"),
        "{line}"
    );
    assert!(
        line.contains("&quot;values&quot;:[&quot;Rp 12,500&quot;"),
        "{line}"
    );
    assert!(
        !line.contains("rx-chart__legend"),
        "one series has no legend: {line}"
    );

    // An area without a table; stacked and grouped bars with legends.
    let area =
        &html[html.find(r#"<div id="area">"#).unwrap()..html.find(r#"<div id="bars">"#).unwrap()];
    assert!(
        area.contains("rx-chart__area rx-series-1") && !area.contains("rx-chart__table"),
        "{area}"
    );
    assert!(area.contains(r#"<figcaption class="rx-visually-hidden">Signups</figcaption>"#));
    let bars = &html
        [html.find(r#"<div id="bars">"#).unwrap()..html.find(r#"<div id="grouped">"#).unwrap()];
    assert!(bars.contains(r#"<span class="rx-chart__key rx-chart__key--box rx-series-2" aria-hidden="true"></span>Tea"#), "{bars}");
    assert_eq!(
        bars.matches(r#"<div class="rx-chart__column">"#).count(),
        2,
        "{bars}"
    );
    assert!(
        bars.contains("rx-chart__bar rx-series-2 rx-chart__bar--neg rx-chart__bar--end"),
        "{bars}"
    );
    let grouped =
        &html[html.find(r#"<div id="grouped">"#).unwrap()..html.find(r#"<div id="pie">"#).unwrap()];
    assert_eq!(
        grouped.matches(r#"<div class="rx-chart__column">"#).count(),
        4,
        "{grouped}"
    );
    assert!(
        grouped.contains("--rx-chart-h: 160px") && grouped.contains("<td class=\"rx-num\">—</td>"),
        "{grouped}"
    );

    // A doughnut: six slices at most, the rest is "Other".
    let pie =
        &html[html.find(r#"<div id="pie">"#).unwrap()..html.find(r#"<div id="month">"#).unwrap()];
    assert_eq!(
        pie.matches(r#"<path class="rx-chart__slice"#).count(),
        6,
        "{pie}"
    );
    assert!(pie.contains(r#"<span class="rx-chart__name">Other</span><span class="rx-chart__value">20 <span class="rx-chart__share">20.0%</span>"#), "{pie}");
    let month = &html[html.find(r#"<div id="month">"#).unwrap()..];
    assert!(month.contains(">08/2026</span>"), "{month}");

    app.get("/bad-kind").await.assert_status(500);
}

#[renox::test]
async fn dashboards_speak_the_apps_language() {
    // Texts from the app's `tests/lang/es.json`, numbers in Spanish style.
    let (app, _views) = app("UTC", "es").await;
    let html = app.get("/page").await.text();
    for needle in [
        ">7 días</a>",
        r#"aria-current="page">30 días</a>"#,
        "frente al periodo anterior",
        "Rp 75.000",
        ">30K</span>",
        ">Oct 1</span>",
        "Ver los datos",
        "Otros",
    ] {
        assert!(html.contains(needle), "missing {needle}");
    }
}
