//! Negative flows in the data layer: queries, integrity, transactions,
//! migrations, cache, storage and boot. Started as the probes of the pre-1.0
//! review (`docs/audit/2026-09-pre-1.0.md`, D*); every test asserts the
//! robust behaviour.

use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::{Duration, Instant};

use axum::body::Bytes;
use renox::Kernel;
use renox::db::{Dialect, Migration};
use renox::prelude::*;
use renox::testing::TestApp;

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "products", soft_deletes)]
struct Product {
    id: i64,
    name: String,
    price: i64,
    category: Option<String>,
    created_at: Option<DateTime>,
    updated_at: Option<DateTime>,
    deleted_at: Option<DateTime>,
}

#[derive(Model, serde::Serialize, Default, Debug)]
#[model(table = "notes")]
struct Note {
    id: i64,
    product_id: Option<i64>,
    body: String,
}

fn p(name: &str) -> Product {
    Product {
        name: name.into(),
        price: 1000,
        ..Default::default()
    }
}

pub(crate) fn config() -> Config {
    {
        let mut c = Config::default();
        c.env = Environment::Testing;
        c.key = Some(renox::generate_key());
        c
    }
}

async fn kernel_cfg(config: Config, extra: &[Migration]) -> Kernel {
    let k = App::with_config(config)
        .migrations(renox::migrations!("tests/migrations"))
        .migrations(extra)
        .boot()
        .await
        .unwrap();
    k.migrate().await.unwrap();
    k
}

async fn kernel() -> Kernel {
    kernel_cfg(config(), &[]).await
}

fn pk(d: Dialect) -> &'static str {
    match d {
        Dialect::Sqlite => "INTEGER PRIMARY KEY AUTOINCREMENT",
        Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    }
}

// ---------------------------------------------------------------- 1. SQL injection

#[renox::test]
async fn injection_through_query_names_is_refused() {
    let k = kernel().await;
    let db = k.db();
    Product::create(db, p("a")).await.unwrap();
    let evil = "name\" = 'x' OR 1=1 --";
    assert!(Product::query().where_eq(evil, "x").get(db).await.is_err());
    assert!(
        Product::query()
            .where_op("price", "= 1 OR 1=1 --", 0)
            .get(db)
            .await
            .is_err()
    );
    assert!(
        Product::query()
            .order_by("price; DROP TABLE products")
            .get(db)
            .await
            .is_err()
    );
    assert!(Product::query().where_in(evil, [1]).get(db).await.is_err());
    assert!(Product::query().where_null(evil).count(db).await.is_err());
    assert!(Product::query().where_eq(evil, 1).delete(db).await.is_err());
    assert_eq!(Product::query().count(db).await.unwrap(), 1);
}

#[renox::test]
async fn injection_through_validation_table_and_column_is_inert() {
    let k = kernel().await;
    let db = k.db();
    Product::create(db, p("a")).await.unwrap();
    for (table, column) in [
        ("products\"; DROP TABLE products; --", "name"),
        ("products", "name\" = name OR 1=1; DROP TABLE products; --"),
    ] {
        let mut v = Validator::new();
        v.field("x", &"a".to_owned()).unique(table, column);
        // An error (unknown table/column), never an executed payload.
        let r = v.finish(db).await;
        eprintln!(
            "unique({table:?}, {column:?}) -> {:?}",
            r.as_ref()
                .map(|e| e.iter().count())
                .map_err(|e| format!("{e:?}"))
        );
        assert!(r.is_err());
    }
    assert_eq!(Product::query().count(db).await.unwrap(), 1);
}

#[renox::test]
async fn exists_rule_with_text_input_against_integer_column() {
    // A <select name="product_id"> arrives as a String: `exists("products","id")`
    // must be a validation error ("does not exist"), not a 500.
    let k = kernel().await;
    let db = k.db();
    Product::create(db, p("a")).await.unwrap();
    let mut v = Validator::new();
    v.field("product_id", &"abc".to_owned())
        .exists("products", "id");
    let result = v.finish(db).await;
    assert!(
        matches!(&result, Ok(errors) if errors.has("product_id")),
        "expected a validation error, got {:?}",
        result.map(|e| e.iter().count())
    );
}

#[renox::test]
async fn assert_database_has_quotes_table_names() {
    let app =
        Arc::new(TestApp::new(App::new().migrations(renox::migrations!("tests/migrations"))).await);
    Product::create(app.db(), p("a")).await.unwrap();
    let a = app.clone();
    // The future is Send, so it can be spawned.
    let joined = tokio::spawn(async move {
        a.assert_database_has("products\" ; DROP TABLE products; --", &[])
            .await;
    })
    .await;
    assert!(joined.is_err(), "unknown table must fail the assertion");
    app.assert_database_count("products", 1).await;
}

// ---------------------------------------------------------------- boundaries

#[renox::test]
async fn where_in_empty_list() {
    let k = kernel().await;
    Product::create(k.db(), p("a")).await.unwrap();
    let none: Vec<i64> = Vec::new();
    assert!(
        Product::query()
            .where_in("id", none)
            .get(k.db())
            .await
            .unwrap()
            .is_empty()
    );
}

#[renox::test]
async fn where_in_with_a_huge_list() {
    // 70 000 ids: over PostgreSQL's 65 535 bind limit and SQLite's default 32 766.
    let k = kernel().await;
    let a = Product::create(k.db(), p("a")).await.unwrap();
    let mut ids: Vec<i64> = (100_000..170_000).collect();
    ids.push(a.id);
    let started = Instant::now();
    let found = Product::query().where_in("id", ids).get(k.db()).await;
    eprintln!(
        "where_in 70k on {:?}: {:?} in {:?}",
        k.db().dialect(),
        found.as_ref().map(Vec::len).map_err(|e| format!("{e:?}")),
        started.elapsed()
    );
    assert_eq!(found.unwrap().len(), 1);
}

#[renox::test]
async fn huge_limit_and_offset_are_clamped() {
    let k = kernel().await;
    Product::create(k.db(), p("a")).await.unwrap();
    let all = Product::query().limit(u64::MAX).get(k.db()).await;
    eprintln!(
        "limit(u64::MAX): {:?}",
        all.as_ref().map(Vec::len).map_err(|e| format!("{e:?}"))
    );
    let none = Product::query().offset(u64::MAX).get(k.db()).await;
    eprintln!(
        "offset(u64::MAX): {:?}",
        none.as_ref().map(Vec::len).map_err(|e| format!("{e:?}"))
    );
    assert_eq!(all.unwrap().len(), 1, "a huge limit means no limit");
    assert_eq!(none.unwrap().len(), 0, "a huge offset means nothing");
}

#[renox::test]
async fn paginate_page_zero_and_huge() {
    let k = kernel().await;
    for i in 0..3 {
        Product::create(k.db(), p(&format!("p{i}"))).await.unwrap();
    }
    let first = Product::query().paginate(k.db(), 0, 2).await.unwrap();
    assert_eq!((first.page, first.items.len()), (1, 2));
    let far = Product::query()
        .paginate(k.db(), u32::MAX, 1000)
        .await
        .unwrap();
    assert!(far.items.is_empty());
    assert_eq!(far.last_page, 1);
    assert!(!far.has_next);
    let zero_per_page = Product::query().paginate(k.db(), 1, 0).await.unwrap();
    assert_eq!(zero_per_page.per_page, 1);
}

#[renox::test]
async fn find_or_404_on_missing_id() {
    let k = kernel().await;
    let err = Product::find_or_404(k.db(), 424242).await.unwrap_err();
    assert_eq!(err.status(), StatusCode::NOT_FOUND);
    let err = Product::find_or_404(k.db(), -1).await.unwrap_err();
    assert_eq!(err.status(), StatusCode::NOT_FOUND);
}

// ---------------------------------------------------------------- integrity

#[renox::test]
async fn saving_a_deleted_row_is_not_found() {
    let k = kernel().await;
    let mut a = Product::create(k.db(), p("a")).await.unwrap();
    a.force_delete(k.db()).await.unwrap();
    a.name = "b".into();
    let err = a.save(k.db()).await.unwrap_err();
    assert_eq!(err.status(), StatusCode::NOT_FOUND);
    assert_eq!(
        Product::query().with_trashed().count(k.db()).await.unwrap(),
        0,
        "no resurrection"
    );
}

#[renox::test]
async fn unique_violation_is_a_conflict() {
    let k = kernel().await;
    let db = k.db();
    renox::db::sql(format!(
        "CREATE TABLE uniq (id {}, code TEXT NOT NULL UNIQUE)",
        pk(db.dialect())
    ))
    .execute(db)
    .await
    .unwrap();
    renox::db::sql("INSERT INTO uniq (code) VALUES (?)")
        .bind("A")
        .execute(db)
        .await
        .unwrap();
    let err = renox::db::sql("INSERT INTO uniq (code) VALUES (?)")
        .bind("A")
        .execute(db)
        .await
        .unwrap_err();
    assert!(err.is_unique_violation(), "DbError reports it: {err}");
    assert!(!err.is_foreign_key_violation());
    let err: Error = err.into();
    eprintln!("unique violation -> {} {:?}", err.status(), err);
    // Robust: a duplicate is a 409/422 the app can show, not a generic 500.
    assert_ne!(err.status(), StatusCode::INTERNAL_SERVER_ERROR);
}

#[renox::test]
async fn foreign_key_and_not_null_violations_error() {
    let k = kernel().await;
    let db = k.db();
    let fk = Note::create(
        db,
        Note {
            product_id: Some(999),
            body: "x".into(),
            ..Default::default()
        },
    )
    .await;
    assert!(fk.is_err(), "foreign keys are enforced");
    let nn = renox::db::sql("INSERT INTO products (name, price) VALUES (?, ?)")
        .bind(None::<String>)
        .bind(1)
        .execute(db)
        .await;
    assert!(nn.is_err());
    assert_eq!(Note::query().count(db).await.unwrap(), 0);
}

// ---------------------------------------------------------------- 2. transactions

#[renox::test]
async fn transaction_error_and_drop_roll_back() {
    let k = kernel().await;
    let db = k.db();
    async fn work(db: &Db) -> Result {
        let mut tx = db.begin().await?;
        Product::create(&mut tx, p("in-tx")).await?;
        Err(Error::BadRequest("boom".into()))?;
        tx.commit().await?;
        Ok(())
    }
    assert!(work(db).await.is_err());
    {
        let mut tx = db.begin().await.unwrap();
        Product::create(&mut tx, p("dropped")).await.unwrap();
    }
    let mut tx = db.begin().await.unwrap();
    Product::create(&mut tx, p("rolled")).await.unwrap();
    tx.rollback().await.unwrap();
    assert_eq!(Product::query().with_trashed().count(db).await.unwrap(), 0);
}

#[renox::test]
async fn nested_begin_on_the_test_pool_fails_fast() {
    // With a transaction open, starting another (or using `&db`) must not
    // deadlock the in-memory/test pool (1 connection on SQLite).
    let k = kernel().await;
    let db = k.db();
    let mut tx = db.begin().await.unwrap();
    Product::create(&mut tx, p("outer")).await.unwrap();
    let started = Instant::now();
    let inner = tokio::time::timeout(Duration::from_secs(5), db.begin()).await;
    eprintln!(
        "nested begin on {:?}: {} after {:?}",
        db.dialect(),
        match &inner {
            Ok(Ok(_)) => "ok".to_owned(),
            Ok(Err(e)) => format!("error {e}"),
            Err(_) => "HUNG (timeout)".to_owned(),
        },
        started.elapsed()
    );
    drop(inner);
    tx.rollback().await.unwrap();
    assert!(
        started.elapsed() < Duration::from_secs(4),
        "nested begin hung"
    );
}

/// SQLite has one writer. A write through `&db` while this task's own
/// transaction holds the lock can't succeed; it must fail within
/// `busy_timeout` with "database is locked", not hang.
#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn file_sqlite_write_while_own_transaction_is_open_fails_fast() {
    let dir = tempfile::tempdir().unwrap();
    let url = format!("sqlite://{}/app.db", dir.path().display());
    let k = kernel_cfg(
        {
            let mut c = config();
            c.database_url = url;
            c
        },
        &[],
    )
    .await;
    let db = k.db();
    let mut tx = db.begin().await.unwrap();
    Product::create(&mut tx, p("outer")).await.unwrap();
    let started = Instant::now();
    let other = Product::create(db, p("other")).await;
    tx.commit().await.unwrap();
    let err = format!("{:?}", other.unwrap_err());
    assert!(err.contains("database is locked"), "{err}");
    // busy_timeout is 5 s; slow CI runners add a few more.
    assert!(
        started.elapsed() < Duration::from_secs(20),
        "it waited, but not forever"
    );
}

// ---------------------------------------------------------------- 3. migrations

const M_A: Migration = Migration::new(
    "20300101000000_m_a",
    "CREATE TABLE m_a (id BIGINT PRIMARY KEY)",
    Some("DROP TABLE m_a"),
);
const M_BAD: Migration = Migration::new(
    "20300101000001_m_bad",
    "CREATE TABLE m_b1 (id BIGINT PRIMARY KEY); THIS IS NOT SQL;",
    Some("DROP TABLE m_b1"),
);
const M_C: Migration = Migration::new(
    "20300101000002_m_c",
    "CREATE TABLE m_c (id BIGINT PRIMARY KEY)",
    Some("DROP TABLE m_c"),
);
const M_C_NO_DOWN: Migration = Migration::new(
    "20300101000002_m_c",
    "CREATE TABLE m_c (id BIGINT PRIMARY KEY)",
    None,
);
const M_A_NO_DOWN: Migration = Migration::new(
    "20300101000000_m_a",
    "CREATE TABLE m_a (id BIGINT PRIMARY KEY)",
    None,
);
const M_A_EDITED: Migration = Migration::new(
    "20300101000000_m_a",
    "CREATE TABLE m_a (id BIGINT PRIMARY KEY, extra TEXT)",
    Some("DROP TABLE m_a"),
);

async fn table_exists(db: &Db, table: &str) -> bool {
    let sql = match db.dialect() {
        Dialect::Sqlite => "SELECT COUNT(*) FROM sqlite_master WHERE name = ?",
        Dialect::Postgres => {
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?"
        }
    };
    renox::db::sql(sql)
        .bind(table)
        .scalar::<i64>(db)
        .await
        .unwrap()
        > 0
}

async fn boot(config: Config, migrations: &[Migration]) -> Kernel {
    App::with_config(config)
        .migrations(migrations)
        .boot()
        .await
        .unwrap()
}

#[renox::test]
async fn failing_migration_mid_batch() {
    let k = boot(config(), &[M_A, M_BAD, M_C]).await;
    let err = k.migrate().await.unwrap_err();
    eprintln!("failing migration: {err:?}");
    let status = k.migration_status().await.unwrap();
    let ran: Vec<_> = status
        .iter()
        .filter(|m| m.name.starts_with("2030"))
        .map(|m| (m.name.clone(), m.batch))
        .collect();
    eprintln!("status after failure: {ran:?}");
    assert!(
        table_exists(k.db(), "m_a").await,
        "earlier migrations are kept"
    );
    assert!(
        !table_exists(k.db(), "m_b1").await,
        "the failed one is rolled back entirely"
    );
    assert!(!table_exists(k.db(), "m_c").await, "later ones don't run");
}

#[renox::test]
async fn rollback_with_a_missing_down_is_all_or_nothing() {
    // Batch = [m_a (no down), m_c (down)]; rollback undoes m_c then fails on m_a.
    let k = boot(config(), &[M_A_NO_DOWN, M_C]).await;
    k.migrate().await.unwrap();
    let err = k.rollback(1).await.unwrap_err();
    eprintln!("rollback without .down.sql: {err:?}");
    let m_c_gone = !table_exists(k.db(), "m_c").await;
    eprintln!("m_c dropped anyway: {m_c_gone}");
    assert!(!m_c_gone, "the batch was half rolled back before the error");

    // And the other order: the newest has no down -> nothing happens.
    let k = boot(config(), &[M_A, M_C_NO_DOWN]).await;
    k.migrate().await.unwrap();
    assert!(k.rollback(1).await.is_err());
    assert!(table_exists(k.db(), "m_a").await && table_exists(k.db(), "m_c").await);
}

#[renox::test]
async fn edited_and_removed_migrations_on_a_file_database() {
    let dir = tempfile::tempdir().unwrap();
    let url = format!("sqlite://{}/app.db", dir.path().display());
    let cfg = || {
        let mut c = config();
        c.database_url = url.clone();
        c
    };
    let k = boot(cfg(), &[M_A, M_C]).await;
    k.migrate().await.unwrap();
    k.db().close().await;
    drop(k);

    // Edited after being applied: silently ignored?
    let k = boot(cfg(), &[M_A_EDITED, M_C]).await;
    let done = k.migrate().await.unwrap();
    let status = k.migration_status().await.unwrap();
    eprintln!(
        "edited migration: migrate ran {done:?}; status says {:?}",
        status
            .iter()
            .find(|m| m.name == M_A.name())
            .map(|m| m.batch)
    );
    k.db().close().await;
    drop(k);

    // Removed but still in renox_migrations.
    let k = boot(cfg(), &[M_A]).await;
    let status = k.migration_status().await.unwrap();
    let listed = status.iter().any(|m| m.name == M_C.name());
    eprintln!("removed migration listed by migrate:status: {listed}");
    let rollback = k.rollback(1).await;
    eprintln!(
        "rollback with a removed migration: {:?}",
        rollback.as_ref().map_err(|e| format!("{e:?}"))
    );
    assert!(
        listed,
        "migrate:status should show applied migrations that are no longer registered"
    );
    assert!(
        rollback.is_ok(),
        "one missing file blocks rolling back its batch forever"
    );
}

const PG_OBJECTS: Migration = Migration::new("20300101000010_pg_objects", "CREATE TABLE parent (id BIGINT PRIMARY KEY);
         CREATE TABLE child (id BIGINT PRIMARY KEY, parent_id BIGINT REFERENCES parent (id));
         CREATE VIEW child_view AS SELECT c.id, p.id AS pid FROM child c JOIN parent p ON p.id = c.parent_id;
         CREATE VIEW child_view2 AS SELECT id FROM child_view;", None).postgres("CREATE TYPE mood AS ENUM ('happy', 'sad');
             CREATE SEQUENCE invoice_no;
             CREATE TABLE parent (id BIGINT PRIMARY KEY, m mood);
             CREATE TABLE child (id BIGINT PRIMARY KEY, parent_id BIGINT REFERENCES parent (id));
             CREATE VIEW child_view AS SELECT c.id, p.id AS pid FROM child c JOIN parent p ON p.id = c.parent_id;
             CREATE VIEW child_view2 AS SELECT id FROM child_view;
             CREATE MATERIALIZED VIEW child_mv AS SELECT id FROM child;
             CREATE FUNCTION add1(i BIGINT) RETURNS BIGINT AS 'SELECT i + 1' LANGUAGE SQL;", None);

#[renox::test]
async fn migrate_fresh_with_views_foreign_keys_and_types() {
    let k = boot(config(), &[PG_OBJECTS]).await;
    k.migrate().await.unwrap();
    let first = k.fresh().await;
    eprintln!(
        "fresh #1 on {:?}: {:?}",
        k.db().dialect(),
        first.as_ref().map(Vec::len).map_err(|e| format!("{e:?}"))
    );
    let second = k.fresh().await;
    eprintln!(
        "fresh #2: {:?}",
        second.as_ref().map(Vec::len).map_err(|e| format!("{e:?}"))
    );
    assert!(first.is_ok() && second.is_ok());
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn concurrent_migrate_runs_wait_for_each_other() {
    // Two replicas running `my-app migrate` at deploy time.
    let k = boot(config(), &[M_A, M_C]).await;
    let (a, b) = tokio::join!(k.migrate(), k.migrate());
    eprintln!(
        "concurrent migrate on {:?}: {:?} / {:?}",
        k.db().dialect(),
        a.as_ref().map(Vec::len).map_err(|e| format!("{e:?}")),
        b.as_ref().map(Vec::len).map_err(|e| format!("{e:?}"))
    );
    assert!(
        a.is_ok() && b.is_ok(),
        "one should wait for the other (a lock), not fail"
    );
}

#[renox::test]
async fn migration_with_its_own_transaction_or_concurrently_runs() {
    const OWN_TX: Migration = Migration::new("20300101000020_own_tx", "BEGIN; CREATE TABLE own_tx (id BIGINT PRIMARY KEY); COMMIT;", None).postgres("CREATE TABLE own_tx (id BIGINT PRIMARY KEY); CREATE INDEX CONCURRENTLY own_tx_id ON own_tx (id);", None);
    let k = boot(config(), &[OWN_TX]).await;
    let r = k.migrate().await;
    eprintln!(
        "migration with BEGIN/COMMIT (sqlite) or CONCURRENTLY (pg): {:?}",
        r.as_ref().map_err(|e| format!("{e:?}"))
    );
    assert!(r.is_ok());
}

// ---------------------------------------------------------------- 8. cache

async fn cache_app(store: &str) -> TestApp {
    let store = match store {
        "database" => renox::CacheStore::Database,
        _ => renox::CacheStore::Memory,
    };
    TestApp::with_config(App::new(), move |c| c.cache_store = store).await
}

#[renox::test]
async fn cache_ttl_zero_is_not_kept() {
    for store in ["memory", "database"] {
        let app = cache_app(store).await;
        let cache = &app.state().cache;
        cache.put("k", &1, Some(Duration::ZERO)).await.unwrap();
        let got: Option<i32> = cache.get("k").await.unwrap();
        eprintln!("{store}: put(ttl=0) then get -> {got:?}");
        cache
            .put("sub", &1, Some(Duration::from_millis(1500)))
            .await
            .unwrap();
        tokio::time::sleep(Duration::from_millis(1100)).await;
        let sub: Option<i32> = cache.get("sub").await.unwrap();
        eprintln!("{store}: ttl=1.5s, read after 1.1s -> {sub:?}");
        assert_eq!(
            got, None,
            "{store}: a zero TTL keeps the value for up to a second"
        );
    }
}

#[renox::test]
async fn cache_huge_values_and_type_mismatch() {
    for store in ["memory", "database"] {
        let app = cache_app(store).await;
        let cache = &app.state().cache;
        let big = "x".repeat(8 * 1024 * 1024);
        cache.put("big", &big, None).await.unwrap();
        let back: Option<String> = cache.get("big").await.unwrap();
        assert_eq!(back.map(|s| s.len()), Some(big.len()));

        cache.put("n", &"not a number", None).await.unwrap();
        assert!(
            cache.get::<i64>("n").await.is_err(),
            "{store}: a wrong type is an error"
        );
        let recomputed = cache
            .remember("n", Duration::from_secs(60), || async { Ok(7i64) })
            .await
            .unwrap();
        assert_eq!(
            recomputed, 7,
            "{store}: remember computes a value of another type again"
        );
    }
}

#[renox::test(flavor = "multi_thread", worker_threads = 4)]
async fn cache_concurrent_remember_computes_once() {
    for store in ["memory", "database"] {
        let app = cache_app(store).await;
        let cache = app.state().cache.clone();
        let calls = Arc::new(AtomicUsize::new(0));
        let mut tasks = Vec::new();
        for _ in 0..20 {
            let (cache, calls) = (cache.clone(), calls.clone());
            tasks.push(tokio::spawn(async move {
                cache
                    .remember("slow", Duration::from_secs(60), || async {
                        calls.fetch_add(1, Ordering::SeqCst);
                        tokio::time::sleep(Duration::from_millis(200)).await;
                        Ok(42i64)
                    })
                    .await
            }));
        }
        for t in tasks {
            assert_eq!(t.await.unwrap().unwrap(), 42);
        }
        let n = calls.load(Ordering::SeqCst);
        eprintln!("{store}: 20 concurrent remember() -> compute ran {n} times");
        assert_eq!(n, 1, "{store}: cache stampede");
    }
}

#[renox::test]
async fn cache_database_store_without_table() {
    let app = cache_app("database").await;
    renox::db::sql("DROP TABLE cache")
        .execute(app.db())
        .await
        .unwrap();
    let cache = &app.state().cache;
    assert!(cache.put("k", &1, None).await.is_err());
    assert!(cache.get::<i32>("k").await.is_err());
}

// ---------------------------------------------------------------- 9. storage

#[renox::test]
async fn storage_hostile_keys() {
    let app = TestApp::new(App::new()).await;
    let s = &app.state().storage;
    let data = || Bytes::from_static(b"hello");
    for bad in ["../x", "a/../../x", "a\\..\\x", "./x", "", "/"] {
        assert!(s.put(bad, data()).await.is_err(), "{bad:?} accepted");
    }
    // NUL: an error, not a panic.
    assert!(s.put("a\0b", data()).await.is_err());
    assert!(s.get("a\0b").await.is_err());
    // Absolute paths are made relative (stay inside the root).
    s.put("/etc/passwd-probe", data()).await.unwrap();
    assert!(!std::path::Path::new("/etc/passwd-probe").exists());
    assert!(s.exists("etc/passwd-probe").await.unwrap());
    // Unicode and overwrite.
    s.put("ünï/😀 file.txt", data()).await.unwrap();
    s.put("ünï/😀 file.txt", Bytes::from_static(b"second"))
        .await
        .unwrap();
    assert_eq!(
        s.get("ünï/😀 file.txt").await.unwrap().unwrap(),
        Bytes::from_static(b"second")
    );
    // Deleting a missing file.
    s.delete("nope/missing.txt").await.unwrap();
    assert_eq!(s.get("nope/missing.txt").await.unwrap(), None);
}

#[renox::test]
async fn storage_temporary_url_with_huge_ttl() {
    let app = TestApp::new(App::new()).await;
    let state = app.state().clone();
    state
        .storage
        .put("doc.txt", Bytes::from_static(b"hi"))
        .await
        .unwrap();
    let zero = state
        .storage
        .temporary_url(&state, "doc.txt", Duration::ZERO)
        .await
        .unwrap();
    eprintln!("ttl 0 url: {zero}");
    let st = state.clone();
    let huge = tokio::spawn(async move {
        st.storage
            .temporary_url(&st, "doc.txt", Duration::MAX)
            .await
    })
    .await;
    eprintln!(
        "ttl Duration::MAX: {}",
        match &huge {
            Ok(Ok(url)) => format!("ok {url}"),
            Ok(Err(e)) => format!("error {e:?}"),
            Err(e) => format!("PANIC {e}"),
        }
    );
    assert!(huge.is_ok(), "temporary_url panics on a huge TTL");
    let url = huge.unwrap().unwrap();
    let path = url.trim_start_matches(&state.config.url);
    app.get(path).await.assert_ok();
}

#[cfg(unix)]
#[renox::test]
async fn storage_read_only_directory() {
    use std::os::unix::fs::PermissionsExt;
    let app = TestApp::new(App::new()).await;
    let s = &app.state().storage;
    s.put("ok.txt", Bytes::from_static(b"x")).await.unwrap();
    let root = app.state().config.storage_path.join("app");
    std::fs::set_permissions(&root, std::fs::Permissions::from_mode(0o555)).unwrap();
    // Root (e.g. in a container) ignores directory permissions: nothing to test.
    let probe = root.join(".probe");
    if std::fs::write(&probe, b"").is_ok() {
        let _ = std::fs::remove_file(&probe);
        std::fs::set_permissions(&root, std::fs::Permissions::from_mode(0o755)).unwrap();
        eprintln!("read-only storage: skipped, permissions aren't enforced for this user");
        return;
    }
    let r = s.put("new/file.txt", Bytes::from_static(b"x")).await;
    let r2 = s.put("ok.txt", Bytes::from_static(b"y")).await;
    let r3 = s.delete("ok.txt").await;
    std::fs::set_permissions(&root, std::fs::Permissions::from_mode(0o755)).unwrap();
    eprintln!(
        "read-only storage: put new {:?}; overwrite {:?}; delete {:?}",
        r.as_ref().map_err(|e| e.status()),
        r2.as_ref().map_err(|e| e.status()),
        r3.as_ref().map_err(|e| e.status())
    );
    assert!(r.is_err() && r3.is_err());
}

// ---------------------------------------------------------------- 11. boot

#[renox::test]
async fn invalid_app_key_fails_boot() {
    let r = App::with_config({
        let mut c = config();
        c.key = Some("short".into());
        c
    })
    .boot()
    .await;
    assert!(r.is_err());
    let r = App::with_config({
        let mut c = config();
        c.key = Some("base64:!!!".into());
        c
    })
    .boot()
    .await;
    assert!(r.is_err());
}

struct ModA;
impl Module for ModA {
    fn name(&self) -> &'static str {
        "a"
    }
    fn routes(&self) -> Routes {
        Routes::new().get("/same", || async { "a" }).name("same")
    }
}
struct ModB;
impl Module for ModB {
    fn name(&self) -> &'static str {
        "b"
    }
    fn routes(&self) -> Routes {
        Routes::new().get("/same", || async { "b" }).name("other")
    }
}
struct ModC;
impl Module for ModC {
    fn name(&self) -> &'static str {
        "c"
    }
    fn routes(&self) -> Routes {
        Routes::new().get("/c", || async { "c" }).name("same")
    }
}

#[renox::test]
async fn duplicate_route_names_and_paths_across_modules_fail_boot() {
    let names = App::with_config(config())
        .module(ModA)
        .module(ModC)
        .boot()
        .await;
    eprintln!("duplicate route name: {:?}", names.as_ref().err());
    assert!(names.is_err());

    let paths = tokio::spawn(async {
        App::with_config(config())
            .module(ModA)
            .module(ModB)
            .boot()
            .await
            .map(|_| ())
    })
    .await;
    eprintln!(
        "duplicate path across modules: {}",
        match &paths {
            Ok(Ok(())) => "booted (one silently wins?)".to_owned(),
            Ok(Err(e)) => format!("boot error {e:?}"),
            Err(e) => format!("PANIC {e}"),
        }
    );
    assert!(
        matches!(paths, Ok(Err(_))),
        "a clean boot error, not a panic"
    );
}

#[renox::test]
async fn zero_pool_size_is_a_boot_error() {
    let dir = tempfile::tempdir().unwrap();
    let r = tokio::time::timeout(
        Duration::from_secs(10),
        tokio::spawn(
            App::with_config({
                let mut c = config();
                c.database_url = format!("sqlite://{}/x.db", dir.path().display());
                c.database_pool_size = 0;
                c
            })
            .boot(),
        ),
    )
    .await;
    let desc = match &r {
        Err(_) => "HUNG".to_owned(),
        Ok(Err(e)) => format!("PANIC {e}"),
        Ok(Ok(Err(e))) => format!("error {e:?}"),
        Ok(Ok(Ok(_))) => "booted".to_owned(),
    };
    eprintln!("DATABASE_POOL_SIZE=0: {desc}");
    assert!(matches!(r, Ok(Ok(Err(_)))), "expected a clean config error");
}

#[renox::test]
async fn unique_rule_with_a_mistyped_column_is_an_error() {
    // `unique("products", "name_typo")` with the value already present in `name`:
    // must be an error (no such column), not a silent pass.
    let k = kernel().await;
    let db = k.db();
    Product::create(db, p("dup")).await.unwrap();
    let mut v = Validator::new();
    v.field("name", &"dup".to_owned())
        .unique("products", "name_typo");
    let unique = v.finish(db).await;
    let mut v = Validator::new();
    v.field("name", &"dup".to_owned())
        .exists("products", "name_typo");
    let exists = v.finish(db).await;
    let show = |r: &Result<Errors>| match r {
        Ok(e) => format!("ok, {} field error(s)", e.iter().count()),
        Err(e) => format!("error {e:?}"),
    };
    eprintln!(
        "mistyped column on {:?}: unique -> {}; exists -> {}",
        db.dialect(),
        show(&unique),
        show(&exists)
    );
    let raw =
        renox::db::sql("SELECT COUNT(*) FROM products WHERE \"no_such_column\" = 'no_such_column'")
            .scalar::<i64>(db)
            .await;
    eprintln!(
        "raw SQL with an unknown double-quoted column: {:?}",
        raw.as_ref().map_err(|e| e.to_string())
    );
    assert!(
        unique.is_err(),
        "a typo'd column makes `unique` always pass"
    );
}

struct Viewer;
impl Module for Viewer {
    fn name(&self) -> &'static str {
        "viewer"
    }
    fn routes(&self) -> Routes {
        Routes::new().get("/page", || async { view("home.html", context! {}) })
    }
}

#[renox::test]
async fn missing_views_directory() {
    let app = TestApp::with_config(App::new().module(Viewer), |c| {
        c.views_path = "/nonexistent/views".into();
        c.debug = false;
    })
    .await;
    let r = app.get("/page").await;
    eprintln!(
        "missing views dir: boot ok; GET /page -> {} ({} bytes)",
        r.status,
        r.body.len()
    );
    r.assert_status(500);
    app.get("/nope").await.assert_status(404);
}

// ---------------------------------------------------------------- boot and requests

#[renox::test]
async fn database_url_with_an_unknown_scheme_is_refused() {
    for url in ["postgress://app:s3cret@db/app", "mysql://app:s3cret@db/app"] {
        let err = App::with_config({
            let mut c = config();
            c.database_url = url.into();
            c
        })
        .boot()
        .await
        .err()
        .map(|e| format!("{e:?}"))
        .unwrap_or_default();
        assert!(err.contains("must start with sqlite:"), "{url}: {err}");
        assert!(!err.contains("s3cret"), "the password is hidden: {err}");
    }
}

struct Faulty;
impl Module for Faulty {
    fn name(&self) -> &'static str {
        "faulty"
    }
    fn routes(&self) -> Routes {
        Routes::new()
            .get("/panic", || async {
                if true {
                    panic!("handler panicked");
                }
                "unreachable"
            })
            .get("/slow", || async {
                tokio::time::sleep(Duration::from_secs(5)).await;
                "too late"
            })
            .get("/ok", || async { "ok" })
    }
}

#[renox::test]
async fn a_panicking_or_slow_handler_answers_500_and_the_app_keeps_serving() {
    let app = TestApp::with_config(App::new().module(Faulty), |c| {
        c.request_timeout = Some(Duration::from_secs(1));
    })
    .await;
    let res = app.get("/panic").await;
    assert_eq!(res.status, StatusCode::INTERNAL_SERVER_ERROR);
    assert!(
        res.text().contains("Internal Server Error"),
        "the error page: {}",
        res.text()
    );
    let started = Instant::now();
    assert_eq!(
        app.get("/slow").await.status,
        StatusCode::INTERNAL_SERVER_ERROR
    );
    assert!(
        started.elapsed() < Duration::from_secs(3),
        "REQUEST_TIMEOUT cut it short"
    );
    app.get("/ok").await.assert_ok();
}

/// A request stuck before its handler (database sessions waiting for a
/// connection) still ends near `REQUEST_TIMEOUT`, not at the pool's acquire
/// timeout (#219).
#[renox::test]
async fn request_timeout_also_bounds_the_session_layer() {
    // A file database: `TEST_DATABASE_URL` swaps only in-memory ones, so this
    // runs on SQLite in the PostgreSQL suite too.
    let dir = tempfile::tempdir().unwrap();
    let url = format!("sqlite://{}", dir.path().join("app.db").display());
    let app = TestApp::with_config(App::new().module(Faulty), |c| {
        c.request_timeout = Some(Duration::from_secs(1));
        c.session_driver = renox::SessionDriver::Database;
        c.database_url = url;
        c.database_pool_size = 1;
        c.database_acquire_timeout = Duration::from_secs(20);
        // Under `testing`, database sessions live in memory; this needs the table.
        c.env = Environment::Local;
    })
    .await;
    app.get("/ok").await.assert_ok(); // a session row and its cookie
    let held = app.db().begin().await.unwrap(); // the pool's only connection
    let started = Instant::now();
    let res = app.get("/ok").await;
    assert_eq!(res.status, StatusCode::INTERNAL_SERVER_ERROR);
    assert!(
        started.elapsed() < Duration::from_secs(6),
        "{:?}",
        started.elapsed()
    );
    assert!(
        started.elapsed() >= Duration::from_secs(1),
        "it waited for the session"
    );
    drop(held);
    app.get("/ok").await.assert_ok();
}

#[renox::test]
async fn a_no_transaction_migration_runs_outside_the_wrapper() {
    const MARKED: Migration = Migration::new(
        "20300101000030_marked",
        "-- renox:no-transaction\nCREATE TABLE marked (id BIGINT PRIMARY KEY);",
        Some("DROP TABLE marked"),
    );
    let k = boot(config(), &[MARKED]).await;
    assert!(
        k.migrate()
            .await
            .unwrap()
            .iter()
            .any(|m| m == MARKED.name())
    );
    assert!(table_exists(k.db(), "marked").await);
    assert!(
        k.rollback(1)
            .await
            .unwrap()
            .iter()
            .any(|m| m == MARKED.name())
    );
    assert!(!table_exists(k.db(), "marked").await);
}
