//! #254: data-layer paths no test had reached, on SQLite and (with
//! `TEST_DATABASE_URL`) PostgreSQL: large `where_in` lists of text, `NOT
//! LIKE`, `OFFSET` alone, invalid columns in aggregates and updates, model
//! edge cases, relation loaders with nothing to load, typed extra columns
//! of users, the shell's interactive mode, and `simple_pagination`.

use renox::db::{Dialect, Model};
use renox::prelude::*;
use renox::testing::TestApp;

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "labels")]
struct Label {
    id: i64,
    code: String,
    name: String,
}

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "bare_rows")]
struct BareRow {
    id: i64,
}

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "notes", hooks)]
struct Note {
    id: i64,
    label_id: i64,
    body: String,
}

static SAVED: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

// Only `saved` is overridden: `saving`, `deleting` and `deleted` keep their
// defaults.
impl renox::db::ModelHooks for Note {
    async fn saved(&self, _creating: bool) -> Result {
        SAVED.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        Ok(())
    }
}

async fn app() -> TestApp {
    let app = TestApp::new(App::new().module(Auth::new())).await;
    let id = match app.db().dialect() {
        Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "INTEGER PRIMARY KEY",
    };
    for statement in [
        format!("CREATE TABLE labels (id {id}, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL)"),
        format!("CREATE TABLE bare_rows (id {id})"),
        format!("CREATE TABLE notes (id {id}, label_id BIGINT NOT NULL, body TEXT NOT NULL)"),
    ] {
        renox::db::sql(statement).execute(app.db()).await.unwrap();
    }
    app
}

async fn label(app: &TestApp, code: &str, name: &str) -> Label {
    Label::create(
        app.db(),
        Label {
            code: code.into(),
            name: name.into(),
            ..Default::default()
        },
    )
    .await
    .unwrap()
}

#[renox::test]
async fn where_in_with_a_large_list_of_text() {
    let app = app().await;
    label(&app, "01JA", "first").await;
    label(&app, "01JB", "second").await;
    label(&app, "01JC", "third").await;
    // Over a thousand values go as one JSON array, for text as for numbers.
    let mut codes: Vec<String> = (0..1500).map(|i| format!("X{i:05}")).collect();
    codes.push("01JA".into());
    codes.push("01JC".into());
    let found = Label::query()
        .where_in("code", codes)
        .order_by("code")
        .get(app.db())
        .await
        .unwrap();
    let names: Vec<&str> = found.iter().map(|l| l.name.as_str()).collect();
    assert_eq!(names, ["first", "third"]);
    // A list that isn't all text (here a NULL in it) can't go as one array:
    // plain placeholders, same answer.
    let mut mixed: Vec<renox::db::DbValue> = (0..1200)
        .map(|i| renox::db::DbValue::Text(format!("Y{i}")))
        .collect();
    mixed.push(renox::db::DbValue::Null);
    mixed.push(renox::db::DbValue::Text("01JB".into()));
    let found = Label::query()
        .where_in("code", mixed)
        .get(app.db())
        .await
        .unwrap();
    assert_eq!(found.len(), 1);
}

#[renox::test]
async fn not_like_ignores_case_offset_works_alone() {
    let app = app().await;
    label(&app, "a", "Coffee").await;
    label(&app, "b", "tea").await;
    label(&app, "c", "COCOA").await;
    let rest = Label::query()
        .where_op("name", "not like", "co%")
        .get(app.db())
        .await
        .unwrap();
    assert_eq!(rest.len(), 1, "{rest:?}");
    assert_eq!(rest[0].name, "tea");
    let skipped = Label::query()
        .order_by("code")
        .offset(1)
        .get(app.db())
        .await
        .unwrap();
    let codes: Vec<&str> = skipped.iter().map(|l| l.code.as_str()).collect();
    assert_eq!(codes, ["b", "c"]);
}

#[renox::test]
async fn aggregates_and_updates_refuse_unknown_columns() {
    let app = app().await;
    let db = app.db();
    let q = || Label::query();
    assert!(
        q().sum::<i64, _>(db, "price; DROP TABLE labels")
            .await
            .is_err()
    );
    assert!(q().avg(db, "nope").await.is_err());
    assert!(q().min::<i64, _>(db, "nope").await.is_err());
    assert!(q().max::<i64, _>(db, "nope").await.is_err());
    assert!(q().increment(db, "nope", 1).await.is_err());
    assert!(q().update(db, &[("nope", &"x")]).await.is_err());
    assert!(
        q().where_in_query("id", BareRow::query(), "nope")
            .get(db)
            .await
            .is_err()
    );
    // The table is still there.
    assert_eq!(q().count(db).await.unwrap(), 0);
}

#[renox::test]
async fn model_edge_cases() {
    let app = app().await;
    let db = app.db();
    // A model with only an id inserts DEFAULT VALUES.
    let bare = BareRow::create(db, BareRow::default()).await.unwrap();
    assert!(bare.id > 0);
    // Upsert needs a conflict target; with nothing to update it skips.
    let err = Label::upsert(db, vec![Label::default()], &[], &[])
        .await
        .unwrap_err();
    assert!(format!("{err:?}").contains("upsert needs at least one `unique_by` column"));
    label(&app, "x", "Original").await;
    Label::upsert(
        db,
        vec![Label {
            code: "x".into(),
            name: "Changed".into(),
            ..Default::default()
        }],
        &["code"],
        &[],
    )
    .await
    .unwrap();
    let kept = Label::query()
        .where_eq("code", "x")
        .first(db)
        .await
        .unwrap()
        .unwrap();
    assert_eq!(kept.name, "Original");
    assert_eq!(Label::insert_many(db, Vec::new()).await.unwrap(), 0);
    // save_only on a row that was never saved is refused; on a row deleted
    // meanwhile it's a 404.
    let mut unsaved = Label::default();
    assert!(unsaved.save_only(db, &["name"]).await.is_err());
    let mut gone = label(&app, "g", "Gone").await;
    renox::db::sql("DELETE FROM labels WHERE id = ?")
        .bind(gone.id)
        .execute(db)
        .await
        .unwrap();
    gone.name = "Back".into();
    assert!(matches!(
        gone.save_only(db, &["name"]).await,
        Err(Error::NotFound)
    ));
}

#[renox::test]
async fn default_hooks_run_around_the_one_overridden() {
    let app = app().await;
    let db = app.db();
    let before = SAVED.load(std::sync::atomic::Ordering::SeqCst);
    let mut note = Note::create(
        db,
        Note {
            label_id: 1,
            body: "hi".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    note.delete(db).await.unwrap();
    assert!(SAVED.load(std::sync::atomic::Ordering::SeqCst) > before);
}

#[renox::test]
async fn relation_loaders_with_nothing_to_load() {
    let app = app().await;
    let db = app.db();
    let none: Vec<Label> = Vec::new();
    let notes =
        renox::db::relations::has_many(db, &none, Note::query(), "label_id", |n: &Note| n.label_id)
            .await
            .unwrap();
    assert!(notes.is_empty());
    let none: Vec<Note> = Vec::new();
    let labels = renox::db::relations::belongs_to::<Label, _, _>(db, &none, |n: &Note| n.label_id)
        .await
        .unwrap();
    assert!(labels.is_empty());
}

#[renox::test]
async fn user_extra_columns_come_back_as_json() {
    let app = app().await;
    let db = app.db();
    let columns = match db.dialect() {
        Dialect::Postgres => vec![
            "ALTER TABLE users ADD COLUMN active BOOLEAN DEFAULT TRUE",
            "ALTER TABLE users ADD COLUMN born DATE DEFAULT '2000-01-02'",
            "ALTER TABLE users ADD COLUMN seen TIMESTAMPTZ DEFAULT '2026-10-01 09:30:00+00'",
            "ALTER TABLE users ADD COLUMN local_seen TIMESTAMP DEFAULT '2026-10-01 09:30:00'",
            "ALTER TABLE users ADD COLUMN score REAL DEFAULT 1.5",
            "ALTER TABLE users ADD COLUMN visits INTEGER DEFAULT 3",
            "ALTER TABLE users ADD COLUMN level SMALLINT DEFAULT 2",
            "ALTER TABLE users ADD COLUMN prefs JSONB DEFAULT '{\"a\": 1}'",
        ],
        _ => vec![
            "ALTER TABLE users ADD COLUMN score REAL DEFAULT 1.5",
            "ALTER TABLE users ADD COLUMN visits INTEGER DEFAULT 3",
            "ALTER TABLE users ADD COLUMN nickname TEXT",
        ],
    };
    for statement in columns {
        renox::db::sql(statement).execute(db).await.unwrap();
    }
    let ann = User::register(db, "Ann", "ann@example.com", "password123")
        .await
        .unwrap();
    assert_eq!(ann.get::<f64>("score"), Some(1.5));
    assert_eq!(ann.get::<i64>("visits"), Some(3));
    if db.dialect() == Dialect::Postgres {
        assert_eq!(ann.get::<bool>("active"), Some(true));
        assert_eq!(ann.get::<i64>("level"), Some(2));
        assert_eq!(ann.get::<String>("born").as_deref(), Some("2000-01-02"));
        assert_eq!(
            ann.get::<String>("seen").as_deref(),
            Some("2026-10-01T09:30:00+00:00")
        );
        assert_eq!(
            ann.get::<String>("local_seen").as_deref(),
            Some("2026-10-01T09:30:00")
        );
        assert_eq!(ann.get::<serde_json::Value>("prefs").unwrap()["a"], 1);
    } else {
        assert_eq!(ann.get::<String>("nickname"), None);
    }
}

#[renox::test]
async fn the_shell_prompts_when_interactive_and_says_when_there_are_no_rows() {
    let app = app().await;
    let input = b".tables\nSELECT * FROM labels\n  WHERE code = 'none';\n\n.exit\n".as_slice();
    let mut out = Vec::new();
    renox::shell::run_with(app.db(), input, &mut out, true)
        .await
        .unwrap();
    let out = String::from_utf8(out).unwrap();
    assert!(out.contains("shell. End statements with `;`"), "{out}");
    assert!(out.contains("sql> ") && out.contains("...> "), "{out}");
    assert!(out.contains("labels"), "{out}");
    assert!(out.contains("(no rows)"), "{out}");
}

struct Pages;

impl Module for Pages {
    fn name(&self) -> &'static str {
        "pages"
    }

    fn routes(&self) -> Routes {
        Routes::new().get(
            "/labels",
            |State(db): State<Db>, Page(page): Page| async move {
                let labels = Label::query()
                    .order_by("code")
                    .simple_paginate(&db, page, 2)
                    .await?;
                Ok::<_, Error>(view("labels.html", context! { labels }))
            },
        )
    }
}

#[renox::test]
async fn simple_pagination_draws_previous_and_next() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(
        dir.path().join("labels.html"),
        r#"{% from "renox/pagination.html" import simple_pagination %}{% for l in labels.items %}{{ l.code }} {% endfor %}{{ simple_pagination(labels) }}"#,
    )
    .unwrap();
    let path = dir.path().to_path_buf();
    let app = TestApp::with_config(App::new().module(Auth::new()).module(Pages), move |c| {
        c.views_path = path
    })
    .await;
    let id = match app.db().dialect() {
        Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "INTEGER PRIMARY KEY",
    };
    renox::db::sql(format!(
        "CREATE TABLE labels (id {id}, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL)"
    ))
    .execute(app.db())
    .await
    .unwrap();
    for code in ["a", "b", "c"] {
        label(&app, code, code).await;
    }
    let first = app.get("/labels").await;
    first.assert_ok().assert_see("a b ").assert_see("page=2");
    let second = app.get("/labels?page=2").await;
    second.assert_see("c ").assert_see("page=1");
}

/// A `DATABASE_URL` that is itself `postgres://` (as in production, not the
/// test swap of an in-memory URL), read from the environment with its pool
/// size and statement timeout, on a database made for this test. Runs only
/// with `TEST_DATABASE_URL`.
#[cfg(feature = "postgres")]
#[renox::test]
async fn a_postgres_database_url_connects_directly() {
    let Some(url) = std::env::var("TEST_DATABASE_URL")
        .ok()
        .filter(|url| url.starts_with("postgres"))
    else {
        return; // no PostgreSQL to connect to
    };
    // Boot only on the shared database (no migrations): it makes the test's own.
    let mut shared = Config::default();
    shared.database_url = url.clone();
    let server = App::with_config(shared).boot().await.unwrap();
    let name = format!(
        "renox_direct_{}_{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    renox::db::sql(format!("CREATE DATABASE {name}"))
        .execute(server.db())
        .await
        .unwrap();
    let base = url.split('?').next().unwrap();
    let own = format!("{}/{name}", base.rsplit_once('/').unwrap().0);
    let config = Config::from_vars(|var| match var {
        "DATABASE_URL" => Some(own.clone()),
        "DATABASE_POOL_SIZE" => Some("2".into()),
        "DATABASE_STATEMENT_TIMEOUT" => Some("7".into()),
        _ => None,
    })
    .unwrap();
    let kernel = App::with_config(config).boot().await.unwrap();
    let db = kernel.db();
    assert_eq!(db.dialect(), Dialect::Postgres);
    assert_eq!(db.postgres().unwrap().options().get_max_connections(), 2);
    let timeout: String = renox::db::sql("SHOW statement_timeout")
        .scalar(db)
        .await
        .unwrap();
    assert_eq!(timeout, "7s");
    let database: String = renox::db::sql("SELECT current_database()::text")
        .scalar(db)
        .await
        .unwrap();
    assert_eq!(database, name);
    db.close().await;
    renox::db::sql(format!("DROP DATABASE {name} WITH (FORCE)"))
        .execute(server.db())
        .await
        .unwrap();
}

/// Unknown columns name the table and the column, whichever method meets
/// them first; a row lock is rendered only for PostgreSQL.
#[renox::test]
async fn unknown_columns_are_named_and_locks_render_per_dialect() {
    let app = app().await;
    let db = app.db();
    let says = |err: Error, column: &str| {
        let text = format!("{err:?}");
        assert!(
            text.contains(&format!("`labels` has no column `{column}`")),
            "{text}"
        );
    };
    says(
        Label::query().sum::<i64, _>(db, "nope").await.unwrap_err(),
        "nope",
    );
    says(Label::query().avg(db, "nope").await.unwrap_err(), "nope");
    says(
        Label::query().min::<i64, _>(db, "nope").await.unwrap_err(),
        "nope",
    );
    says(
        Label::query().max::<i64, _>(db, "nope").await.unwrap_err(),
        "nope",
    );
    says(
        Label::query().increment(db, "nope", 1).await.unwrap_err(),
        "nope",
    );
    says(
        Label::query()
            .update(db, &[("nope", &"x")])
            .await
            .unwrap_err(),
        "nope",
    );
    // The outer column of `where_in_query`, and the children's foreign key
    // of `where_has` / `where_doesnt_have`.
    says(
        Label::query()
            .where_in_query("nope", Note::query(), "label_id")
            .get(db)
            .await
            .unwrap_err(),
        "nope",
    );
    for query in [
        Label::query().where_has(Note::query(), "nope"),
        Label::query().where_doesnt_have(Note::query(), "nope"),
    ] {
        let text = format!("{:?}", query.get(db).await.unwrap_err());
        assert!(text.contains("`notes` has no column `nope`"), "{text}");
    }

    let locked = Label::query().where_eq("code", "a").lock_for_update();
    let (postgres, _) = locked.to_sql(Dialect::Postgres).unwrap();
    assert!(postgres.ends_with(" FOR UPDATE"), "{postgres}");
    let (sqlite, _) = locked.to_sql(Dialect::Sqlite).unwrap();
    assert!(!sqlite.contains("FOR "), "{sqlite}");
    let (shared, _) = Label::query()
        .shared_lock()
        .to_sql(Dialect::Postgres)
        .unwrap();
    assert!(shared.ends_with(" FOR SHARE"), "{shared}");
    // The locked read runs inside a transaction on either database.
    label(&app, "a", "A").await;
    let mut tx = db.begin().await.unwrap();
    let row = locked.first(&mut tx).await.unwrap().unwrap();
    assert_eq!(row.name, "A");
    tx.commit().await.unwrap();
}

/// A duplicate is a unique violation (SQLite's 2067, PostgreSQL's 23505);
/// neither it nor other errors are worth retrying.
#[renox::test]
async fn unique_violations_are_recognised_and_not_retried() {
    let app = app().await;
    let db = app.db();
    label(&app, "dup", "First").await;
    let err = Label::create(
        db,
        Label {
            code: "dup".into(),
            name: "Second".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap_err();
    assert!(err.is_unique_violation(), "{err:?}");
    assert!(!err.is_retryable(), "{err:?}");
    assert!(!Error::NotFound.is_unique_violation());
    assert!(!Error::NotFound.is_retryable());
    let plain = Error::from(anyhow::anyhow!("not a database error"));
    assert!(!plain.is_unique_violation());
    assert!(!plain.is_retryable());
}

/// `first_or_create` losing a race: the row appears between its read and
/// its insert, the insert hits the unique index, and the winner's row is
/// returned. SQLite: another runtime inserts it from `make` (a file
/// database, so that runtime opens its own connection).
#[renox::test]
async fn first_or_create_returns_the_row_that_won_the_race() {
    let dir = tempfile::tempdir().unwrap();
    let url = format!("sqlite://{}/race.db", dir.path().display());
    let app = TestApp::with_config(App::new(), move |c| c.database_url = url).await;
    let db = app.db().clone();
    renox::db::sql("CREATE TABLE labels (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL)")
        .execute(&db)
        .await
        .unwrap();
    let other = db.clone();
    let found = Label::query()
        .where_eq("code", "race")
        .first_or_create(&db, move || {
            std::thread::spawn(move || {
                tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                    .unwrap()
                    .block_on(async {
                        Label::create(
                            &other,
                            Label {
                                code: "race".into(),
                                name: "Winner".into(),
                                ..Default::default()
                            },
                        )
                        .await
                        .unwrap();
                    })
            })
            .join()
            .unwrap();
            Label {
                code: "race".into(),
                name: "Loser".into(),
                ..Default::default()
            }
        })
        .await
        .unwrap();
    assert_eq!(found.name, "Winner");
    assert_eq!(Label::query().count(&db).await.unwrap(), 1);
}

/// The same race on PostgreSQL: a sequence hides the winner's row from the
/// first read only. Runs only with `TEST_DATABASE_URL`.
#[renox::test]
async fn first_or_create_returns_the_winner_on_postgres() {
    let app = app().await;
    let db = app.db();
    if db.dialect() != Dialect::Postgres {
        return;
    }
    label(&app, "race", "Winner").await;
    renox::db::sql("CREATE SEQUENCE race_reads")
        .execute(db)
        .await
        .unwrap();
    let found = Label::query()
        .where_eq("code", "race")
        .where_raw("nextval('race_reads') > 1", Vec::<i64>::new())
        .first_or_create(db, || Label {
            code: "race".into(),
            name: "Loser".into(),
            ..Default::default()
        })
        .await
        .unwrap();
    assert_eq!(found.name, "Winner");
}

/// `retrying` and `transaction_retrying` try again after a serialization
/// failure (40001) and give up after the last attempt. PostgreSQL only: it
/// raises the code from SQL (SQLite's busy errors are unit-tested in
/// renox-core's db/conn.rs).
#[renox::test]
async fn retrying_tries_again_after_a_serialization_failure() {
    use std::sync::Arc;
    use std::sync::atomic::{AtomicU32, Ordering};

    let app = app().await;
    let db = app.db().clone();
    if db.dialect() != Dialect::Postgres {
        return;
    }
    const CONFLICT: &str = "DO $$ BEGIN RAISE EXCEPTION 'conflict' USING ERRCODE = '40001'; END $$";
    let tries = Arc::new(AtomicU32::new(0));
    let counter = tries.clone();
    let conn = db.clone();
    let value = db
        .retrying(3, move || {
            let conn = conn.clone();
            let counter = counter.clone();
            async move {
                if counter.fetch_add(1, Ordering::SeqCst) == 0 {
                    renox::db::sql(CONFLICT).execute(&conn).await?;
                }
                Ok(7)
            }
        })
        .await
        .unwrap();
    assert_eq!((value, tries.load(Ordering::SeqCst)), (7, 2));

    let tries = Arc::new(AtomicU32::new(0));
    let counter = tries.clone();
    let err = db
        .transaction_retrying(2, move |tx| {
            counter.fetch_add(1, Ordering::SeqCst);
            Box::pin(async move {
                renox::db::sql(CONFLICT).execute(tx).await?;
                Ok(())
            })
        })
        .await
        .unwrap_err();
    assert!(err.is_retryable(), "{err:?}");
    assert_eq!(tries.load(Ordering::SeqCst), 2);
}

/// Saving a model with only an id, or with nothing changed, writes nothing.
#[renox::test]
async fn saving_nothing_new_writes_nothing() {
    let app = app().await;
    let db = app.db();
    let mut bare = BareRow::create(db, BareRow::default()).await.unwrap();
    bare.save(db).await.unwrap();
    assert_eq!(BareRow::query().count(db).await.unwrap(), 1);
    let mut kept = label(&app, "same", "Same").await;
    let original = kept.clone();
    assert!(!kept.save_changes(db, &original).await.unwrap());
    kept.name = "Changed".into();
    assert!(kept.save_changes(db, &original).await.unwrap());
}

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "tags")]
struct Tag {
    id: i64,
    name: String,
}

#[derive(serde::Serialize, Debug, FromRow)]
struct Linked {
    note: String,
}

const LABEL_TAGS: renox::db::relations::Pivot =
    renox::db::relations::Pivot::new("label_tags", "label_id", "tag_id").with_timestamps();

/// Loaders given no parents answer without a query, `Pivot` is built in a
/// const and prints its columns, and `update_pivot` on a pair that isn't
/// linked says so.
#[renox::test]
async fn relation_loaders_and_pivots_with_nothing_to_do() {
    let app = app().await;
    let db = app.db();
    let id = match db.dialect() {
        Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "INTEGER PRIMARY KEY",
    };
    for statement in [
        format!("CREATE TABLE tags (id {id}, name TEXT NOT NULL)"),
        "CREATE TABLE label_tags (label_id BIGINT NOT NULL, tag_id BIGINT NOT NULL, \
         note TEXT, created_at TEXT, updated_at TEXT)"
            .to_owned(),
    ] {
        renox::db::sql(statement).execute(db).await.unwrap();
    }
    let none: Vec<Label> = Vec::new();
    let through = renox::db::relations::has_many_through(
        db,
        &none,
        Note::query(),
        "label_id",
        |n: &Note| n.label_id,
        BareRow::query(),
        "id",
        |b: &BareRow| b.id,
    )
    .await
    .unwrap();
    assert!(through.is_empty());
    let tags: std::collections::HashMap<i64, Vec<Tag>> =
        LABEL_TAGS.load(db, Vec::new()).await.unwrap();
    assert!(tags.is_empty());
    let with: std::collections::HashMap<i64, Vec<(Tag, Linked)>> =
        LABEL_TAGS.load_with_pivot(db, Vec::new()).await.unwrap();
    assert!(with.is_empty());
    let parents = renox::db::relations::Morph::new("kind", "owner_id")
        .parents::<Label, Note>(db, &[], |n| ("labels".into(), n.label_id))
        .await
        .unwrap();
    assert!(parents.is_empty());

    let copy = LABEL_TAGS;
    let shown = format!("{copy:?}");
    assert!(
        shown.contains("label_tags") && shown.contains("timestamps: true"),
        "{shown}"
    );
    assert!(
        !LABEL_TAGS
            .update_pivot(db, 1, 2, &[("note", &"x")])
            .await
            .unwrap()
    );
}

/// A user's TIME column reads as text (it read as `null` on PostgreSQL),
/// and a BLOB as `null`, as documented.
#[renox::test]
async fn user_time_and_blob_columns_come_back_as_json() {
    let app = app().await;
    let db = app.db();
    let (time, blob) = match db.dialect() {
        Dialect::Postgres => ("TIME DEFAULT '09:30:00'", "BYTEA DEFAULT '\\x0102'"),
        _ => ("TEXT DEFAULT '09:30:00'", "BLOB DEFAULT x'0102'"),
    };
    for statement in [
        format!("ALTER TABLE users ADD COLUMN opens {time}"),
        format!("ALTER TABLE users ADD COLUMN avatar {blob}"),
    ] {
        renox::db::sql(statement).execute(db).await.unwrap();
    }
    let ann = User::register(db, "Ann", "ann@example.com", "password123")
        .await
        .unwrap();
    assert_eq!(ann.get::<String>("opens").as_deref(), Some("09:30:00"));
    assert_eq!(ann.get::<String>("avatar"), None);
}

/// The raw sqlx rows, `Debug` that shows only shapes, a `Json` column read
/// from a column of another type, and a migration that is only a comment.
#[renox::test]
async fn rows_debug_output_and_json_type_checks() {
    let app = app().await;
    let db = app.db();
    label(&app, "r", "Row").await;
    let rows = renox::db::sql("SELECT id, code FROM labels")
        .fetch_all(db)
        .await
        .unwrap();
    let row = &rows[0];
    match db.dialect() {
        Dialect::Sqlite => assert!(row.sqlite().is_some()),
        #[cfg(feature = "postgres")]
        Dialect::Postgres => {
            assert!(row.postgres().is_some());
            assert!(row.sqlite().is_none());
        }
        #[allow(unreachable_patterns)]
        _ => {}
    }
    #[cfg(feature = "postgres")]
    if db.dialect() == Dialect::Sqlite {
        assert!(row.postgres().is_none());
    }
    assert!(format!("{row:?}").contains("[\"id\", \"code\"]"), "{row:?}");
    assert!(format!("{db:?}").contains("dialect"), "{db:?}");
    let tx = db.begin().await.unwrap();
    assert!(format!("{tx:?}").starts_with("Transaction"), "{tx:?}");
    drop(tx);
    // An id isn't JSON text.
    assert!(
        row.try_get::<renox::db::Json<serde_json::Value>>("id")
            .is_err()
    );
    let code: renox::db::Json<String> = renox::db::sql("SELECT '\"x\"' AS code")
        .fetch_one(db)
        .await
        .unwrap()
        .try_get("code")
        .unwrap();
    assert_eq!(code.0, "x");
}

/// A statement that fails prints its error and the shell goes on; a value
/// of a type the shell can't show is `?` (PostgreSQL's INTERVAL), a blob
/// its size, NULL as `NULL`; input ending without `.quit` ends the shell.
#[renox::test]
async fn the_shell_reports_errors_and_shows_what_it_cant_print() {
    let app = app().await;
    let db = app.db();
    let odd = match db.dialect() {
        Dialect::Postgres => {
            "SELECT INTERVAL '1 day' AS gap, CAST(NULL AS TEXT) AS empty, \
             CAST('\\x0102' AS BYTEA) AS raw, CAST(2 AS SMALLINT) AS small, \
             CAST(1.5 AS REAL) AS ratio, TRUE AS yes, DATE '2026-01-02' AS day;"
        }
        _ => "SELECT NULL AS empty, x'0102' AS raw, 1.5 AS ratio;",
    };
    let input =
        format!("SELECT * FROM no_such_table;\nINSERT INTO bare_rows DEFAULT VALUES;\n{odd}\n");
    let mut out = Vec::new();
    renox::shell::run_with(db, input.as_bytes(), &mut out, false)
        .await
        .unwrap();
    let out = String::from_utf8(out).unwrap();
    assert!(out.contains("Error: "), "{out}");
    assert!(out.contains("OK (1 row(s) affected)"), "{out}");
    assert!(
        out.contains("NULL") && out.contains("<2 bytes>") && out.contains("1.5"),
        "{out}"
    );
    if db.dialect() == Dialect::Postgres {
        let values = out.lines().find(|l| l.contains("<2 bytes>")).unwrap();
        assert!(values.trim_start().starts_with('?'), "{out}");
        assert!(
            values.contains("true") && values.contains("2026-01-02"),
            "{out}"
        );
    }
}
