//! #254: data-layer paths no test had reached, on SQLite and (with
//! `TEST_DATABASE_URL`) PostgreSQL: large `where_in` lists of text, `NOT
//! LIKE`, `OFFSET` alone, invalid columns in aggregates and updates, model
//! edge cases, relation loaders with nothing to load, typed extra columns
//! of users, the shell's interactive mode, and `simple_pagination`.

use renox::db::{Dialect, Model};
use renox::prelude::*;
use renox::testing::TestApp;

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "labels")]
struct Label {
    id: i64,
    code: String,
    name: String,
}

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "bare_rows")]
struct BareRow {
    id: i64,
}

#[derive(Model, serde::Serialize, Default, Clone, Debug)]
#[model(table = "notes", hooks)]
struct Note {
    id: i64,
    label_id: i64,
    body: String,
}

static SAVED: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

// Only `saved` is overridden: `saving`, `deleting` and `deleted` keep their
// defaults.
impl renox::db::ModelHooks for Note {
    async fn saved(&self, _creating: bool) -> Result {
        SAVED.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        Ok(())
    }
}

async fn app() -> TestApp {
    let app = TestApp::new(App::new().module(Auth::new())).await;
    let id = match app.db().dialect() {
        Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "INTEGER PRIMARY KEY",
    };
    for statement in [
        format!("CREATE TABLE labels (id {id}, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL)"),
        format!("CREATE TABLE bare_rows (id {id})"),
        format!("CREATE TABLE notes (id {id}, label_id BIGINT NOT NULL, body TEXT NOT NULL)"),
    ] {
        renox::db::sql(statement).execute(app.db()).await.unwrap();
    }
    app
}

async fn label(app: &TestApp, code: &str, name: &str) -> Label {
    Label::create(
        app.db(),
        Label {
            code: code.into(),
            name: name.into(),
            ..Default::default()
        },
    )
    .await
    .unwrap()
}

#[renox::test]
async fn where_in_with_a_large_list_of_text() {
    let app = app().await;
    label(&app, "01JA", "first").await;
    label(&app, "01JB", "second").await;
    label(&app, "01JC", "third").await;
    // Over a thousand values go as one JSON array, for text as for numbers.
    let mut codes: Vec<String> = (0..1500).map(|i| format!("X{i:05}")).collect();
    codes.push("01JA".into());
    codes.push("01JC".into());
    let found = Label::query()
        .where_in("code", codes)
        .order_by("code")
        .get(app.db())
        .await
        .unwrap();
    let names: Vec<&str> = found.iter().map(|l| l.name.as_str()).collect();
    assert_eq!(names, ["first", "third"]);
    // A list that isn't all text (here a NULL in it) can't go as one array:
    // plain placeholders, same answer.
    let mut mixed: Vec<renox::db::DbValue> = (0..1200)
        .map(|i| renox::db::DbValue::Text(format!("Y{i}")))
        .collect();
    mixed.push(renox::db::DbValue::Null);
    mixed.push(renox::db::DbValue::Text("01JB".into()));
    let found = Label::query()
        .where_in("code", mixed)
        .get(app.db())
        .await
        .unwrap();
    assert_eq!(found.len(), 1);
}

#[renox::test]
async fn not_like_ignores_case_offset_works_alone() {
    let app = app().await;
    label(&app, "a", "Coffee").await;
    label(&app, "b", "tea").await;
    label(&app, "c", "COCOA").await;
    let rest = Label::query()
        .where_op("name", "not like", "co%")
        .get(app.db())
        .await
        .unwrap();
    assert_eq!(rest.len(), 1, "{rest:?}");
    assert_eq!(rest[0].name, "tea");
    let skipped = Label::query()
        .order_by("code")
        .offset(1)
        .get(app.db())
        .await
        .unwrap();
    let codes: Vec<&str> = skipped.iter().map(|l| l.code.as_str()).collect();
    assert_eq!(codes, ["b", "c"]);
}

#[renox::test]
async fn aggregates_and_updates_refuse_unknown_columns() {
    let app = app().await;
    let db = app.db();
    let q = || Label::query();
    assert!(
        q().sum::<i64, _>(db, "price; DROP TABLE labels")
            .await
            .is_err()
    );
    assert!(q().avg(db, "nope").await.is_err());
    assert!(q().min::<i64, _>(db, "nope").await.is_err());
    assert!(q().max::<i64, _>(db, "nope").await.is_err());
    assert!(q().increment(db, "nope", 1).await.is_err());
    assert!(q().update(db, &[("nope", &"x")]).await.is_err());
    assert!(
        q().where_in_query("id", BareRow::query(), "nope")
            .get(db)
            .await
            .is_err()
    );
    // The table is still there.
    assert_eq!(q().count(db).await.unwrap(), 0);
}

#[renox::test]
async fn model_edge_cases() {
    let app = app().await;
    let db = app.db();
    // A model with only an id inserts DEFAULT VALUES.
    let bare = BareRow::create(db, BareRow::default()).await.unwrap();
    assert!(bare.id > 0);
    // Upsert needs a conflict target; with nothing to update it skips.
    let err = Label::upsert(db, vec![Label::default()], &[], &[])
        .await
        .unwrap_err();
    assert!(format!("{err:?}").contains("upsert needs at least one `unique_by` column"));
    label(&app, "x", "Original").await;
    Label::upsert(
        db,
        vec![Label {
            code: "x".into(),
            name: "Changed".into(),
            ..Default::default()
        }],
        &["code"],
        &[],
    )
    .await
    .unwrap();
    let kept = Label::query()
        .where_eq("code", "x")
        .first(db)
        .await
        .unwrap()
        .unwrap();
    assert_eq!(kept.name, "Original");
    assert_eq!(Label::insert_many(db, Vec::new()).await.unwrap(), 0);
    // save_only on a row that was never saved is refused; on a row deleted
    // meanwhile it's a 404.
    let mut unsaved = Label::default();
    assert!(unsaved.save_only(db, &["name"]).await.is_err());
    let mut gone = label(&app, "g", "Gone").await;
    renox::db::sql("DELETE FROM labels WHERE id = ?")
        .bind(gone.id)
        .execute(db)
        .await
        .unwrap();
    gone.name = "Back".into();
    assert!(matches!(
        gone.save_only(db, &["name"]).await,
        Err(Error::NotFound)
    ));
}

#[renox::test]
async fn default_hooks_run_around_the_one_overridden() {
    let app = app().await;
    let db = app.db();
    let before = SAVED.load(std::sync::atomic::Ordering::SeqCst);
    let mut note = Note::create(
        db,
        Note {
            label_id: 1,
            body: "hi".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    note.delete(db).await.unwrap();
    assert!(SAVED.load(std::sync::atomic::Ordering::SeqCst) > before);
}

#[renox::test]
async fn relation_loaders_with_nothing_to_load() {
    let app = app().await;
    let db = app.db();
    let none: Vec<Label> = Vec::new();
    let notes =
        renox::db::relations::has_many(db, &none, Note::query(), "label_id", |n: &Note| n.label_id)
            .await
            .unwrap();
    assert!(notes.is_empty());
    let none: Vec<Note> = Vec::new();
    let labels = renox::db::relations::belongs_to::<Label, _, _>(db, &none, |n: &Note| n.label_id)
        .await
        .unwrap();
    assert!(labels.is_empty());
}

#[renox::test]
async fn user_extra_columns_come_back_as_json() {
    let app = app().await;
    let db = app.db();
    let columns = match db.dialect() {
        Dialect::Postgres => vec![
            "ALTER TABLE users ADD COLUMN active BOOLEAN DEFAULT TRUE",
            "ALTER TABLE users ADD COLUMN born DATE DEFAULT '2000-01-02'",
            "ALTER TABLE users ADD COLUMN seen TIMESTAMPTZ DEFAULT '2026-10-01 09:30:00+00'",
            "ALTER TABLE users ADD COLUMN local_seen TIMESTAMP DEFAULT '2026-10-01 09:30:00'",
            "ALTER TABLE users ADD COLUMN score REAL DEFAULT 1.5",
            "ALTER TABLE users ADD COLUMN visits INTEGER DEFAULT 3",
            "ALTER TABLE users ADD COLUMN level SMALLINT DEFAULT 2",
            "ALTER TABLE users ADD COLUMN prefs JSONB DEFAULT '{\"a\": 1}'",
        ],
        _ => vec![
            "ALTER TABLE users ADD COLUMN score REAL DEFAULT 1.5",
            "ALTER TABLE users ADD COLUMN visits INTEGER DEFAULT 3",
            "ALTER TABLE users ADD COLUMN nickname TEXT",
        ],
    };
    for statement in columns {
        renox::db::sql(statement).execute(db).await.unwrap();
    }
    let ann = User::register(db, "Ann", "ann@example.com", "password123")
        .await
        .unwrap();
    assert_eq!(ann.get::<f64>("score"), Some(1.5));
    assert_eq!(ann.get::<i64>("visits"), Some(3));
    if db.dialect() == Dialect::Postgres {
        assert_eq!(ann.get::<bool>("active"), Some(true));
        assert_eq!(ann.get::<i64>("level"), Some(2));
        assert_eq!(ann.get::<String>("born").as_deref(), Some("2000-01-02"));
        assert_eq!(
            ann.get::<String>("seen").as_deref(),
            Some("2026-10-01T09:30:00+00:00")
        );
        assert_eq!(
            ann.get::<String>("local_seen").as_deref(),
            Some("2026-10-01T09:30:00")
        );
        assert_eq!(ann.get::<serde_json::Value>("prefs").unwrap()["a"], 1);
    } else {
        assert_eq!(ann.get::<String>("nickname"), None);
    }
}

#[renox::test]
async fn the_shell_prompts_when_interactive_and_says_when_there_are_no_rows() {
    let app = app().await;
    let input = b".tables\nSELECT * FROM labels\n  WHERE code = 'none';\n\n.exit\n".as_slice();
    let mut out = Vec::new();
    renox::shell::run_with(app.db(), input, &mut out, true)
        .await
        .unwrap();
    let out = String::from_utf8(out).unwrap();
    assert!(out.contains("shell. End statements with `;`"), "{out}");
    assert!(out.contains("sql> ") && out.contains("...> "), "{out}");
    assert!(out.contains("labels"), "{out}");
    assert!(out.contains("(no rows)"), "{out}");
}

struct Pages;

impl Module for Pages {
    fn name(&self) -> &'static str {
        "pages"
    }

    fn routes(&self) -> Routes {
        Routes::new().get(
            "/labels",
            |State(db): State<Db>, Page(page): Page| async move {
                let labels = Label::query()
                    .order_by("code")
                    .simple_paginate(&db, page, 2)
                    .await?;
                Ok::<_, Error>(view("labels.html", context! { labels }))
            },
        )
    }
}

#[renox::test]
async fn simple_pagination_draws_previous_and_next() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(
        dir.path().join("labels.html"),
        r#"{% from "renox/pagination.html" import simple_pagination %}{% for l in labels.items %}{{ l.code }} {% endfor %}{{ simple_pagination(labels) }}"#,
    )
    .unwrap();
    let path = dir.path().to_path_buf();
    let app = TestApp::with_config(App::new().module(Auth::new()).module(Pages), move |c| {
        c.views_path = path
    })
    .await;
    let id = match app.db().dialect() {
        Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "INTEGER PRIMARY KEY",
    };
    renox::db::sql(format!(
        "CREATE TABLE labels (id {id}, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL)"
    ))
    .execute(app.db())
    .await
    .unwrap();
    for code in ["a", "b", "c"] {
        label(&app, code, code).await;
    }
    let first = app.get("/labels").await;
    first.assert_ok().assert_see("a b ").assert_see("page=2");
    let second = app.get("/labels?page=2").await;
    second.assert_see("c ").assert_see("page=1");
}

/// A `DATABASE_URL` that is itself `postgres://` (as in production, not the
/// test swap of an in-memory URL): the pool connects and answers. Runs only
/// with `TEST_DATABASE_URL`.
#[cfg(feature = "postgres")]
#[renox::test]
async fn a_postgres_database_url_connects_directly() {
    let Some(url) = std::env::var("TEST_DATABASE_URL")
        .ok()
        .filter(|url| url.starts_with("postgres"))
    else {
        return; // no PostgreSQL to connect to
    };
    let mut config = Config::default();
    config.database_url = url;
    config.database_pool_size = 2;
    config.database_statement_timeout = Some(std::time::Duration::from_secs(5));
    // Boot only: no migrations, so nothing is written to the shared database.
    let kernel = App::with_config(config).boot().await.unwrap();
    assert_eq!(kernel.db().dialect(), Dialect::Postgres);
    let one: i64 = renox::db::sql("SELECT CAST(1 AS BIGINT)")
        .scalar(kernel.db())
        .await
        .unwrap();
    assert_eq!(one, 1);
}
