use std::time::Duration;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use renox::Kernel;
use renox::prelude::*;
use tower::ServiceExt;

struct Shop;

impl Module for Shop {
    fn name(&self) -> &'static str {
        "shop"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get("/", || async { view("home.html", ()) })
            .name("home")
            .get("/products", || async { "list" })
            .post("/products", || async { "saved" })
            .name("products")
            .get("/search", || async { "results" })
            .throttle(10, Duration::from_secs(60))
            .merge(
                Routes::new()
                    .get("/orders", || async { "orders" })
                    .name("orders.index")
                    .require_auth(),
            )
    }
}

async fn kernel(dir: &std::path::Path, env: Environment) -> Kernel {
    std::fs::create_dir_all(dir.join("views")).unwrap();
    std::fs::write(
        dir.join("views/home.html"),
        "<head>{{ renox_head() }}</head>v1",
    )
    .unwrap();
    let config = {
        let mut c = Config::default();
        c.env = env;
        c.key = Some(renox::generate_key());
        c.views_path = dir.join("views");
        c.public_path = dir.join("public");
        c.lang_path = dir.join("lang");
        c
    };
    let kernel = App::with_config(config)
        .module(Auth::new())
        .module(Shop)
        .boot()
        .await
        .unwrap();
    kernel.migrate().await.unwrap();
    kernel
}

#[tokio::test]
async fn routes_are_listed_with_names_modules_and_guards() {
    let dir = tempfile::tempdir().unwrap();
    let kernel = kernel(dir.path(), Environment::Testing).await;
    let find = |method: &str, path: &str| {
        kernel
            .routes()
            .iter()
            .find(|r| r.method == method && r.path == path)
            .unwrap_or_else(|| panic!("{method} {path} missing"))
            .clone()
    };

    let get = find("GET", "/products");
    assert_eq!(
        (get.name.as_deref(), get.module.as_str()),
        (Some("products"), "shop"),
        "a name covers every method of its path"
    );
    assert_eq!(find("POST", "/products").name.as_deref(), Some("products"));
    assert_eq!(find("GET", "/search").middleware, ["throttle:10/60s"]);
    assert_eq!(find("GET", "/orders").middleware, ["auth"]);
    assert_eq!(find("GET", "/login").middleware, ["guest"]);
    assert_eq!(find("GET", "/login").module, "auth");
    assert_eq!(find("GET", "/health").module, "renox");
    assert!(
        kernel.routes().iter().all(|r| r.path != "/_renox/live"),
        "no live reload outside local"
    );

    let paths: Vec<&str> = kernel.routes().iter().map(|r| r.path.as_str()).collect();
    let mut sorted = paths.clone();
    sorted.sort();
    assert_eq!(paths, sorted, "sorted by path");
}

#[tokio::test]
async fn db_shell_runs_statements() {
    let dir = tempfile::tempdir().unwrap();
    let kernel = kernel(dir.path(), Environment::Testing).await;
    let (table, blob) = match kernel.db().dialect() {
        renox::db::Dialect::Sqlite => (
            "CREATE TABLE notes (id INTEGER PRIMARY KEY, body TEXT, score REAL, raw BLOB);",
            "x'0102'",
        ),
        renox::db::Dialect::Postgres => (
            "CREATE TABLE notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
             body TEXT, score DOUBLE PRECISION, raw BYTEA);",
            "'\\x0102'::bytea",
        ),
    };
    let input = format!(
        ".tables\n{table}\n\
INSERT INTO notes (body, score, raw) VALUES ('note', 1.5, {blob}), (NULL, 2, NULL);\n\
SELECT id, body,\n  score, raw FROM notes ORDER BY id;\nSELECT * FROM missing;\n.quit\nSELECT 1;\n"
    );
    let input = input.as_bytes();
    let mut out = Vec::new();
    renox::shell::run_with(kernel.db(), input, &mut out, false)
        .await
        .unwrap();
    let out = String::from_utf8(out).unwrap();

    assert!(out.lines().next().unwrap().contains("users"), "{out}");
    assert!(out.contains("OK (2 row(s) affected)"), "{out}");
    assert!(out.contains("id | body | score | raw"), "{out}");
    assert!(out.contains("1  | note | 1.5   | <2 bytes>"), "{out}");
    assert!(out.contains("2  | NULL | 2     | NULL"), "{out}");
    assert!(out.contains("(2 row(s))"), "{out}");
    assert!(
        out.contains("Error: error returned from database:") && out.contains("missing"),
        "{out}"
    );
    assert!(
        !out.contains("(1 row(s))"),
        "nothing runs after .quit: {out}"
    );
}

async fn next_event(body: &mut Body) -> String {
    let frame = tokio::time::timeout(Duration::from_secs(5), body.frame())
        .await
        .expect("an event within 5 s")
        .unwrap()
        .unwrap();
    String::from_utf8(frame.into_data().unwrap().to_vec()).unwrap()
}

#[tokio::test]
async fn live_reload_while_developing_locally() {
    let dir = tempfile::tempdir().unwrap();
    let kernel = kernel(dir.path(), Environment::Local).await;
    let page = kernel
        .router()
        .oneshot(Request::get("/").body(Body::empty()).unwrap())
        .await
        .unwrap();
    let page = String::from_utf8(
        page.into_body()
            .collect()
            .await
            .unwrap()
            .to_bytes()
            .to_vec(),
    )
    .unwrap();
    assert!(page.contains(r#"<meta name="renox-live" content="1">"#));

    let res = kernel
        .router()
        .oneshot(Request::get("/_renox/live").body(Body::empty()).unwrap())
        .await
        .unwrap();
    assert_eq!(res.headers()["content-type"], "text/event-stream");
    let mut body = res.into_body();
    let boot = next_event(&mut body).await;
    assert!(
        boot.contains("event: boot") && boot.contains("retry: 500"),
        "{boot}"
    );

    tokio::time::sleep(Duration::from_millis(600)).await;
    std::fs::write(
        dir.path().join("views/home.html"),
        "<head>{{ renox_head() }}</head>v2",
    )
    .unwrap();
    let mut event = next_event(&mut body).await;
    while event.trim().starts_with(':') {
        event = next_event(&mut body).await; // keep-alive comments
    }
    assert!(event.contains("event: reload"), "{event}");
}

#[tokio::test]
async fn no_live_reload_outside_local_development() {
    let dir = tempfile::tempdir().unwrap();
    let kernel = kernel(dir.path(), Environment::Testing).await;
    let res = kernel
        .router()
        .oneshot(Request::get("/_renox/live").body(Body::empty()).unwrap())
        .await
        .unwrap();
    assert_eq!(res.status(), StatusCode::NOT_FOUND);
    let page = kernel
        .router()
        .oneshot(Request::get("/").body(Body::empty()).unwrap())
        .await
        .unwrap();
    let page = String::from_utf8(
        page.into_body()
            .collect()
            .await
            .unwrap()
            .to_bytes()
            .to_vec(),
    )
    .unwrap();
    assert!(!page.contains("renox-live"));
}
