//! M27a: data grids (`renox::grid`): filters, sorting and pages from the
//! query string, the `grid` macro, and preferences per user or session.

use renox::chrono::NaiveDate;
use renox::db::{DateTime, Json, Migration, Scripts};
use renox::grid::{Column, Grid, GridPrefs, GridRequest};
use renox::prelude::*;
use renox::testing::TestApp;

const SCHEMA: Migration = Migration {
    name: "20300101000000_grid_orders",
    up: "",
    down: Some("DROP TABLE grid_orders;"),
    sqlite: Some(Scripts {
        up: "CREATE TABLE grid_orders (id INTEGER PRIMARY KEY AUTOINCREMENT, number TEXT NOT NULL,
                 status TEXT NOT NULL, tags TEXT NOT NULL DEFAULT '[]', total INTEGER NOT NULL,
                 ordered_on TEXT NOT NULL, placed_at TEXT, paid INTEGER NOT NULL DEFAULT 0)",
        down: None,
    }),
    postgres: Some(Scripts {
        up: "CREATE TABLE grid_orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 number TEXT NOT NULL, status TEXT NOT NULL, tags JSONB NOT NULL DEFAULT '[]',
                 total BIGINT NOT NULL, ordered_on DATE NOT NULL, placed_at TIMESTAMPTZ,
                 paid BOOLEAN NOT NULL DEFAULT FALSE)",
        down: None,
    }),
};

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "grid_orders")]
struct GridOrder {
    id: i64,
    number: String,
    status: String,
    tags: Json<Vec<String>>,
    total: i64,
    ordered_on: NaiveDate,
    placed_at: Option<DateTime>,
    paid: bool,
}

fn grid() -> Grid {
    Grid::new("orders")
        .title("Orders")
        .column(Column::text("number", "Order").frozen().mobile())
        .column(
            Column::select("status", "Status", [("new", "New"), ("paid", "Paid")]).under(["State"]),
        )
        .column(Column::bool("paid", "Paid").under(["State"]))
        .column(Column::tags(
            "tags",
            "Tags",
            [("online", "Online"), ("promo", "Promo")],
        ))
        .column(Column::money("total", "Total"))
        .column(Column::date("ordered_on", "Ordered"))
        .column(Column::datetime("placed_at", "Placed").hidden())
        .column(Column::custom("chart", "Chart"))
        .per_page(10)
        .sort_by("-total")
}

struct Orders;

impl Module for Orders {
    fn name(&self) -> &'static str {
        "orders"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get("/orders", index)
            .get("/totals", totals)
            .get("/exports", exports)
    }
}

async fn index(request: GridRequest) -> Result<View> {
    let page = grid()
        .page(GridOrder::query(), &request)
        .await?
        .extend(|order| json!({ "points": [1, order.total % 7, 3] }));
    Ok(view("orders.html", context! { orders => page }))
}

/// M27c: the same grid with its export menu.
async fn exports(request: GridRequest) -> Result<Response> {
    let grid = grid().exports();
    if let Some(file) = grid.export(GridOrder::query(), &request).await? {
        return Ok(file);
    }
    let page = grid.page(GridOrder::query(), &request).await?;
    Ok(view("orders.html", context! { orders => page }).into_response())
}

/// `Grid::filter` for figures over every filtered row.
async fn totals(State(state): State<AppState>, request: GridRequest) -> Result<String> {
    let sum: i64 = grid()
        .filter(GridOrder::query(), &request)
        .sum(&state.db, "total")
        .await?;
    Ok(sum.to_string())
}

async fn app() -> (TestApp, tempfile::TempDir) {
    let views = tempfile::tempdir().unwrap();
    std::fs::write(
        views.path().join("orders.html"),
        r#"{% from "renox/grid.html" import grid %}<!doctype html><title>t</title>
{% call(row, column) grid(orders) %}<i class="chart">{{ sparkline(row.points) }}</i>{% endcall %}"#,
    )
    .unwrap();
    let app = TestApp::with_config(
        App::new()
            .migrations(&[SCHEMA])
            .module(Auth::new())
            .module(Orders),
        |c| c.views_path = views.path().to_path_buf(),
    )
    .await;
    let day = |d: u32| NaiveDate::from_ymd_opt(2026, 3, d).unwrap();
    let rows = [
        ("SO-001", "new", vec!["online"], 5_000, day(1), false),
        ("SO-002", "paid", vec!["promo"], 12_000, day(5), true),
        (
            "SO-003",
            "paid",
            vec!["online", "promo"],
            30_000,
            day(10),
            true,
        ),
        ("SO-104", "new", vec![], 800, day(20), false),
        ("XX-105", "paid", vec!["online"], 45_000, day(31), true),
    ];
    for (number, status, tags, total, ordered_on, paid) in rows {
        GridOrder::create(
            app.db(),
            GridOrder {
                number: number.into(),
                status: status.into(),
                tags: Json(tags.into_iter().map(String::from).collect()),
                total,
                ordered_on,
                placed_at: Some(ordered_on.and_hms_opt(9, 0, 0).unwrap().and_utc()),
                paid,
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    for i in 0..20 {
        GridOrder::create(
            app.db(),
            GridOrder {
                number: format!("ZZ-{i:03}"),
                status: "new".into(),
                total: 100 + i,
                ordered_on: day(28),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    (app, views)
}

/// The order numbers on the page, in order.
fn numbers(html: &str) -> Vec<String> {
    html.split("<td data-col=\"number\"")
        .skip(1)
        .filter_map(|cell| {
            let text = cell.split_once('>')?.1.split_once("</td>")?.0;
            Some(text.trim().to_owned())
        })
        .collect()
}

async fn rows(app: &TestApp, query: &str) -> Vec<String> {
    let res = app.get(&format!("/orders?{query}")).await;
    res.assert_ok();
    numbers(&res.text())
}

#[renox::test]
async fn filters_by_each_kind_of_column() {
    let (app, _views) = app().await;
    assert_eq!(
        rows(&app, "q.number=SO-00").await,
        ["SO-003", "SO-002", "SO-001"]
    );
    assert_eq!(
        rows(&app, "q.number=so-1&m.number=starts").await,
        ["SO-104"]
    );
    assert_eq!(rows(&app, "q.number=105&m.number=ends").await, ["XX-105"]);
    assert_eq!(
        rows(&app, "q.number=SO-%25-&m.number=equals").await,
        Vec::<String>::new()
    );
    assert_eq!(
        rows(&app, "q.number=S_-1%25").await,
        ["SO-104"],
        "a pattern"
    );
    assert_eq!(
        rows(&app, "min.total=10000&max.total=40000").await,
        ["SO-003", "SO-002"]
    );
    assert_eq!(
        rows(&app, "from.ordered_on=2026-03-05&to.ordered_on=2026-03-10").await,
        ["SO-003", "SO-002"]
    );
    assert_eq!(
        rows(&app, "from.placed_at=2026-03-31").await,
        ["XX-105"],
        "a date-time column, whole days"
    );
    assert_eq!(
        rows(&app, "in.status=paid&in.paid=true&q.number=SO").await,
        ["SO-003", "SO-002"]
    );
    assert_eq!(
        rows(&app, "in.paid=false&q.number=SO").await,
        ["SO-001", "SO-104"]
    );
    assert_eq!(
        rows(&app, "in.tags=promo").await,
        ["SO-003", "SO-002"],
        "tags: any of the picked"
    );
    assert_eq!(
        rows(&app, "in.tags=online&in.tags=promo").await,
        ["XX-105", "SO-003", "SO-002", "SO-001"]
    );
    // Unknown columns, custom columns, bad values and unknown choices are
    // ignored rather than errors.
    let all = rows(&app, "").await;
    for query in [
        "q.nope=x",
        "q.chart=x",
        "min.total=lots",
        "from.ordered_on=yesterday",
        "in.status=evil",
        "sort=chart",
        "sort=total;DROP",
        "per_page=7",
    ] {
        assert_eq!(rows(&app, query).await, all, "{query}");
    }
    // Totals over every filtered row, not just a page.
    app.get("/totals?in.status=paid").await.assert_see("87000");
}

#[renox::test]
async fn sorts_and_pages_from_the_server() {
    let (app, _views) = app().await;
    let first = rows(&app, "").await;
    assert_eq!(first.len(), 10, "per_page(10)");
    assert_eq!(first[0], "XX-105", "sort_by(-total)");
    assert_eq!(rows(&app, "sort=total").await[0], "ZZ-000");
    assert_eq!(rows(&app, "sort=-number&per_page=25").await.len(), 25);
    let third = rows(&app, "page=3").await;
    assert_eq!(third.len(), 5);
    assert_eq!(rows(&app, "page=99").await.len(), 0);
    let res = app.get("/orders?q.number=SO&sort=number").await;
    res.assert_see("4 rows")
        .assert_see(r#"aria-sort="ascending""#)
        .assert_see(r#"data-grid-sort="-number""#)
        .assert_see(r#"<option value="25">25</option>"#);
}

#[renox::test]
async fn the_macro_draws_headings_cells_and_controls() {
    let (app, _views) = app().await;
    let res = app.get("/orders?q.number=SO-002").await;
    res.assert_ok()
        .assert_see(r#"<form class="rx-grid" id="grid-orders""#)
        .assert_see(r##"hx-select="#grid-orders""##)
        .assert_see("/_renox/grid-")
        .assert_see("/_renox/cally-")
        // A group spanning two columns; leaves under no group span both rows.
        .assert_see(r#"<th scope="colgroup" colspan="2" class="rx-grid__group" data-cols="status paid">State</th>"#)
        .assert_see(r#"rowspan="2" data-col="number" data-pin="left""#)
        // Cells by kind: money, a label for a choice, tags, yes/no, a date.
        .assert_see("12,000")
        .assert_see(r#"<span class="rx-grid__tag">Promo</span>"#)
        .assert_see(r#"<span class="rx-grid__yes">Yes</span>"#)
        .assert_see("2026-03-05")
        // The custom column, drawn by the page with `extend`ed values.
        .assert_see(r#"<i class="chart"><svg class="rx-spark""#)
        // The active filter is marked and refilled.
        .assert_see("rx-grid__filter rx-grid__filter--on")
        .assert_see(r#"name="q.number" value="SO-002""#)
        .assert_see("1 row · filtered");
    // The grid's assets are served.
    let html = res.text();
    for prefix in ["/_renox/grid-", "/_renox/cally-"] {
        let url = html
            .split(prefix)
            .nth(1)
            .unwrap()
            .split('"')
            .next()
            .unwrap();
        app.get(&format!("{prefix}{url}")).await.assert_ok();
    }
    // Nothing found says so.
    app.get("/orders?q.number=nothing")
        .await
        .assert_see("Nothing matches these filters.");
}

#[renox::test]
async fn guests_keep_their_columns_in_the_session() {
    let (app, _views) = app().await;
    let config = |html: String| -> serde_json::Value {
        let attr = html
            .split("data-rx-grid=\"")
            .nth(1)
            .unwrap()
            .split('"')
            .next()
            .unwrap();
        serde_json::from_str(&attr.replace("&quot;", "\"")).unwrap()
    };
    let before = config(app.get("/orders").await.text());
    assert_eq!(before["compact"], json!(["number"]));
    assert!(
        !before["wide"]
            .as_array()
            .unwrap()
            .contains(&json!("placed_at"))
    );

    let prefs = json!({
        "order": ["total", "number", "status"],
        "left": ["total"],
        "right": [],
        "compact": ["total", "number"],
        "wide": ["total", "number", "status"]
    });
    app.post_json("/_renox/grid/orders/prefs", &prefs)
        .await
        .assert_status(204);
    let html = app.get("/orders").await.text();
    let after = config(html.clone());
    assert_eq!(after["left"], json!(["total"]));
    assert_eq!(after["compact"], json!(["total", "number"]));
    assert_eq!(after["order"][0], "total");
    assert!(html.contains(r#"data-col="total" data-pin="left""#));
    assert!(!html.contains(r#"data-col="number" data-pin"#), "unfrozen");

    // Column widths come back in the config for the script.
    app.post_json(
        "/_renox/grid/orders/prefs",
        &json!({ "order": ["total", "number", "status"], "widths": { "total": 180 } }),
    )
    .await
    .assert_status(204);
    assert_eq!(
        config(app.get("/orders").await.text())["widths"],
        json!({ "total": 180 })
    );
    app.post_json(
        "/_renox/grid/orders/prefs",
        &json!({ "widths": { "total": 5 } }),
    )
    .await
    .assert_status(422);
    assert!(
        app.get("/orders").await.text().contains("data-grid-resize"),
        "every heading has a resize handle"
    );

    // Bad preferences are refused; DELETE goes back to the defaults.
    app.post_json("/_renox/grid/orders/prefs", &json!({ "order": ["x y"] }))
        .await
        .assert_status(422);
    app.delete("/_renox/grid/orders/prefs")
        .await
        .assert_status(204);
    assert_eq!(
        config(app.get("/orders").await.text())["left"],
        json!(["number"])
    );
}

#[renox::test]
async fn users_keep_their_columns_in_the_database() {
    let (app, _views) = app().await;
    let user = User::register(app.db(), "Arif", "arif@example.com", "password123")
        .await
        .unwrap();
    app.acting_as(&user);
    app.post_json(
        "/_renox/grid/orders/prefs",
        &json!({ "compact": ["status"], "left": [] }),
    )
    .await
    .assert_status(204);
    app.assert_database_has("grid_preferences", &[("grid", &"orders")])
        .await;
    app.assert_database_count("grid_preferences", 1).await;
    // Saving again replaces the row.
    let prefs = GridPrefs::default();
    renox::grid::save_prefs(app.db(), user.id, "orders", &prefs)
        .await
        .unwrap();
    app.assert_database_count("grid_preferences", 1).await;
    app.post_json("/_renox/grid/orders/prefs", &json!({ "left": [] }))
        .await
        .assert_status(204);
    let html = app.get("/orders").await.text();
    assert!(!html.contains("data-pin=\"left\""));
    app.delete("/_renox/grid/orders/prefs")
        .await
        .assert_status(204);
    app.assert_database_count("grid_preferences", 0).await;
}

#[renox::test]
async fn grid_requests_work_outside_handlers() {
    let (app, _views) = app().await;
    let request = GridRequest::new(
        app.db(),
        "/orders",
        &[("in.status", "paid"), ("sort", "number")],
    );
    assert_eq!(request.param("sort"), Some("number"));
    let page = grid().page(GridOrder::query(), &request).await.unwrap();
    assert_eq!(page.total(), 3);
    let numbers: Vec<&str> = page.items().iter().map(|o| o.number.as_str()).collect();
    assert_eq!(numbers, ["SO-002", "SO-003", "XX-105"]);
    // A bad grid id is the app's mistake.
    assert!(
        Grid::new("bad id")
            .page(GridOrder::query(), &request)
            .await
            .is_err()
    );
}

// ---------- M27b: details, editing, row order, merged cells ----------

const TASKS: Migration = Migration {
    name: "20300101000001_grid_tasks",
    up: "",
    down: Some("DROP TABLE grid_tasks;"),
    sqlite: Some(Scripts {
        up: "CREATE TABLE grid_tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, region TEXT NOT NULL,
                 city TEXT NOT NULL, title TEXT NOT NULL, position INTEGER NOT NULL DEFAULT 0,
                 created_by TEXT NOT NULL DEFAULT '', updated_by TEXT NOT NULL DEFAULT '',
                 created_at TEXT, updated_at TEXT)",
        down: None,
    }),
    postgres: Some(Scripts {
        up: "CREATE TABLE grid_tasks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 region TEXT NOT NULL, city TEXT NOT NULL, title TEXT NOT NULL,
                 position BIGINT NOT NULL DEFAULT 0, created_by TEXT NOT NULL DEFAULT '',
                 updated_by TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ)",
        down: None,
    }),
};

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "grid_tasks")]
struct GridTask {
    id: i64,
    region: String,
    city: String,
    title: String,
    position: i64,
    created_by: String,
    updated_by: String,
    created_at: Option<DateTime>,
    updated_at: Option<DateTime>,
}

fn tasks_grid() -> Grid {
    Grid::new("tasks")
        .column(Column::text("region", "Region").merge())
        .column(Column::text("city", "City").merge())
        .column(Column::text("title", "Title").editable())
        .column(Column::number("position", "#"))
        .sort_by("region,city,title")
        .audit()
        .details()
        .edit_url("/tasks/{id}")
        .reorder("position", "/tasks/order")
}

struct Tasks;

impl Module for Tasks {
    fn name(&self) -> &'static str {
        "tasks"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get("/tasks", |request: GridRequest| async move {
                let page = tasks_grid().page(GridTask::query(), &request).await?;
                Ok::<_, Error>(view("tasks.html", context! { tasks => page }))
            })
            .post(
                "/tasks/order",
                |State(db): State<Db>, Form(order): Form<renox::grid::RowOrder>| async move {
                    order.save::<GridTask>(&db, "position").await?;
                    Ok::<_, Error>(StatusCode::NO_CONTENT)
                },
            )
    }
}

async fn tasks_app() -> (TestApp, tempfile::TempDir) {
    let views = tempfile::tempdir().unwrap();
    std::fs::write(
        views.path().join("tasks.html"),
        r#"{% from "renox/grid.html" import grid %}
{% call(row, column) grid(tasks) %}{% if column.key == "_details" %}<b class="more">{{ row.title }} more</b>{% endif %}{% endcall %}"#,
    )
    .unwrap();
    let app = TestApp::with_config(App::new().migrations(&[TASKS]).module(Tasks), |c| {
        c.views_path = views.path().to_path_buf()
    })
    .await;
    let rows = [
        ("Java", "Bandung", "a"),
        ("Java", "Bandung", "b"),
        ("Java", "Jakarta", "c"),
        ("Bali", "Denpasar", "d"),
    ];
    for (i, (region, city, title)) in rows.into_iter().enumerate() {
        GridTask::create(
            app.db(),
            GridTask {
                region: region.into(),
                city: city.into(),
                title: title.into(),
                position: i as i64 + 10,
                created_by: "Arif".into(),
                updated_by: "Dewi".into(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    (app, views)
}

#[renox::test]
async fn equal_neighbours_share_a_merged_cell() {
    let (app, _views) = tasks_app().await;
    let html = app.get("/tasks").await.text();
    // Sorted region, city, title (the default's several keys): Bali first.
    let order: Vec<&str> = html
        .split("<td data-col=\"title\"")
        .skip(1)
        .filter_map(|c| {
            c.split_once("</td>")
                .map(|(c, _)| c.rsplit('>').next().unwrap().trim())
        })
        .collect();
    assert_eq!(order, ["d", "a", "b", "c"]);
    assert!(
        html.contains(r#"data-col="region" rowspan="3" data-group="region-1""#),
        "{html}"
    );
    assert!(html.contains(r#"data-col="city" rowspan="2" data-group="city-1""#));
    assert!(html.contains(r#"data-covered="region city""#));
    assert!(html.contains(r#"data-covered="region""#));
    assert_eq!(
        html.matches("<td data-col=\"region\"").count(),
        2,
        "Bali and Java"
    );
    assert_eq!(html.matches("<td data-col=\"city\"").count(), 3);
    // A user's own sort keeps merging, by the merged columns' values.
    let by_title = app.get("/tasks?sort=title").await.text();
    assert_eq!(
        by_title.matches("<td data-col=\"region\"").count(),
        2,
        "a, b, c, d: Java×3 then Bali"
    );
}

#[renox::test]
async fn rows_open_their_audit_and_details() {
    let (app, _views) = tasks_app().await;
    let res = app.get("/tasks").await;
    res.assert_see("<template data-grid-details>")
        .assert_see("<dt>Created</dt><dd>Arif")
        .assert_see("<dt>Last updated</dt><dd>Dewi")
        .assert_see(r#"<b class="more">d more</b>"#)
        .assert_see(r#"data-grid-expand aria-expanded="false""#)
        .assert_see("data-grid-row");
}

#[renox::test]
async fn editable_cells_carry_their_values() {
    let (app, _views) = tasks_app().await;
    let res = app.get("/tasks").await;
    let id = GridTask::where_eq("title", "a")
        .first(app.db())
        .await
        .unwrap()
        .unwrap()
        .id;
    res.assert_see(&format!(r#"data-edit="/tasks/{id}""#))
        .assert_see(r#"data-editable tabindex="0" data-raw='"a"'"#)
        .assert_see("data-grid-edit-row")
        .assert_dont_see(r#"data-col="region" data-editable"#);
}

#[renox::test]
async fn rows_reorder_while_sorted_by_their_position() {
    let (app, _views) = tasks_app().await;
    // Not sorted by position: the handle is off and cells merge.
    let html = app.get("/tasks").await.text();
    assert!(html.contains("data-grid-drag disabled"));
    // Sorted by it: dragging on, merging off.
    let html = app.get("/tasks?sort=position").await.text();
    assert!(!html.contains("data-grid-drag disabled"));
    assert!(!html.contains("rowspan=\"3\" data-group"));
    assert!(html.contains("&quot;reorder&quot;:&quot;/tasks/order&quot;"));

    let ids: Vec<i64> = GridTask::query()
        .order_by("position")
        .get(app.db())
        .await
        .unwrap()
        .iter()
        .map(|t| t.id)
        .collect();
    let reversed: Vec<String> = ids.iter().rev().map(i64::to_string).collect();
    app.post(
        "/tasks/order",
        &[("ids", reversed.join(",").as_str()), ("offset", "100")],
    )
    .await
    .assert_status(204);
    let titles: Vec<String> = GridTask::query()
        .order_by("position")
        .get(app.db())
        .await
        .unwrap()
        .into_iter()
        .map(|t| format!("{}:{}", t.title, t.position))
        .collect();
    assert_eq!(titles, ["d:100", "c:101", "b:102", "a:103"]);
    // Ids that aren't ids are refused, and nothing changes.
    app.post("/tasks/order", &[("ids", "1,x"), ("offset", "0")])
        .await
        .assert_status(400);
}

#[renox::test]
async fn row_order_checks_its_column() {
    let (app, _views) = tasks_app().await;
    let order: renox::grid::RowOrder =
        serde_json::from_value(json!({ "ids": "1,2", "offset": 5 })).unwrap();
    assert_eq!(order.ids, ["1", "2"]);
    assert!(order.save::<GridTask>(app.db(), "nope").await.is_err());
    assert!(order.save::<GridTask>(app.db(), "id").await.is_err());
    assert_eq!(
        order.save::<GridTask>(app.db(), "position").await.unwrap(),
        2
    );
}

// ---------- M27c: exports ----------

#[renox::test]
async fn exports_hold_every_filtered_row() {
    let (app, _views) = app().await;
    GridOrder::create(
        app.db(),
        GridOrder {
            number: "=HYPERLINK(\"x\")".into(),
            status: "paid".into(),
            tags: Json(vec!["online".into(), "promo".into()]),
            total: 7,
            ordered_on: NaiveDate::from_ymd_opt(2026, 4, 1).unwrap(),
            paid: true,
            ..Default::default()
        },
    )
    .await
    .unwrap();
    // The menu links keep the filters.
    let page = app.get("/exports?in.status=paid").await;
    page.assert_see("in.status=paid&amp;export=csv")
        .assert_see("in.status=paid&amp;export=print");
    assert_eq!(
        page.text().contains("export=xlsx"),
        cfg!(feature = "xlsx"),
        "Excel only with the feature"
    );

    let csv = app.get("/exports?in.status=paid&export=csv").await;
    csv.assert_ok()
        .assert_header("content-type", "text/csv; charset=utf-8");
    let text = csv.text();
    let lines: Vec<&str> = text.trim_start_matches('\u{feff}').lines().collect();
    // Paid rows on all pages (per_page is 10), placed_at hidden, the custom
    // chart left out; groups in the headings.
    assert_eq!(
        lines[0],
        "Order,State / Status,State / Paid,Tags,Total,Ordered"
    );
    assert_eq!(lines.len(), 1 + 4);
    assert!(
        lines.contains(&"XX-105,Paid,Yes,Online,45000,2026-03-31"),
        "{text}"
    );
    // Labels joined and quoted; a formula is made text.
    assert!(
        lines.contains(&"\"'=HYPERLINK(\"\"x\"\")\",Paid,Yes,\"Online, Promo\",7,2026-04-01"),
        "{text}"
    );

    let print = app.get("/exports?in.status=paid&export=print").await;
    print
        .assert_ok()
        .assert_see("<title>Orders</title>")
        .assert_see(">State</th>")
        .assert_see(r#"<td class="num">45,000</td>"#)
        .assert_see("4 rows")
        .assert_see("data-grid-print");

    let xlsx = app.get("/exports?export=xlsx").await;
    if cfg!(feature = "xlsx") {
        xlsx.assert_ok().assert_header(
            "content-type",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        );
        assert!(xlsx.body.starts_with(b"PK"), "a zip");
    } else {
        xlsx.assert_status(400);
    }
    app.get("/exports?export=docx").await.assert_status(400);
    // Without `export`, the page.
    app.get("/exports").await.assert_see("rx-grid");
}

// ---------- M28a: prefixes, search, chips, row links, empty state ----------

fn search_grid(prefix: Option<&str>) -> Grid {
    let grid = Grid::new("orders")
        .column(Column::text("number", "Order").searchable())
        .column(Column::select("status", "Status", [("new", "New"), ("paid", "Paid")]).searchable())
        .column(Column::money("total", "Total"))
        .sort_by("number")
        .row_url("/orders/{id}")
        .empty_state("No orders yet", Some("They show up here."));
    match prefix {
        Some(p) => grid.prefix(p),
        None => grid,
    }
}

struct Searching;

impl Module for Searching {
    fn name(&self) -> &'static str {
        "searching"
    }

    fn routes(&self) -> Routes {
        Routes::new()
            .get("/search", |request: GridRequest| async move {
                let page = search_grid(None).page(GridOrder::query(), &request).await?;
                Ok::<_, Error>(view("orders.html", context! { orders => page }))
            })
            .get("/two", |request: GridRequest| async move {
                let a = search_grid(Some("a"))
                    .page(GridOrder::query(), &request)
                    .await?;
                let b = Grid::new("others")
                    .prefix("b")
                    .column(Column::text("number", "Order"))
                    .page(GridOrder::query(), &request)
                    .await?;
                Ok::<_, Error>(view("two.html", context! { a, b }))
            })
            .get("/none", |request: GridRequest| async move {
                let page = search_grid(None)
                    .page(GridOrder::where_eq("number", "nothing"), &request)
                    .await?;
                Ok::<_, Error>(view("orders.html", context! { orders => page }))
            })
    }
}

async fn search_app() -> (TestApp, tempfile::TempDir) {
    let (_, views) = app().await; // for its views
    std::fs::write(
        views.path().join("two.html"),
        r#"{% from "renox/grid.html" import grid %}{{ grid(a) }}{{ grid(b) }}"#,
    )
    .unwrap();
    let app = TestApp::with_config(App::new().migrations(&[SCHEMA]).module(Searching), |c| {
        c.views_path = views.path().to_path_buf()
    })
    .await;
    for (number, status, total) in [
        ("SO-001", "new", 5),
        ("SO-002", "paid", 7),
        ("XX-003", "paid", 9),
    ] {
        GridOrder::create(
            app.db(),
            GridOrder {
                number: number.into(),
                status: status.into(),
                total,
                ordered_on: NaiveDate::from_ymd_opt(2026, 1, 1).unwrap(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    (app, views)
}

#[renox::test]
async fn the_search_box_looks_in_searchable_columns() {
    let (app, _views) = search_app().await;
    let found = |q: &'static str| {
        let app = &app;
        async move { numbers(&app.get(&format!("/search?{q}")).await.text()) }
    };
    assert_eq!(found("search=so-").await, ["SO-001", "SO-002"], "any case");
    assert_eq!(
        found("search=paid").await,
        ["SO-002", "XX-003"],
        "the status column"
    );
    assert_eq!(found("search=so+paid").await, ["SO-002"], "every word");
    assert_eq!(found("search=%25").await.len(), 3, "% is LIKE's wildcard");
    let res = app.get("/search?search=paid&in.status=paid").await;
    res.assert_see(r#"name="search" value="paid""#)
        .assert_see("data-grid-clear-search")
        .assert_see("Search: “paid”")
        .assert_see("Status: Paid");
}

#[renox::test]
async fn rows_link_and_empty_grids_say_why() {
    let (app, _views) = search_app().await;
    let id = GridOrder::where_eq("number", "SO-001")
        .first(app.db())
        .await
        .unwrap()
        .unwrap()
        .id;
    app.get("/search")
        .await
        .assert_see(&format!(r#"data-href="/orders/{id}" tabindex="0""#));
    app.get("/none")
        .await
        .assert_see("No orders yet")
        .assert_see("They show up here.");
    app.get("/search?search=zzz")
        .await
        .assert_see("Nothing matches these filters.")
        .assert_dont_see("No orders yet");
}

#[renox::test]
async fn two_grids_on_a_page_keep_their_own_values() {
    let (app, _views) = search_app().await;
    let html = app
        .get("/two?a.search=SO-002&b.sort=-number&tab=2")
        .await
        .text();
    let (first, second) = html.split_once("id=\"grid-others\"").unwrap();
    assert_eq!(numbers(first), ["SO-002"]);
    assert_eq!(numbers(second), ["XX-003", "SO-002", "SO-001"]);
    // Each keeps the other's values and the page's own.
    assert!(first.contains(r#"<input type="hidden" name="b.sort" value="-number">"#));
    assert!(first.contains(r#"<input type="hidden" name="tab" value="2">"#));
    assert!(second.contains(r#"<input type="hidden" name="a.search" value="SO-002">"#));
    assert!(first.contains(r#"name="a.page""#) && second.contains(r#"name="b.page""#));
}

// ---------- M28b: selection, bulk and row actions ----------

fn action_grid() -> Grid {
    use renox::grid::Action;
    Grid::new("orders")
        .column(Column::text("number", "Order"))
        .column(Column::select(
            "status",
            "Status",
            [("new", "New"), ("paid", "Paid")],
        ))
        .sort_by("number")
        .bulk_action(Action::new("Mark paid", "/bulk/paid"))
        .bulk_action(
            Action::new("Delete", "/bulk/delete")
                .confirm("Sure?")
                .danger(),
        )
        .row_action(Action::link("Open", "/orders/{id}"))
        .row_action(
            Action::new("Remove", "/orders/{id}")
                .method("delete")
                .confirm("Remove it?"),
        )
}

struct Acting;

impl Module for Acting {
    fn name(&self) -> &'static str {
        "acting"
    }

    fn routes(&self) -> Routes {
        use renox::grid::Selection;
        Routes::new()
            .get("/acts", |request: GridRequest| async move {
                let page = action_grid().page(GridOrder::query(), &request).await?;
                Ok::<_, Error>(view("orders.html", context! { orders => page }))
            })
            .post(
                "/bulk/paid",
                |State(db): State<Db>, request: GridRequest, Form(selection): Form<Selection>| async move {
                    let n = action_grid()
                        .selected(GridOrder::query(), &request, &selection)?
                        .update(&db, &[("status", &"paid")])
                        .await?;
                    Ok::<_, Error>(n.to_string())
                },
            )
    }
}

#[renox::test]
async fn bulk_actions_take_the_selection_or_all_matching() {
    let (_, views) = app().await; // for its views
    let app = TestApp::with_config(App::new().migrations(&[SCHEMA]).module(Acting), |c| {
        c.views_path = views.path().to_path_buf()
    })
    .await;
    let mut ids = Vec::new();
    for (number, status) in [("A1", "new"), ("A2", "new"), ("B1", "new"), ("B2", "paid")] {
        let order = GridOrder::create(
            app.db(),
            GridOrder {
                number: number.into(),
                status: status.into(),
                ordered_on: NaiveDate::from_ymd_opt(2026, 1, 1).unwrap(),
                ..Default::default()
            },
        )
        .await
        .unwrap();
        ids.push(order.id);
    }
    let html = app.get("/acts").await.text();
    assert!(html.contains("data-grid-select-all"));
    assert!(html.contains(&format!(r#"data-grid-select value="{}""#, ids[0])));
    assert!(html.contains(
        r#"data-url="/bulk/delete" data-method="POST" data-confirm="Sure?" data-danger"#
    ));
    assert!(html.contains(&format!(r#"href="/orders/{}">Open</a>"#, ids[0])));
    assert!(html.contains(&format!(
        r#"data-url="/orders/{}" data-method="DELETE" data-confirm="Remove it?""#,
        ids[0]
    )));
    assert!(html.contains("<dialog class=\"rx-grid__dialog\""));

    // The selected ids only.
    let picked = format!("{},{}", ids[0], ids[2]);
    app.post("/bulk/paid", &[("ids", picked.as_str()), ("all", "false")])
        .await
        .assert_see("2");
    // Every row the grid's filters (in the query string) match.
    app.post("/bulk/paid?q.number=A", &[("ids", ""), ("all", "true")])
        .await
        .assert_see("2");
    let paid = GridOrder::where_eq("status", "paid")
        .count(app.db())
        .await
        .unwrap();
    assert_eq!(paid, 4);
    app.post("/bulk/paid", &[("ids", "x"), ("all", "false")])
        .await
        .assert_status(400);
}
