//! M27a: data grids (`renox::grid`): filters, sorting and pages from the
//! query string, the `grid` macro, and preferences per user or session.

use renox::chrono::NaiveDate;
use renox::db::{DateTime, Json, Migration, Scripts};
use renox::grid::{Column, Grid, GridPrefs, GridRequest};
use renox::prelude::*;
use renox::testing::TestApp;

const SCHEMA: Migration = Migration {
    name: "20300101000000_grid_orders",
    up: "",
    down: Some("DROP TABLE grid_orders;"),
    sqlite: Some(Scripts {
        up: "CREATE TABLE grid_orders (id INTEGER PRIMARY KEY AUTOINCREMENT, number TEXT NOT NULL,
                 status TEXT NOT NULL, tags TEXT NOT NULL DEFAULT '[]', total INTEGER NOT NULL,
                 ordered_on TEXT NOT NULL, placed_at TEXT, paid INTEGER NOT NULL DEFAULT 0)",
        down: None,
    }),
    postgres: Some(Scripts {
        up: "CREATE TABLE grid_orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 number TEXT NOT NULL, status TEXT NOT NULL, tags JSONB NOT NULL DEFAULT '[]',
                 total BIGINT NOT NULL, ordered_on DATE NOT NULL, placed_at TIMESTAMPTZ,
                 paid BOOLEAN NOT NULL DEFAULT FALSE)",
        down: None,
    }),
};

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "grid_orders")]
struct GridOrder {
    id: i64,
    number: String,
    status: String,
    tags: Json<Vec<String>>,
    total: i64,
    ordered_on: NaiveDate,
    placed_at: Option<DateTime>,
    paid: bool,
}

fn grid() -> Grid {
    Grid::new("orders")
        .title("Orders")
        .column(Column::text("number", "Order").frozen().mobile())
        .column(
            Column::select("status", "Status", [("new", "New"), ("paid", "Paid")]).under(["State"]),
        )
        .column(Column::bool("paid", "Paid").under(["State"]))
        .column(Column::tags(
            "tags",
            "Tags",
            [("online", "Online"), ("promo", "Promo")],
        ))
        .column(Column::money("total", "Total"))
        .column(Column::date("ordered_on", "Ordered"))
        .column(Column::datetime("placed_at", "Placed").hidden())
        .column(Column::custom("chart", "Chart"))
        .per_page(10)
        .sort_by("-total")
}

struct Orders;

impl Module for Orders {
    fn name(&self) -> &'static str {
        "orders"
    }

    fn routes(&self) -> Routes {
        Routes::new().get("/orders", index).get("/totals", totals)
    }
}

async fn index(request: GridRequest) -> Result<View> {
    let page = grid()
        .page(GridOrder::query(), &request)
        .await?
        .extend(|order| json!({ "points": [1, order.total % 7, 3] }));
    Ok(view("orders.html", context! { orders => page }))
}

/// `Grid::filter` for figures over every filtered row.
async fn totals(State(state): State<AppState>, request: GridRequest) -> Result<String> {
    let sum: i64 = grid()
        .filter(GridOrder::query(), &request)
        .sum(&state.db, "total")
        .await?;
    Ok(sum.to_string())
}

async fn app() -> (TestApp, tempfile::TempDir) {
    let views = tempfile::tempdir().unwrap();
    std::fs::write(
        views.path().join("orders.html"),
        r#"{% from "renox/grid.html" import grid %}<!doctype html><title>t</title>
{% call(row, column) grid(orders) %}<i class="chart">{{ sparkline(row.points) }}</i>{% endcall %}"#,
    )
    .unwrap();
    let app = TestApp::with_config(
        App::new()
            .migrations(&[SCHEMA])
            .module(Auth::new())
            .module(Orders),
        |c| c.views_path = views.path().to_path_buf(),
    )
    .await;
    let day = |d: u32| NaiveDate::from_ymd_opt(2026, 3, d).unwrap();
    let rows = [
        ("SO-001", "new", vec!["online"], 5_000, day(1), false),
        ("SO-002", "paid", vec!["promo"], 12_000, day(5), true),
        (
            "SO-003",
            "paid",
            vec!["online", "promo"],
            30_000,
            day(10),
            true,
        ),
        ("SO-104", "new", vec![], 800, day(20), false),
        ("XX-105", "paid", vec!["online"], 45_000, day(31), true),
    ];
    for (number, status, tags, total, ordered_on, paid) in rows {
        GridOrder::create(
            app.db(),
            GridOrder {
                number: number.into(),
                status: status.into(),
                tags: Json(tags.into_iter().map(String::from).collect()),
                total,
                ordered_on,
                placed_at: Some(ordered_on.and_hms_opt(9, 0, 0).unwrap().and_utc()),
                paid,
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    for i in 0..20 {
        GridOrder::create(
            app.db(),
            GridOrder {
                number: format!("ZZ-{i:03}"),
                status: "new".into(),
                total: 100 + i,
                ordered_on: day(28),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    (app, views)
}

/// The order numbers on the page, in order.
fn numbers(html: &str) -> Vec<String> {
    html.split("<td data-col=\"number\"")
        .skip(1)
        .filter_map(|cell| {
            let text = cell.split_once('>')?.1.split_once("</td>")?.0;
            Some(text.trim().to_owned())
        })
        .collect()
}

async fn rows(app: &TestApp, query: &str) -> Vec<String> {
    let res = app.get(&format!("/orders?{query}")).await;
    res.assert_ok();
    numbers(&res.text())
}

#[renox::test]
async fn filters_by_each_kind_of_column() {
    let (app, _views) = app().await;
    assert_eq!(
        rows(&app, "q.number=SO-00").await,
        ["SO-003", "SO-002", "SO-001"]
    );
    assert_eq!(
        rows(&app, "q.number=so-1&m.number=starts").await,
        ["SO-104"]
    );
    assert_eq!(rows(&app, "q.number=105&m.number=ends").await, ["XX-105"]);
    assert_eq!(
        rows(&app, "q.number=SO-%25-&m.number=equals").await,
        Vec::<String>::new()
    );
    assert_eq!(
        rows(&app, "q.number=S_-1%25").await,
        ["SO-104"],
        "a pattern"
    );
    assert_eq!(
        rows(&app, "min.total=10000&max.total=40000").await,
        ["SO-003", "SO-002"]
    );
    assert_eq!(
        rows(&app, "from.ordered_on=2026-03-05&to.ordered_on=2026-03-10").await,
        ["SO-003", "SO-002"]
    );
    assert_eq!(
        rows(&app, "from.placed_at=2026-03-31").await,
        ["XX-105"],
        "a date-time column, whole days"
    );
    assert_eq!(
        rows(&app, "in.status=paid&in.paid=true&q.number=SO").await,
        ["SO-003", "SO-002"]
    );
    assert_eq!(
        rows(&app, "in.paid=false&q.number=SO").await,
        ["SO-001", "SO-104"]
    );
    assert_eq!(
        rows(&app, "in.tags=promo").await,
        ["SO-003", "SO-002"],
        "tags: any of the picked"
    );
    assert_eq!(
        rows(&app, "in.tags=online&in.tags=promo").await,
        ["XX-105", "SO-003", "SO-002", "SO-001"]
    );
    // Unknown columns, custom columns, bad values and unknown choices are
    // ignored rather than errors.
    let all = rows(&app, "").await;
    for query in [
        "q.nope=x",
        "q.chart=x",
        "min.total=lots",
        "from.ordered_on=yesterday",
        "in.status=evil",
        "sort=chart",
        "sort=total;DROP",
        "per_page=7",
    ] {
        assert_eq!(rows(&app, query).await, all, "{query}");
    }
    // Totals over every filtered row, not just a page.
    app.get("/totals?in.status=paid").await.assert_see("87000");
}

#[renox::test]
async fn sorts_and_pages_from_the_server() {
    let (app, _views) = app().await;
    let first = rows(&app, "").await;
    assert_eq!(first.len(), 10, "per_page(10)");
    assert_eq!(first[0], "XX-105", "sort_by(-total)");
    assert_eq!(rows(&app, "sort=total").await[0], "ZZ-000");
    assert_eq!(rows(&app, "sort=-number&per_page=25").await.len(), 25);
    let third = rows(&app, "page=3").await;
    assert_eq!(third.len(), 5);
    assert_eq!(rows(&app, "page=99").await.len(), 0);
    let res = app.get("/orders?q.number=SO&sort=number").await;
    res.assert_see("4 rows")
        .assert_see(r#"aria-sort="ascending""#)
        .assert_see(r#"data-grid-sort="-number""#)
        .assert_see(r#"<option value="25">25</option>"#);
}

#[renox::test]
async fn the_macro_draws_headings_cells_and_controls() {
    let (app, _views) = app().await;
    let res = app.get("/orders?q.number=SO-002").await;
    res.assert_ok()
        .assert_see(r#"<form class="rx-grid" id="grid-orders""#)
        .assert_see(r##"hx-select="#grid-orders""##)
        .assert_see("/_renox/grid-")
        .assert_see("/_renox/cally-")
        // A group spanning two columns; leaves under no group span both rows.
        .assert_see(r#"<th scope="colgroup" colspan="2" class="rx-grid__group" data-cols="status paid">State</th>"#)
        .assert_see(r#"rowspan="2" data-col="number" data-pin="left""#)
        // Cells by kind: money, a label for a choice, tags, yes/no, a date.
        .assert_see("12,000")
        .assert_see(r#"<span class="rx-grid__tag">Promo</span>"#)
        .assert_see(r#"<span class="rx-grid__yes">Yes</span>"#)
        .assert_see("2026-03-05")
        // The custom column, drawn by the page with `extend`ed values.
        .assert_see(r#"<i class="chart"><svg class="rx-spark""#)
        // The active filter is marked and refilled.
        .assert_see("rx-grid__filter rx-grid__filter--on")
        .assert_see(r#"name="q.number" value="SO-002""#)
        .assert_see("1 row · filtered");
    // The grid's assets are served.
    let html = res.text();
    for prefix in ["/_renox/grid-", "/_renox/cally-"] {
        let url = html
            .split(prefix)
            .nth(1)
            .unwrap()
            .split('"')
            .next()
            .unwrap();
        app.get(&format!("{prefix}{url}")).await.assert_ok();
    }
    // Nothing found says so.
    app.get("/orders?q.number=nothing")
        .await
        .assert_see("Nothing matches these filters.");
}

#[renox::test]
async fn guests_keep_their_columns_in_the_session() {
    let (app, _views) = app().await;
    let config = |html: String| -> serde_json::Value {
        let attr = html
            .split("data-rx-grid=\"")
            .nth(1)
            .unwrap()
            .split('"')
            .next()
            .unwrap();
        serde_json::from_str(&attr.replace("&quot;", "\"")).unwrap()
    };
    let before = config(app.get("/orders").await.text());
    assert_eq!(before["compact"], json!(["number"]));
    assert!(
        !before["wide"]
            .as_array()
            .unwrap()
            .contains(&json!("placed_at"))
    );

    let prefs = json!({
        "order": ["total", "number", "status"],
        "left": ["total"],
        "right": [],
        "compact": ["total", "number"],
        "wide": ["total", "number", "status"]
    });
    app.post_json("/_renox/grid/orders/prefs", &prefs)
        .await
        .assert_status(204);
    let html = app.get("/orders").await.text();
    let after = config(html.clone());
    assert_eq!(after["left"], json!(["total"]));
    assert_eq!(after["compact"], json!(["total", "number"]));
    assert_eq!(after["order"][0], "total");
    assert!(html.contains(r#"data-col="total" data-pin="left""#));
    assert!(!html.contains(r#"data-col="number" data-pin"#), "unfrozen");

    // Bad preferences are refused; DELETE goes back to the defaults.
    app.post_json("/_renox/grid/orders/prefs", &json!({ "order": ["x y"] }))
        .await
        .assert_status(422);
    app.delete("/_renox/grid/orders/prefs")
        .await
        .assert_status(204);
    assert_eq!(
        config(app.get("/orders").await.text())["left"],
        json!(["number"])
    );
}

#[renox::test]
async fn users_keep_their_columns_in_the_database() {
    let (app, _views) = app().await;
    let user = User::register(app.db(), "Arif", "arif@example.com", "password123")
        .await
        .unwrap();
    app.acting_as(&user);
    app.post_json(
        "/_renox/grid/orders/prefs",
        &json!({ "compact": ["status"], "left": [] }),
    )
    .await
    .assert_status(204);
    app.assert_database_has("grid_preferences", &[("grid", &"orders")])
        .await;
    app.assert_database_count("grid_preferences", 1).await;
    // Saving again replaces the row.
    let prefs = GridPrefs::default();
    renox::grid::save_prefs(app.db(), user.id, "orders", &prefs)
        .await
        .unwrap();
    app.assert_database_count("grid_preferences", 1).await;
    app.post_json("/_renox/grid/orders/prefs", &json!({ "left": [] }))
        .await
        .assert_status(204);
    let html = app.get("/orders").await.text();
    assert!(!html.contains("data-pin=\"left\""));
    app.delete("/_renox/grid/orders/prefs")
        .await
        .assert_status(204);
    app.assert_database_count("grid_preferences", 0).await;
}

#[renox::test]
async fn grid_requests_work_outside_handlers() {
    let (app, _views) = app().await;
    let request = GridRequest::new(
        app.db(),
        "/orders",
        &[("in.status", "paid"), ("sort", "number")],
    );
    assert_eq!(request.param("sort"), Some("number"));
    let page = grid().page(GridOrder::query(), &request).await.unwrap();
    assert_eq!(page.total(), 3);
    let numbers: Vec<&str> = page.items().iter().map(|o| o.number.as_str()).collect();
    assert_eq!(numbers, ["SO-002", "SO-003", "XX-105"]);
    // A bad grid id is the app's mistake.
    assert!(
        Grid::new("bad id")
            .page(GridOrder::query(), &request)
            .await
            .is_err()
    );
}
