//! #255: data grid paths the other grid tests don't reach: the advanced
//! filter's negative operators on bool, option and text columns with NULL
//! rows, rules and filters the request parser drops, related values for
//! string ids and fractions, groups by a yes/no or a number column, a
//! summary on a column that isn't the model's, a column pinned right, a
//! descending sort on a `SELECT *` model's extra column, `GridRequest`
//! without Renox's middleware, and CSV/Excel exports read back. On SQLite
//! and, with `TEST_DATABASE_URL`, PostgreSQL.

use std::io::Read;

use renox::chrono::NaiveDate;
use renox::db::{DateTime, Dialect, Json, Migration, Ulid};
use renox::grid::{Column, Grid, GridRequest, Summary};
use renox::prelude::*;
use renox::testing::TestApp;
use serde_json::{Value, json};

const GADGETS: Migration = Migration::new(
    "20300101000050_grid_gadgets",
    "",
    Some("DROP TABLE grid_gadgets; DROP TABLE grid_makers;"),
)
.sqlite(
    "CREATE TABLE grid_makers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, rating REAL);
     CREATE TABLE grid_gadgets (id TEXT PRIMARY KEY, maker_id INTEGER, name TEXT NOT NULL,
         active BOOLEAN, kind TEXT, note TEXT, price REAL NOT NULL, cost INTEGER NOT NULL,
         made_on TEXT, made_at TEXT, code TEXT NOT NULL, meta TEXT)",
    None,
)
.postgres(
    "CREATE TABLE grid_makers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         name TEXT NOT NULL, rating DOUBLE PRECISION);
     CREATE TABLE grid_gadgets (id TEXT PRIMARY KEY, maker_id BIGINT, name TEXT NOT NULL,
         active BOOLEAN, kind TEXT, note TEXT, price DOUBLE PRECISION NOT NULL, cost BIGINT NOT NULL,
         made_on DATE, made_at TIMESTAMPTZ, code TEXT NOT NULL, meta JSONB)",
    None,
);

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "grid_makers")]
struct GridMaker {
    id: i64,
    name: String,
    rating: Option<f64>,
}

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "grid_gadgets")]
struct Gadget {
    id: Ulid,
    maker_id: Option<i64>,
    name: String,
    active: Option<bool>,
    kind: Option<String>,
    note: Option<String>,
    price: f64,
    cost: i64,
    made_on: Option<NaiveDate>,
    made_at: Option<DateTime>,
    code: String,
    meta: Option<Json<Value>>,
}

fn gadgets_grid() -> Grid {
    Grid::new("gadgets")
        .column(Column::text("name", "Name").filterable(false))
        .column(
            Column::related("maker", "Maker", "grid_makers", "maker_id", "name")
                .summary(Summary::Count),
        )
        .column(Column::related("rating", "Rating", "grid_makers", "maker_id", "rating").numeric())
        .column(Column::bool("active", "Active"))
        .column(Column::select(
            "kind",
            "Kind",
            [("a", "Kind A"), ("b", "Kind B")],
        ))
        .column(Column::text("note", "Note"))
        .column(Column::number("price", "Price").decimals(2))
        .column(Column::money("cost", "Cost"))
        .column(Column::date("made_on", "Made on"))
        .column(Column::datetime("made_at", "Made at"))
        .column(Column::text("code", "Code"))
        .column(Column::text("meta", "Meta"))
        .column(Column::image("photo", "Photo"))
        .column(Column::custom("extra", "Extra").filterable(true))
        .sort_by("name")
        .groups(&["active", "price"])
        .advanced_filter()
        .exports()
}

async fn gadgets(request: GridRequest) -> Result<Response> {
    if let Some(file) = gadgets_grid().export(Gadget::query(), &request).await? {
        return Ok(file);
    }
    let page = gadgets_grid().page(Gadget::query(), &request).await?;
    Ok(renox::axum::Json(serde_json::to_value(page)?).into_response())
}

struct Gadgets;

impl Module for Gadgets {
    fn name(&self) -> &'static str {
        "gadgets"
    }

    fn routes(&self) -> Routes {
        Routes::new().get("/gadgets", gadgets)
    }
}

async fn gadgets_app(locale: Option<&str>) -> (TestApp, tempfile::TempDir) {
    let lang = tempfile::tempdir().unwrap();
    std::fs::write(
        lang.path().join("es.json"),
        r#"{"ui.grid.yes": "Sí", "ui.grid.no": "No"}"#,
    )
    .unwrap();
    let (path, locale) = (lang.path().to_path_buf(), locale.map(str::to_owned));
    let app = TestApp::with_config(
        App::new().migrations(&[GADGETS]).module(Gadgets),
        move |c| {
            c.lang_path = path;
            c.timezone = "+07:00".parse().unwrap();
            if let Some(locale) = locale {
                c.locale = locale;
            }
        },
    )
    .await;
    let db = app.db();
    let mut makers = Vec::new();
    for (name, rating) in [("Acme", 4.5), ("Bolt", 3.0)] {
        makers.push(
            GridMaker::create(
                db,
                GridMaker {
                    name: name.into(),
                    rating: Some(rating),
                    ..Default::default()
                },
            )
            .await
            .unwrap()
            .id,
        );
    }
    let at = renox::chrono::DateTime::parse_from_rfc3339("2026-04-01T20:00:00Z")
        .unwrap()
        .with_timezone(&renox::chrono::Utc);
    for gadget in [
        Gadget {
            maker_id: Some(makers[0]),
            name: "Alpha".into(),
            active: Some(true),
            kind: Some("a".into()),
            note: Some("Red box".into()),
            price: 1.25,
            cost: 150_000,
            made_on: NaiveDate::from_ymd_opt(2026, 4, 1),
            made_at: Some(at),
            code: "007".into(),
            meta: Some(Json(json!({"x": 1}))),
            ..Default::default()
        },
        Gadget {
            maker_id: Some(makers[1]),
            name: "Beta".into(),
            active: Some(false),
            kind: Some("b".into()),
            note: Some("blue".into()),
            price: 2.5,
            cost: 2_000,
            code: "B2".into(),
            ..Default::default()
        },
        Gadget {
            name: "Gamma".into(),
            price: 0.75,
            code: "G".into(),
            ..Default::default()
        },
    ] {
        let mut gadget = gadget;
        gadget.save(db).await.unwrap();
    }
    (app, lang)
}

fn names(page: &Value) -> Vec<String> {
    page["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r["name"].as_str().unwrap().to_owned())
        .collect()
}

#[renox::test]
async fn negative_rules_on_yes_no_option_and_text_columns_keep_empty_rows() {
    let (app, _lang) = gadgets_app(None).await;
    let names_for = |q: &'static str| {
        let app = &app;
        async move { names(&app.get(&format!("/gadgets?{q}")).await.json()) }
    };
    assert_eq!(
        names_for("r.0.c=active&r.0.o=is_false").await,
        ["Beta", "Gamma"]
    );
    assert_eq!(names_for("r.0.c=active&r.0.o=is_true").await, ["Alpha"]);
    assert_eq!(
        names_for("r.0.c=note&r.0.o=not_contains&r.0.v=RED").await,
        ["Beta", "Gamma"]
    );
    assert_eq!(
        names_for("r.0.c=kind&r.0.o=is_not&r.0.v=a").await,
        ["Beta", "Gamma"]
    );
    assert_eq!(names_for("r.0.c=kind&r.0.o=is&r.0.v=a").await, ["Alpha"]);
    assert_eq!(
        names_for("r.0.c=kind&r.0.o=not_empty").await,
        ["Alpha", "Beta"]
    );
    // Numbers with a fraction compare as numbers.
    assert_eq!(
        names_for("r.0.c=price&r.0.o=gt&r.0.v=1.1").await,
        ["Alpha", "Beta"]
    );
    assert_eq!(
        names_for("r.0.c=price&r.0.o=lte&r.0.v=0.75").await,
        ["Gamma"]
    );
    // The related number, filtered by a range of fractions.
    assert_eq!(names_for("min.rating=3.5").await, ["Alpha"]);
}

#[renox::test]
async fn the_request_parser_drops_what_doesnt_fit() {
    let (app, _lang) = gadgets_app(None).await;
    for q in [
        // An operator no column has, and one this column doesn't take.
        "r.0.c=kind&r.0.o=bogus&r.0.v=a",
        "r.0.c=active&r.0.o=contains&r.0.v=x",
        // Rules on columns without operators (custom), or not filterable.
        "r.0.c=extra&r.0.o=contains&r.0.v=x",
        "r.0.c=name&r.0.o=equals&r.0.v=Alpha",
        // Malformed rule names, numbers past the limit, unknown fields, a
        // rule missing its value.
        "r.x.c=kind&r.x.o=is&r.x.v=a",
        "r.0=kind",
        "r.25.c=kind&r.25.o=is&r.25.v=a",
        "r.0.c=kind&r.0.o=is&r.0.z=a",
        "r.0.c=kind&r.0.o=is&r.0.v=",
        // Filters on an unknown column, a column that isn't filterable, a
        // custom and an image column, a bare name, an unknown part.
        "q.nope=1",
        "q.name=Alpha",
        "q.extra=x",
        "q.photo=x",
        "nope=1",
        "zz.kind=a",
        "in.kind=c",
        "in.active=maybe",
    ] {
        let page: Value = app.get(&format!("/gadgets?{q}")).await.json();
        assert_eq!(names(&page).len(), 3, "{q}");
    }
    // A picked yes/no value does filter.
    let page: Value = app.get("/gadgets?in.active=0").await.json();
    assert_eq!(names(&page), ["Beta"]);
}

#[renox::test]
async fn related_values_groups_summaries_and_pins() {
    let (app, _lang) = gadgets_app(None).await;
    let page: Value = app.get("/gadgets").await.json();
    let rows = page["rows"].as_array().unwrap();
    // String ids, a fraction and a whole number from the related table.
    assert!(
        rows[0]["_rx"]["id"].as_str().unwrap().len() == 26,
        "{}",
        rows[0]["_rx"]
    );
    assert_eq!(rows[0]["rating"], json!(4.5));
    assert_eq!(rows[1]["rating"], json!(3));
    assert_eq!(rows[2]["rating"], Value::Null);
    assert_eq!(rows[0]["maker"], "Acme");
    // The summary on a related column is skipped: only the model's own
    // columns are summed.
    let text = page.to_string();
    assert!(!text.contains("\"maker\":{\"count\""), "{text}");

    // Grouped by a yes/no column: true, false and empty each start a group.
    let page: Value = app.get("/gadgets?group=active").await.json();
    let groups: Vec<Value> = page["rows"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r["_rx"]["group"]["value"].clone())
        .collect();
    assert_eq!(groups.len(), 3);
    assert!(groups.contains(&Value::Null), "{groups:?}");
    for row in page["rows"].as_array().unwrap() {
        assert_eq!(row["_rx"]["group"]["rows"], json!(1), "{row}");
    }
    // Grouped by a number column.
    let page: Value = app.get("/gadgets?group=price").await.json();
    assert_eq!(page["rows"][0]["_rx"]["group"]["rows"], json!(1));

    // A column pinned right by the user's preferences.
    app.post_json(
        "/_renox/grid/gadgets/prefs",
        &json!({ "left": [], "right": ["price"] }),
    )
    .await
    .assert_status(204);
    let page: Value = app.get("/gadgets").await.json();
    let price = page["columns"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["key"] == "price")
        .unwrap()
        .clone();
    assert_eq!(price["pin"], "right", "{price}");
}

#[renox::test]
async fn csv_exports_use_the_apps_yes_no_and_write_json_cells() {
    let (app, _lang) = gadgets_app(Some("es")).await;
    let csv = app.get("/gadgets?export=csv").await.text();
    let lines: Vec<&str> = csv.trim_start_matches('\u{feff}').lines().collect();
    assert!(lines[1].contains(",Sí,Kind A,"), "{csv}");
    assert!(lines[2].contains(",No,Kind B,"), "{csv}");
    // A JSON value is written as JSON; a moment in APP_TIMEZONE; an
    // empty yes/no and option are empty.
    assert!(lines[1].contains(r#""{""x"":1}""#), "{csv}");
    assert!(lines[1].contains("2026-04-02 03:00"), "{csv}");
    assert!(lines[3].starts_with("Gamma,,,,,"), "{csv}");
}

/// The Excel file read back: numbers with their format, a money column,
/// a date and a moment as dates, text that looks like a number kept as
/// text, an empty cell left out.
#[renox::test]
async fn excel_exports_keep_numbers_dates_and_text_apart() {
    let (app, _lang) = gadgets_app(None).await;
    let res = app.get("/gadgets?export=xlsx").await;
    if !cfg!(feature = "xlsx") {
        return;
    }
    res.assert_ok();
    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(res.body.to_vec())).unwrap();
    let mut read = |name: &str| {
        let mut text = String::new();
        zip.by_name(name)
            .unwrap()
            .read_to_string(&mut text)
            .unwrap();
        text
    };
    let sheet = read("xl/worksheets/sheet1.xml");
    let styles = read("xl/styles.xml");
    let strings = read("xl/sharedStrings.xml");
    assert!(styles.contains(r##"formatCode="#,##0.00""##), "{styles}");
    assert!(styles.contains("yyyy-mm-dd hh:mm") && styles.contains(r#"formatCode="yyyy-mm-dd""#));
    // 1.25 is a number cell; "007" is a shared string, not the number 7.
    assert!(sheet.contains("<v>1.25</v>"), "{sheet}");
    assert!(strings.contains("<t>007</t>"), "{strings}");
    assert!(sheet.contains(r#"<c r="K2" t="s">"#), "{sheet}");
    // The date and the moment (20:00 UTC is 03:00 the next day at +07:00)
    // are dates: 2026-04-01 is day 46113.
    assert!(
        sheet.contains("<v>46113</v>") && sheet.contains("<v>46114.125</v>"),
        "{sheet}"
    );
    // Money in the smallest unit becomes the amount (IDR has no cents).
    assert!(sheet.contains("<v>150000</v>"), "{sheet}");
    // Gamma (row 4) has no maker: no cell B4.
    assert!(
        sheet.contains(r#"r="A4""#) && !sheet.contains(r#"r="B4""#),
        "{sheet}"
    );
}

#[renox::test]
async fn a_grid_request_without_renoxs_middleware_is_a_500() {
    use renox::axum::extract::FromRequestParts;

    let (mut parts, ()) = renox::axum::http::Request::new(()).into_parts();
    let Err(res) = GridRequest::from_request_parts(&mut parts, &()).await else {
        panic!("a GridRequest without the middleware");
    };
    assert_eq!(res.status(), 500);
}

/// A sort on a column a `SELECT *` model has without declaring it (an
/// extra column of `users`), both ways.
#[renox::test]
async fn sorting_by_an_extra_column_of_a_select_all_model() {
    async fn users(request: GridRequest) -> Result<renox::axum::Json<Value>> {
        let page = Grid::new("people")
            .column(Column::text("name", "Name"))
            .column(Column::number("score", "Score"))
            .sort_by("-score")
            .page(User::query(), &request)
            .await?;
        Ok(renox::axum::Json(serde_json::to_value(page)?))
    }
    struct People;
    impl Module for People {
        fn name(&self) -> &'static str {
            "people"
        }
        fn routes(&self) -> Routes {
            Routes::new().get("/people", users)
        }
    }
    let app = TestApp::new(App::new().module(Auth::new()).module(People)).await;
    let db = app.db();
    renox::db::sql("ALTER TABLE users ADD COLUMN score BIGINT")
        .execute(db)
        .await
        .unwrap();
    for (name, score) in [("Ann", 2), ("Ben", 9), ("Cy", 5)] {
        let user = User::register(db, name, &format!("{name}@example.com"), "password123")
            .await
            .unwrap();
        renox::db::sql("UPDATE users SET score = ? WHERE id = ?")
            .bind(score)
            .bind(user.id)
            .execute(db)
            .await
            .unwrap();
    }
    let page: Value = app.get("/people").await.json();
    assert_eq!(names(&page), ["Ben", "Cy", "Ann"]);
    let page: Value = app.get("/people?sort=score").await.json();
    assert_eq!(names(&page), ["Ann", "Cy", "Ben"]);
    if app.db().dialect() == Dialect::Postgres {
        // The same order on PostgreSQL, NULLs last either way.
        assert_eq!(page["rows"].as_array().unwrap().len(), 3);
    }
}
