//! M20b: queue priority, unique jobs, encrypted payloads, middleware,
//! chains, batches, the failed hook, dispatch_sync and pruning.

use std::time::Duration;

use renox::Kernel;
use renox::db::Dialect;
use renox::prelude::*;
use renox::queue::Middleware;
use serde::{Deserialize, Serialize};

async fn log(state: &AppState, message: impl Into<String>) -> Result {
    renox::db::sql("INSERT INTO log (message) VALUES (?)")
        .bind(message.into())
        .execute(&state.db)
        .await?;
    Ok(())
}

async fn logged(kernel: &Kernel) -> Vec<String> {
    renox::db::sql("SELECT message FROM log ORDER BY id")
        .scalars(kernel.db())
        .await
        .unwrap()
}

#[derive(Serialize, Deserialize)]
struct Say(String);

impl Job for Say {
    const NAME: &'static str = "say";

    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, self.0).await
    }
}

#[derive(Serialize, Deserialize)]
struct Urgent(String);

impl Job for Urgent {
    const NAME: &'static str = "urgent";
    const QUEUE: &'static str = "high";

    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, self.0).await
    }
}

/// Fails for good on its first attempt, and says so in its `failed` hook.
/// (Permanent, not retried: a retry is due in the second it's recorded,
/// which may be later than the jobs queued after it, so the order in a
/// batch would depend on the clock.)
#[derive(Serialize, Deserialize)]
struct Broken(String);

impl Job for Broken {
    const NAME: &'static str = "broken";

    async fn handle(self, _: JobContext) -> Result {
        Err(Error::permanent(anyhow::anyhow!("the supplier is down")))
    }

    async fn failed(self, state: AppState, error: String) {
        let _ = log(
            &state,
            format!("gave up on {}: {}", self.0, error.contains("supplier")),
        )
        .await;
    }
}

#[derive(Serialize, Deserialize)]
struct SyncShop {
    shop: i64,
}

impl Job for SyncShop {
    const NAME: &'static str = "sync-shop";
    const UNIQUE_FOR: Option<Duration> = Some(Duration::from_secs(600));

    fn unique_id(&self) -> String {
        self.shop.to_string()
    }

    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, format!("synced {}", self.shop)).await
    }
}

#[derive(Serialize, Deserialize)]
struct Secret {
    card: String,
}

impl Job for Secret {
    const NAME: &'static str = "secret";
    const ENCRYPTED: bool = true;
    const MAX_ATTEMPTS: u32 = 1;

    async fn handle(self, ctx: JobContext) -> Result {
        if self.card == "bad" {
            return Err(Error::permanent(anyhow::anyhow!("declined")));
        }
        log(
            &ctx.state,
            format!("charged {}", &self.card[self.card.len() - 4..]),
        )
        .await
    }
}

#[derive(Serialize, Deserialize)]
struct CallApi(i64);

impl Job for CallApi {
    const NAME: &'static str = "call-api";

    fn middleware(&self) -> Vec<Middleware> {
        vec![
            Middleware::without_overlapping("api").release_after(Duration::from_secs(30)),
            Middleware::rate_limited("api", 2, Duration::from_secs(3600)),
        ]
    }

    async fn handle(self, ctx: JobContext) -> Result {
        log(&ctx.state, format!("call {}", self.0)).await
    }
}

async fn kernel() -> Kernel {
    let mut config = Config::default();
    config.env = Environment::Testing;
    config.key = Some(renox::generate_key());
    let kernel = App::with_config(config)
        .job::<Say>()
        .job::<Urgent>()
        .job::<Broken>()
        .job::<SyncShop>()
        .job::<Secret>()
        .job::<CallApi>()
        .boot()
        .await
        .unwrap();
    kernel.migrate().await.unwrap();
    renox::db::sql(match kernel.db().dialect() {
        Dialect::Sqlite => "CREATE TABLE log (id INTEGER PRIMARY KEY, message TEXT NOT NULL)",
        Dialect::Postgres => {
            "CREATE TABLE log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
             message TEXT NOT NULL)"
        }
    })
    .execute(kernel.db())
    .await
    .unwrap();
    kernel
}

async fn count(kernel: &Kernel, sql: &str) -> i64 {
    renox::db::sql(sql.to_owned())
        .scalar(kernel.db())
        .await
        .unwrap()
}

#[tokio::test]
async fn listed_queues_drain_in_order() {
    let kernel = kernel().await;
    let queue = &kernel.state().queue;
    queue.dispatch(Say("default 1".into())).await.unwrap();
    queue.dispatch(Urgent("high 1".into())).await.unwrap();
    queue
        .dispatch_on("high", Say("high 2".into()))
        .await
        .unwrap();
    queue.dispatch(Say("default 2".into())).await.unwrap();
    kernel
        .worker(vec!["high".into(), "default".into()])
        .drain()
        .await
        .unwrap();
    assert_eq!(
        logged(&kernel).await,
        ["high 1", "high 2", "default 1", "default 2"]
    );

    queue.dispatch(Urgent("high 3".into())).await.unwrap();
    queue.dispatch(Say("default 3".into())).await.unwrap();
    let worker = kernel.worker(vec!["default".into(), "high".into()]);
    worker.run_next().await.unwrap();
    assert_eq!(logged(&kernel).await.last().unwrap(), "default 3");
}

#[tokio::test]
async fn unique_jobs_are_queued_once() {
    let kernel = kernel().await;
    let queue = &kernel.state().queue;
    let first = queue.dispatch(SyncShop { shop: 1 }).await.unwrap();
    assert_eq!(queue.dispatch(SyncShop { shop: 1 }).await.unwrap(), first);
    let other = queue.dispatch(SyncShop { shop: 2 }).await.unwrap();
    assert_ne!(other, first);
    assert_eq!(queue.pending().await.unwrap(), 2);

    // Inside a transaction too.
    let mut tx = kernel.db().begin().await.unwrap();
    assert_eq!(
        queue
            .dispatch_in(&mut tx, SyncShop { shop: 1 })
            .await
            .unwrap(),
        first
    );
    tx.commit().await.unwrap();

    // Once it has run, the claim is gone.
    kernel.worker(vec![]).drain().await.unwrap();
    assert_eq!(logged(&kernel).await, ["synced 1", "synced 2"]);
    let again = queue.dispatch(SyncShop { shop: 1 }).await.unwrap();
    assert!(again > other);
    // `flush` of the cache doesn't drop claims.
    kernel.state().cache.flush().await.unwrap();
    assert_eq!(queue.dispatch(SyncShop { shop: 1 }).await.unwrap(), again);
}

#[tokio::test]
async fn encrypted_payloads_stay_encrypted_at_rest() {
    let kernel = kernel().await;
    let queue = &kernel.state().queue;
    queue
        .dispatch(Secret {
            card: "4111111111111111".into(),
        })
        .await
        .unwrap();
    let stored: String = renox::db::sql("SELECT payload FROM jobs")
        .scalar(kernel.db())
        .await
        .unwrap();
    assert!(
        stored.starts_with("enc:") && !stored.contains("4111"),
        "{stored}"
    );
    queue.dispatch(Secret { card: "bad".into() }).await.unwrap();
    kernel.worker(vec![]).drain().await.unwrap();
    assert_eq!(logged(&kernel).await, ["charged 1111"]);
    let failed = queue.failed().await.unwrap();
    assert_eq!(failed.len(), 1);
    assert!(failed[0].payload.starts_with("enc:") && failed[0].error.contains("declined"));

    // A payload sealed with another key fails for good, and says why.
    renox::db::sql(
        "INSERT INTO jobs (queue, job, payload, max_attempts, available_at, created_at) \
         VALUES ('default', 'secret', 'enc:bm9wZQ==', 3, 0, 0)",
    )
    .execute(kernel.db())
    .await
    .unwrap();
    kernel.worker(vec![]).drain().await.unwrap();
    let failed = queue.failed().await.unwrap();
    assert!(failed[1].error.contains("APP_KEY"), "{}", failed[1].error);
}

#[tokio::test]
async fn middleware_holds_jobs_back_without_using_attempts() {
    let kernel = kernel().await;
    let state = kernel.state();
    let worker = kernel.worker(vec![]);

    // Another worker holds the overlap lock.
    let held = state
        .cache
        .lock("overlap:api", Duration::from_secs(60))
        .try_acquire()
        .await
        .unwrap()
        .unwrap();
    state.queue.dispatch(CallApi(1)).await.unwrap();
    assert!(worker.run_next().await.unwrap());
    assert!(logged(&kernel).await.is_empty());
    let (attempts, wait) = (
        count(&kernel, "SELECT attempts FROM jobs").await,
        count(&kernel, "SELECT available_at FROM jobs").await - renox::db::now().timestamp(),
    );
    assert_eq!(attempts, 0, "the attempt isn't counted");
    assert!(
        (28..=30).contains(&wait),
        "put back for release_after: {wait}"
    );
    held.release().await.unwrap();

    // 2 calls an hour: the third waits for the next window.
    renox::db::sql("UPDATE jobs SET available_at = 0")
        .execute(kernel.db())
        .await
        .unwrap();
    state.queue.dispatch(CallApi(2)).await.unwrap();
    state.queue.dispatch(CallApi(3)).await.unwrap();
    worker.drain().await.unwrap();
    assert_eq!(logged(&kernel).await, ["call 1", "call 2"]);
    assert_eq!(state.queue.pending().await.unwrap(), 1);
    assert_eq!(count(&kernel, "SELECT attempts FROM jobs").await, 0);
    assert!(
        !state
            .cache
            .lock("overlap:api", Duration::from_secs(1))
            .is_held()
            .await
            .unwrap()
    );
}

#[tokio::test]
async fn chains_run_in_order_and_stop_at_a_failure() {
    let kernel = kernel().await;
    let queue = &kernel.state().queue;
    let worker = kernel.worker(vec![]);
    queue
        .chain()
        .then(Say("one".into()))
        .then(Urgent("two".into()))
        .then(Say("three".into()))
        .dispatch()
        .await
        .unwrap();
    assert_eq!(queue.pending().await.unwrap(), 1, "one link at a time");
    worker.drain().await.unwrap();
    assert_eq!(logged(&kernel).await, ["one", "two", "three"]);

    queue
        .chain()
        .then(Broken("link".into()))
        .then(Say("never".into()))
        .dispatch()
        .await
        .unwrap();
    worker.drain().await.unwrap();
    let log = logged(&kernel).await;
    assert_eq!(
        log.last().unwrap(),
        "gave up on link: true",
        "the failed hook ran"
    );
    assert!(!log.contains(&"never".to_owned()));
    let rest: Option<String> = renox::db::sql("SELECT chain FROM failed_jobs")
        .scalar(kernel.db())
        .await
        .unwrap();
    assert!(
        rest.unwrap().contains("never"),
        "the rest waits with the failed job"
    );
    assert_eq!(queue.chain().dispatch().await.unwrap(), 0);
}

#[tokio::test]
async fn batches_track_progress_and_follow_up() {
    let kernel = kernel().await;
    let queue = &kernel.state().queue;
    let worker = kernel.worker(vec![]);

    let ok = queue
        .batch("greetings")
        .push(Say("a".into()))
        .push(Say("b".into()))
        .then(Say("then".into()))
        .catch(Say("catch".into()))
        .finally(Say("finally".into()))
        .dispatch()
        .await
        .unwrap();
    let status = queue.batch_status(ok).await.unwrap().unwrap();
    assert_eq!((status.total, status.pending, status.progress()), (2, 2, 0));
    worker.run_next().await.unwrap();
    assert_eq!(
        queue.batch_status(ok).await.unwrap().unwrap().progress(),
        50
    );
    worker.drain().await.unwrap();
    let status = queue.batch_status(ok).await.unwrap().unwrap();
    assert!(status.finished && !status.cancelled && status.failed == 0);
    assert_eq!(logged(&kernel).await, ["a", "b", "then", "finally"]);

    // The first failure cancels the rest, runs `catch` and `finally`.
    let bad = queue
        .batch("fragile")
        .push(Broken("x".into()))
        .push(Say("skipped".into()))
        .then(Say("then 2".into()))
        .catch(Say("catch 2".into()))
        .finally(Say("finally 2".into()))
        .dispatch()
        .await
        .unwrap();
    worker.drain().await.unwrap();
    let status = queue.batch_status(bad).await.unwrap().unwrap();
    assert!(status.finished && status.cancelled);
    assert_eq!(
        (status.failed, status.pending, status.progress()),
        (1, 0, 100)
    );
    let log = logged(&kernel).await;
    assert_eq!(&log[4..], ["gave up on x: true", "catch 2", "finally 2"]);

    // With allow_failures, the others run; `then` doesn't, `finally` does.
    let tolerant = queue
        .batch("tolerant")
        .push(Broken("y".into()))
        .push(Say("still runs".into()))
        .then(Say("then 3".into()))
        .finally(Say("finally 3".into()))
        .allow_failures()
        .dispatch()
        .await
        .unwrap();
    worker.drain().await.unwrap();
    let log = logged(&kernel).await;
    assert!(log.contains(&"still runs".to_owned()) && log.contains(&"finally 3".to_owned()));
    assert!(!log.contains(&"then 3".to_owned()));

    // Retrying the failed job puts it back in its batch.
    let failed = queue.failed().await.unwrap();
    let y = failed.iter().find(|f| f.payload.contains('y')).unwrap();
    queue.retry(Some(y.id)).await.unwrap();
    let status = queue.batch_status(tolerant).await.unwrap().unwrap();
    assert_eq!(
        (status.failed, status.pending, status.finished),
        (0, 1, false)
    );

    // An empty batch is finished at once; a cancelled one skips its jobs.
    let empty = queue
        .batch("empty")
        .then(Say("empty then".into()))
        .dispatch()
        .await
        .unwrap();
    assert!(queue.batch_status(empty).await.unwrap().unwrap().finished);
    let cancelled = queue
        .batch("stopped")
        .push(Say("not me".into()))
        .dispatch()
        .await
        .unwrap();
    assert!(queue.cancel_batch(cancelled).await.unwrap());
    assert!(!queue.cancel_batch(cancelled).await.unwrap());
    worker.drain().await.unwrap();
    assert!(!logged(&kernel).await.contains(&"not me".to_owned()));
    assert!(queue.batch_status(999).await.unwrap().is_none());
}

#[tokio::test]
async fn sync_dispatch_forget_and_prune() {
    let kernel = kernel().await;
    let state = kernel.state();
    state.dispatch_sync(Say("now".into())).await.unwrap();
    assert!(state.dispatch_sync(Broken("sync".into())).await.is_err());
    assert_eq!(logged(&kernel).await, ["now"]);
    assert_eq!(state.queue.pending().await.unwrap(), 0);

    for name in ["p", "q"] {
        state.queue.dispatch(Broken(name.into())).await.unwrap();
    }
    kernel.worker(vec![]).drain().await.unwrap();
    let failed = state.queue.failed().await.unwrap();
    assert!(state.queue.forget_failed(failed[0].id).await.unwrap());
    assert!(!state.queue.forget_failed(failed[0].id).await.unwrap());
    assert_eq!(
        state
            .queue
            .prune_failed(Duration::from_secs(3600))
            .await
            .unwrap(),
        0
    );
    renox::db::sql("UPDATE failed_jobs SET failed_at = 0")
        .execute(kernel.db())
        .await
        .unwrap();
    assert_eq!(
        state
            .queue
            .prune_failed(Duration::from_secs(3600))
            .await
            .unwrap(),
        1
    );

    let batch = state.queue.batch("old").dispatch().await.unwrap();
    assert_eq!(
        state
            .queue
            .prune_batches(Duration::from_secs(3600))
            .await
            .unwrap(),
        0
    );
    renox::db::sql("UPDATE job_batches SET finished_at = 1")
        .execute(kernel.db())
        .await
        .unwrap();
    assert_eq!(
        state
            .queue
            .prune_batches(Duration::from_secs(3600))
            .await
            .unwrap(),
        1
    );
    assert!(state.queue.batch_status(batch).await.unwrap().is_none());
}
