//! M24: the items M21 deferred: domain and fallback routes, `route_is` and
//! `CurrentRoute`, `Redirect::route`/`intended`, session `push`/`increment`,
//! factory states and sequences, plural ranges, `{% break %}` and
//! `class_names`.

use renox::db::{Migration, Scripts};
use renox::prelude::*;
use renox::testing::TestApp;
use renox::{CurrentRoute, DomainParams};

const SCHEMA: Migration = Migration {
    name: "20300101000000_leftovers",
    up: "",
    down: None,
    sqlite: Some(Scripts {
        up: "CREATE TABLE beans (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, stock INTEGER NOT NULL)",
        down: None,
    }),
    postgres: Some(Scripts {
        up: "CREATE TABLE beans (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, stock BIGINT NOT NULL)",
        down: None,
    }),
};

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "beans")]
struct Bean {
    id: i64,
    name: String,
    stock: i64,
}

impl Factory for Bean {
    fn definition() -> Self {
        Bean {
            name: "Arabica".into(),
            stock: 10,
            ..Default::default()
        }
    }
}

fn sold_out(bean: &mut Bean) {
    bean.stock = 0;
}

struct Site;

impl Module for Site {
    fn name(&self) -> &'static str {
        "site"
    }

    fn routes(&self) -> Routes {
        let tenant = |domain: DomainParams| async move {
            format!("store {}", domain.get("account").unwrap_or("?"))
        };
        Routes::new()
            .get("/", || async { "home" })
            .name("home")
            .get("/beans/{id}", |Path(id): Path<i64>| async move {
                format!("bean {id}")
            })
            .name("beans.show")
            .get("/menu", || async { view("menu.html", context! {}) })
            .name("shop.menu")
            .get("/route", |route: CurrentRoute| async move {
                format!(
                    "{} {} {}",
                    route.name().unwrap_or("-"),
                    route.path().unwrap_or("-"),
                    route.is("beans.*")
                )
            })
            .name("beans.route")
            .get("/go", || async { Redirect::route("beans.show", &[&7]) })
            .get("/after", |session: Session| async move {
                Redirect::intended(&session, "/fallback-home")
            })
            .merge(
                Routes::new()
                    .get("/private", || async { "private" })
                    .require_auth(),
            )
            .get("/cart", |session: Session| async move {
                let items = session.push("cart", "coffee")?;
                let visits = session.increment("visits", 1)?;
                Ok::<_, Error>(format!("{items} {visits}"))
            })
            .get("/texts", || async { view("texts.html", context! {}) })
            .fallback(|uri: axum::http::Uri| async move {
                (StatusCode::NOT_FOUND, format!("no page at {}", uri.path()))
            })
            .domain(
                "admin.example.com",
                Routes::new()
                    // Not a 404: a fallback's own status is kept.
                    .fallback(|| async { Redirect::to("/") })
                    .get("/", || async { "admin" })
                    .name("admin.dashboard")
                    .get("/menu", || async { view("menu.html", context! {}) })
                    .name("admin.menu"),
            )
            .domain(
                "{account}.shops.test",
                Routes::new().get("/", tenant).name("tenant.home"),
            )
    }
}

struct Billing;

impl Module for Billing {
    fn name(&self) -> &'static str {
        "billing"
    }

    fn routes(&self) -> Routes {
        // Another module adds to the same domain.
        Routes::new().domain(
            "admin.example.com",
            Routes::new().get("/invoices", || async { "invoices" }),
        )
    }
}

async fn app() -> (TestApp, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(dir.path().join("public")).unwrap();
    std::fs::write(dir.path().join("public/robots-extra.txt"), "static").unwrap();
    std::fs::write(
        dir.path().join("menu.html"),
        r#"<nav>{% for item in ["coffee", "tea", "milk"] %}{% if item == "milk" %}{% break %}{% endif %}<a class="{{ class_names('tab', {'tab-active': route_is('shop.*'), 'admin': route_is('admin.*')}) }}">{{ item }}</a>{% endfor %}</nav> route={{ request.route }}"#,
    )
    .unwrap();
    std::fs::write(
        dir.path().join("texts.html"),
        "{% for n in [0, 3, 12] %}{{ t('messages', count=n) }};{% endfor %}",
    )
    .unwrap();
    std::fs::create_dir_all(dir.path().join("lang")).unwrap();
    std::fs::write(
        dir.path().join("lang/en.json"),
        r#"{"messages": "{0} No messages|[1,9] :count messages|[10,*] Lots of messages"}"#,
    )
    .unwrap();
    let (views, public, lang) = (
        dir.path().to_path_buf(),
        dir.path().join("public"),
        dir.path().join("lang"),
    );
    let app = TestApp::with_config(
        App::new()
            .migrations(&[SCHEMA])
            .module(Auth::new())
            .module(Site)
            .module(Billing),
        |c| {
            c.views_path = views;
            c.public_path = public;
            c.lang_path = lang;
        },
    )
    .await;
    (app, dir)
}

async fn on(app: &TestApp, host: &str, path: &str) -> renox::testing::TestResponse {
    app.request().header("host", host).get(path).await
}

#[renox::test]
async fn domains_have_their_own_routes() {
    let (app, _dir) = app().await;
    // The same path, three pages.
    on(&app, "example.com", "/").await.assert_see("home");
    on(&app, "admin.example.com", "/").await.assert_see("admin");
    on(&app, "ADMIN.example.com:8080", "/")
        .await
        .assert_see("admin");
    on(&app, "acme.shops.test", "/")
        .await
        .assert_see("store acme");
    app.get("/").await.assert_see("home"); // no Host: the default routes

    // Two modules share the admin domain; its routes stay there.
    on(&app, "admin.example.com", "/invoices")
        .await
        .assert_see("invoices");
    on(&app, "example.com", "/invoices")
        .await
        .assert_status(404)
        .assert_see("no page at /invoices");
    // The admin domain's fallback redirects (a public directory exists, and
    // the status isn't turned into a 404).
    on(&app, "admin.example.com", "/beans/1")
        .await
        .assert_redirect("/");
    // Renox's own routes and public files work on every host.
    on(&app, "admin.example.com", "/health").await.assert_ok();
    on(&app, "admin.example.com", "/robots-extra.txt")
        .await
        .assert_see("static");

    // Names are global; route() gives the path.
    assert_eq!(app.state().url("admin.dashboard", &[]).unwrap(), "/");
    let admin_routes: Vec<_> = app
        .kernel()
        .routes()
        .iter()
        .filter(|r| r.domain.as_deref() == Some("admin.example.com"))
        .map(|r| (r.path.as_str(), r.module.as_str()))
        .collect();
    assert!(admin_routes.contains(&("/", "site")), "{admin_routes:?}");
    assert!(admin_routes.contains(&("/invoices", "billing")));
}

#[renox::test]
async fn clashing_domain_routes_stop_the_boot() {
    struct Twice;
    impl Module for Twice {
        fn name(&self) -> &'static str {
            "twice"
        }
        fn routes(&self) -> Routes {
            Routes::new().domain(
                "admin.example.com",
                Routes::new().get("/invoices", || async { "again" }),
            )
        }
    }
    let err = App::with_config(renox::Config::default())
        .module(Billing)
        .module(Twice)
        .boot()
        .await
        .err()
        .expect("a clash");
    let message = format!("{err:?}");
    assert!(message.contains("on admin.example.com"), "{message}");
    // Same path on another domain: fine.
    assert!(
        App::with_config(renox::Config::default())
            .module(Billing)
            .module(Site)
            .boot()
            .await
            .is_ok()
    );
}

#[renox::test]
async fn the_fallback_answers_what_nothing_else_does() {
    let (app, _dir) = app().await;
    app.get("/robots-extra.txt").await.assert_see("static");
    app.get("/nothing/here")
        .await
        .assert_status(404)
        .assert_see("no page at /nothing/here");
}

#[renox::test]
async fn views_and_handlers_know_the_current_route() {
    let (app, _dir) = app().await;
    let page = app.get("/menu").await;
    page.assert_ok()
        .assert_see(
            r#"<a class="tab tab-active">coffee</a><a class="tab tab-active">tea</a></nav>"#,
        )
        .assert_see("route=shop.menu");
    // `{% break %}` stopped before milk.
    page.assert_dont_see("milk");
    on(&app, "admin.example.com", "/menu")
        .await
        .assert_see(r#"<a class="tab admin">coffee</a>"#)
        .assert_see("route=admin.menu");
    app.get("/route")
        .await
        .assert_see("beans.route /route true");
}

#[renox::test]
async fn redirects_to_routes_and_intended_pages() {
    let (app, _dir) = app().await;
    app.get("/go").await.assert_redirect("/beans/7");
    // Nothing stored: the fallback.
    app.get("/after").await.assert_redirect("/fallback-home");
    // A guard stores the page; `intended` goes back to it once.
    app.get("/private").await.assert_redirect("/login");
    app.get("/after").await.assert_redirect("/private");
    app.get("/after").await.assert_redirect("/fallback-home");
}

#[renox::test]
async fn sessions_push_and_increment() {
    let (app, _dir) = app().await;
    app.get("/cart").await.assert_see("1 1");
    app.get("/cart").await.assert_see("2 2");
    assert_eq!(
        app.session_get::<Vec<String>>("cart"),
        Some(vec!["coffee".to_owned(), "coffee".to_owned()])
    );
}

#[renox::test]
async fn factories_take_states_and_sequences() {
    let (app, _dir) = app().await;
    let db = app.db();
    let made = Bean::factory()
        .count(3)
        .state(sold_out)
        .sequence(|i, bean| bean.name = ["Arabica", "Robusta", "Liberica"][i % 3].into())
        .create(db)
        .await
        .unwrap();
    assert_eq!(made.len(), 3);
    assert!(made.iter().all(|b| b.stock == 0 && b.id != 0));
    assert_eq!(made[1].name, "Robusta");
    assert_eq!(Bean::all(db).await.unwrap().len(), 3);
    let unsaved = Bean::factory()
        .state(|b: &mut Bean| b.stock = 99)
        .make_one();
    assert_eq!((unsaved.id, unsaved.stock), (0, 99));
    let one = Bean::factory().create_one(db).await.unwrap();
    assert_eq!(one.name, "Arabica");
}

#[renox::test]
async fn translations_choose_plural_ranges() {
    let (app, _dir) = app().await;
    app.get("/texts")
        .await
        .assert_see("No messages;3 messages;Lots of messages;");
}
