//! `#[derive(Model)]` describes its columns, `#[derive(DbEnum)]` counts as text.

use renox::db::{ColumnKind, Encrypted, Json, Model};
use renox::prelude::*;

#[derive(DbEnum, Debug, Clone, Copy, Default, PartialEq)]
enum Status {
    #[default]
    Open,
    Closed,
}

/// A local type stored as text, but with no `ColumnType`.
#[derive(Debug, Clone, Default, PartialEq)]
struct Custom(String);

impl std::str::FromStr for Custom {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, String> {
        Ok(Custom(s.to_string()))
    }
}

impl std::fmt::Display for Custom {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl renox::db::ToDbValue for Custom {
    fn to_db_value(&self) -> renox::db::DbValue {
        renox::db::DbValue::Text(self.0.clone())
    }
}

renox::__db_text_type!(Custom);

#[derive(Model, Debug, Clone, Default)]
#[model(table = "gadgets")]
struct Gadget {
    id: i64,
    name: String,
    price: Option<i64>,
    active: bool,
    born: Option<renox::chrono::NaiveDate>,
    at: DateTime,
    tags: Json<Vec<String>>,
    secret: Encrypted<String>,
    status: Status,
    custom: Custom,
    #[allow(dead_code)]
    #[model(skip)]
    scratch: String,
}

#[test]
fn the_derive_describes_every_column() {
    let columns = Gadget::column_info();
    let names: Vec<_> = columns.iter().map(|c| c.name).collect();
    assert_eq!(
        names,
        [
            "id", "name", "price", "active", "born", "at", "tags", "secret", "status", "custom"
        ]
    );
    let expect = [
        ("id", ColumnKind::BigInt, false, "i64"),
        ("name", ColumnKind::Text, false, "String"),
        ("price", ColumnKind::BigInt, true, "i64"),
        ("active", ColumnKind::Bool, false, "bool"),
        ("born", ColumnKind::Date, true, "NaiveDate"),
        ("at", ColumnKind::DateTime, false, "DateTime"),
        ("tags", ColumnKind::Json, false, "Json"),
        ("secret", ColumnKind::Text, false, "Encrypted"),
        ("status", ColumnKind::Text, false, "Status"),
        ("custom", ColumnKind::Unknown, false, "Custom"),
    ];
    for (c, (name, kind, nullable, ty)) in columns.iter().zip(expect) {
        assert_eq!(c.name, name);
        assert_eq!(c.kind, kind, "{name}");
        assert_eq!(c.nullable, nullable, "{name}");
        assert!(c.rust_type.contains(ty), "{name}: {}", c.rust_type);
    }
}

mod db_check {
    use std::sync::Arc;
    use std::sync::atomic::{AtomicBool, Ordering};

    use renox::db::Migration;
    use renox::prelude::*;
    use renox::testing::TestApp;

    #[derive(Model, Debug, Clone, Default)]
    #[model(table = "goods")]
    struct Good {
        id: i64,
        name: String,
        price: i64,
    }

    #[derive(Model, Debug, Clone, Default)]
    #[model(table = "bads")]
    struct Bad {
        id: i64,
        name: String,
        title: String,
        price: i64,
    }

    const GOOD: Migration = Migration::new("20300101000000_goods", "", Some("DROP TABLE goods;"))
        .sqlite(
            "CREATE TABLE goods (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL,
                price INTEGER NOT NULL);",
            None,
        )
        .postgres(
            "CREATE TABLE goods (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL, price BIGINT NOT NULL);",
            None,
        );

    // name nullable, title an integer, price missing, stock NOT NULL without a default.
    const BAD: Migration = Migration::new("20300101000001_bads", "", Some("DROP TABLE bads;"))
        .sqlite(
            "CREATE TABLE bads (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT,
                title INTEGER NOT NULL, stock INTEGER NOT NULL);",
            None,
        )
        .postgres(
            "CREATE TABLE bads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT, title BIGINT NOT NULL, stock BIGINT NOT NULL);",
            None,
        );

    fn config(dir: &std::path::Path) -> Config {
        let mut config = Config::default();
        config.storage_path = dir.join("storage");
        config
    }

    #[renox::test]
    async fn db_check_passes_for_a_matching_model() {
        let dir = tempfile::tempdir().unwrap();
        let app = App::new()
            .config(config(dir.path()))
            .migrations(&[GOOD])
            .model::<Good>();
        app.run_args(["db:check"]).await.unwrap();
    }

    #[renox::test]
    async fn db_check_fails_and_counts_the_problems() {
        let dir = tempfile::tempdir().unwrap();
        let app = App::new()
            .config(config(dir.path()))
            .migrations(&[GOOD, BAD])
            .model::<Good>()
            .model::<Bad>();
        let err = app.run_args(["db:check"]).await.unwrap_err();
        let text = err.to_string();
        assert!(text.contains("problem(s) in the models"), "{text}");
        assert!(!text.starts_with("0 "), "{text}");
    }

    #[renox::test]
    async fn an_app_command_named_db_check_wins() {
        let dir = tempfile::tempdir().unwrap();
        let ran = Arc::new(AtomicBool::new(false));
        let flag = ran.clone();
        let app = App::new()
            .config(config(dir.path()))
            .migrations(&[GOOD, BAD])
            .model::<Bad>()
            .command("db:check", "Mine", move |_args, _state| {
                let flag = flag.clone();
                async move {
                    flag.store(true, Ordering::SeqCst);
                    Ok(())
                }
            });
        app.run_args(["db:check"]).await.unwrap();
        assert!(ran.load(Ordering::SeqCst));
    }

    #[renox::test]
    async fn assert_models_match_schema_passes_for_a_matching_model() {
        let app = TestApp::new(App::new().migrations(&[GOOD]).model::<Good>()).await;
        app.assert_models_match_schema().await;
    }

    #[renox::test]
    async fn assert_models_match_schema_names_every_problem() {
        let app = TestApp::new(App::new().migrations(&[BAD]).model::<Bad>()).await;
        let handle = tokio::spawn(async move { app.assert_models_match_schema().await });
        let err = handle.await.unwrap_err();
        assert!(err.is_panic());
        let payload = err.into_panic();
        let text = payload
            .downcast_ref::<String>()
            .cloned()
            .or_else(|| payload.downcast_ref::<&str>().map(|s| s.to_string()))
            .unwrap();
        for needle in ["bads", "name", "title", "price", "stock"] {
            assert!(text.contains(needle), "{needle} missing in:\n{text}");
        }
        assert!(text.contains("4 problems"), "{text}");
    }
}

// `index(user_id)` twice in one list is what clippy flags; the columns differ.
#[allow(clippy::duplicated_attributes)]
#[derive(Model, Debug, Clone, Default)]
#[model(
    table = "posts",
    index(user_id),
    unique(slug),
    index(user_id, created_at)
)]
struct Post {
    id: i64,
    #[model(references = "users")]
    user_id: i64,
    slug: String,
    #[model(default = "0")]
    views: i64,
    created_at: DateTime,
}

#[test]
fn indexes_defaults_and_references_round_trip() {
    let indexes = Post::indexes();
    let got: Vec<_> = indexes.iter().map(|i| (i.columns, i.unique)).collect();
    assert_eq!(
        got,
        [
            (&["user_id"][..], false),
            (&["slug"][..], true),
            (&["user_id", "created_at"][..], false),
        ]
    );
    let columns = Post::column_info();
    let col = |n: &str| columns.iter().find(|c| c.name == n).unwrap().clone();
    assert_eq!(col("user_id").references, Some("users"));
    assert_eq!(col("user_id").default, None);
    assert_eq!(col("views").default, Some("0"));
    assert_eq!(col("views").references, None);
    assert!(Gadget::indexes().is_empty());
}
