//! #244: roles given in one record (a store) and for a period: the active
//! scope per request, `has_permission_in`, `scopes_with` in a default
//! scope, the dates under `TestApp::travel`, and the data APIs.

use std::time::Duration;

use renox::auth::permissions::{self, Assignment, Permissions, Scope, Scopes};
use renox::axum::extract::Request;
use renox::axum::middleware::{Next, from_fn};
use renox::prelude::*;
use renox::testing::TestApp;

const DAY: Duration = Duration::from_secs(24 * 60 * 60);

#[derive(Model, serde::Serialize, Default, Clone)]
#[model(table = "stores")]
struct Store {
    id: i64,
    name: String,
}

/// Seen from the store it leaves and from the one it goes to.
#[derive(Model, serde::Serialize, Default, Clone)]
#[model(table = "transfers", default_scope = "my_stores")]
struct Transfer {
    id: i64,
    from_store_id: i64,
    to_store_id: i64,
    note: String,
}

fn my_stores(query: renox::db::Query<Transfer>) -> renox::db::Query<Transfer> {
    permissions::scopes_with::<Store>("transfers.view")
        .apply(query, &["from_store_id", "to_store_id"])
}

/// The store a request works in, from a header (an app would check the
/// user may work there, and keep it in the session).
async fn pick_store(req: Request, next: Next) -> Response {
    let store = req
        .headers()
        .get("x-store")
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.parse::<i64>().ok());
    if let Some(store) = store {
        permissions::set_scope(Scope::of_id::<Store>(store));
    }
    next.run(req).await
}

async fn me(user: AuthUser) -> String {
    let scopes = match user.scopes_with::<Store>("orders.refund") {
        Scopes::All => "all".to_owned(),
        Scopes::Only(ids) => format!("{ids:?}"),
    };
    format!(
        "roles={} manager={} refund={} allows={} in1={} in2={} scopes={scopes} user_in2={}",
        user.role_names().join("+"),
        user.has_role("manager"),
        user.has_permission("orders.refund"),
        user.allows("orders.refund"),
        user.has_permission_in("orders.refund", &Scope::of_id::<Store>(1)),
        user.has_permission_in("orders.refund", &Scope::of_id::<Store>(2)),
        // `User`'s own checks read the request's grants (policies get a `User`).
        user.user()
            .has_permission_in("orders.refund", &Scope::of_id::<Store>(2)),
    )
}

async fn transfers(State(db): State<Db>) -> Result<String> {
    let notes: Vec<String> = Transfer::query().order_by("id").pluck(&db, "note").await?;
    Ok(notes.join(","))
}

struct Shops;

impl Module for Shops {
    fn name(&self) -> &'static str {
        "shops"
    }

    fn routes(&self) -> Routes {
        let open = Routes::new()
            .get("/me", me)
            .get("/transfers", transfers)
            .get("/page", || async { view("page.html", ()) })
            .require_auth();
        let refund = Routes::new()
            .get("/refund", || async { "refunded" })
            .require_permission("orders.refund");
        let manage = Routes::new()
            .get("/manage", || async { "managing" })
            .require_role("manager");
        open.merge(refund).merge(manage)
    }
}

fn app() -> App {
    App::new()
        .module(Auth::new())
        .module(Permissions)
        .module(Shops)
        .layer(from_fn(pick_store))
}

async fn boot() -> (TestApp, tempfile::TempDir) {
    let views = tempfile::tempdir().unwrap();
    std::fs::write(
        views.path().join("page.html"),
        "{% if can('orders.refund') %}can-refund{% endif %} roles={{ auth.roles | join(',') }}",
    )
    .unwrap();
    let app = TestApp::with_config(app(), |c| c.views_path = views.path().to_path_buf()).await;
    let id = match app.db().dialect() {
        renox::db::Dialect::Postgres => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        _ => "INTEGER PRIMARY KEY",
    };
    for statement in [
        format!("CREATE TABLE stores (id {id}, name TEXT NOT NULL)"),
        format!(
            "CREATE TABLE transfers (id {id}, from_store_id BIGINT NOT NULL, \
             to_store_id BIGINT NOT NULL, note TEXT NOT NULL)"
        ),
        "INSERT INTO stores (name) VALUES ('north'), ('south'), ('east')".to_owned(),
        "INSERT INTO transfers (from_store_id, to_store_id, note) VALUES \
         (1, 3, 'north-east'), (3, 2, 'east-south'), (3, 3, 'east-east')"
            .to_owned(),
    ] {
        renox::db::sql(statement).execute(app.db()).await.unwrap();
    }
    let db = app.db();
    permissions::define_role(db, "manager", &["orders.refund", "transfers.view"])
        .await
        .unwrap();
    permissions::define_role(db, "clerk", &["orders.view"])
        .await
        .unwrap();
    (app, views)
}

async fn user(app: &TestApp, email: &str) -> User {
    User::register(app.db(), "U", email, "password123")
        .await
        .unwrap()
}

fn store(id: i64) -> Scope {
    Scope::of_id::<Store>(id)
}

#[renox::test]
async fn scoped_roles_count_only_in_their_scope() {
    let (app, _views) = boot().await;
    let db = app.db();
    let ana = user(&app, "ana@example.com").await;
    let north = Store::find(db, 1).await.unwrap().unwrap();
    ana.assign_role_in(db, "manager", &Scope::of(&north))
        .await
        .unwrap();
    ana.assign_role_in(db, "clerk", &store(2)).await.unwrap();
    app.acting_as(&ana);

    // No scope picked: only global roles count, and there are none.
    app.get("/refund").await.assert_forbidden();
    app.get("/manage").await.assert_forbidden();
    app.get("/me").await.assert_see(
        "roles= manager=false refund=false allows=false in1=true in2=false scopes=[1] user_in2=false",
    );

    // Store 1: manager there.
    let in_store = |id: &'static str| app.request().header("x-store", id);
    in_store("1").get("/refund").await.assert_ok();
    in_store("1").get("/manage").await.assert_see("managing");
    in_store("1")
        .get("/me")
        .await
        .assert_see("roles=manager manager=true refund=true allows=true in1=true in2=false");
    in_store("1")
        .get("/page")
        .await
        .assert_see("can-refund roles=manager");

    // Store 2: a clerk, who may not refund.
    in_store("2").get("/refund").await.assert_forbidden();
    in_store("2").get("/manage").await.assert_forbidden();
    in_store("2")
        .get("/me")
        .await
        .assert_see("roles=clerk manager=false refund=false");
    in_store("2").get("/page").await.assert_see(" roles=clerk");
    in_store("3").get("/refund").await.assert_forbidden();

    // A global role counts in every store, and makes `scopes_with` All.
    let bo = user(&app, "bo@example.com").await;
    bo.assign_role(db, "manager").await.unwrap();
    app.acting_as(&bo);
    app.get("/refund").await.assert_ok();
    in_store("3").get("/refund").await.assert_ok();
    app.get("/me").await.assert_see(
        "roles=manager manager=true refund=true allows=true in1=true in2=true scopes=all",
    );

    // The async readers follow the same rule (no scope here: global only).
    assert!(ana.roles(db).await.unwrap().is_empty());
    assert_eq!(bo.roles(db).await.unwrap(), ["manager"]);
    assert_eq!(
        bo.permissions(db).await.unwrap(),
        ["orders.refund", "transfers.view"]
    );
}

#[renox::test]
async fn scopes_with_narrows_a_default_scope() {
    let (app, _views) = boot().await;
    let db = app.db();
    let ana = user(&app, "ana@example.com").await;
    app.acting_as(&ana);
    // No role at all: no rows (fails closed).
    assert_eq!(app.get("/transfers").await.text(), "");

    // Manager of store 2: transfers from or to store 2.
    ana.assign_role_in(db, "manager", &store(2)).await.unwrap();
    assert_eq!(app.get("/transfers").await.text(), "east-south");
    // And of store 1: both stores' transfers, whatever the active scope.
    ana.assign_role_in(db, "manager", &store(1)).await.unwrap();
    assert_eq!(app.get("/transfers").await.text(), "north-east,east-south");
    // A clerk role in store 3 doesn't grant `transfers.view`.
    ana.assign_role_in(db, "clerk", &store(3)).await.unwrap();
    assert_eq!(app.get("/transfers").await.text(), "north-east,east-south");
    // A global manager sees everything.
    ana.assign_role(db, "manager").await.unwrap();
    assert_eq!(
        app.get("/transfers").await.text(),
        "north-east,east-south,east-east"
    );

    // Outside a request there is no user: nothing.
    assert_eq!(
        permissions::scopes_with::<Store>("transfers.view"),
        Scopes::Only(vec![])
    );
    assert!(Scopes::<i64>::Only(vec![]).is_empty());
    assert!(Scopes::<i64>::All.contains(&9));
    assert!(!Scopes::Only(vec![1_i64]).contains(&9));
}

#[renox::test]
async fn assignments_follow_their_dates() {
    let (app, _views) = boot().await;
    let db = app.db();
    let ana = user(&app, "ana@example.com").await;
    let now = renox::db::now();
    let from = now + renox::chrono::Duration::days(1);
    let until = now + renox::chrono::Duration::days(3);
    ana.assign_role_in(db, "manager", &store(1))
        .from(from)
        .until(until)
        .await
        .unwrap();
    // A global role for a week.
    ana.assign_role_in(db, "clerk", &Scope::global())
        .until(now + renox::chrono::Duration::days(7))
        .await
        .unwrap();
    assert!(
        ana.assign_role_in(db, "manager", &store(2))
            .from(until)
            .until(from)
            .await
            .is_err(),
        "an end before the start is refused"
    );
    assert!(
        ana.assign_role_in(db, "ghost", &store(1)).await.is_err(),
        "roles must exist"
    );
    let refund = || app.request().header("x-store", "1").get("/refund");

    app.acting_as(&ana);
    refund().await.assert_forbidden(); // not started yet
    app.get("/me").await.assert_see("roles=clerk ");

    app.travel(2 * DAY);
    app.acting_as(&ana);
    refund().await.assert_ok();
    let list = app
        .at_travelled_time(permissions::users_with_role_in(db, "manager", &store(1)))
        .await
        .unwrap();
    assert_eq!(list.iter().map(|u| u.id).collect::<Vec<_>>(), [ana.id]);

    app.travel(2 * DAY); // day 4: ended
    app.acting_as(&ana);
    refund().await.assert_forbidden();
    app.get("/me").await.assert_see("roles=clerk ");
    assert!(
        app.at_travelled_time(permissions::users_with_role_in(db, "manager", &store(1)))
            .await
            .unwrap()
            .is_empty()
    );
    // Ended assignments are still listed until pruned.
    let assignments = ana.assignments(db).await.unwrap();
    assert_eq!(assignments.len(), 2);
    let manager: &Assignment = assignments.iter().find(|a| a.role == "manager").unwrap();
    assert_eq!(manager.scope, store(1));
    assert_eq!(manager.starts_at, Some(from));
    assert_eq!(manager.ends_at, Some(until));
    assert!(!manager.is_active_at(until));
    assert!(manager.is_active_at(from));

    app.travel(5 * DAY); // day 9: the global clerk role ended too
    app.acting_as(&ana);
    app.get("/me").await.assert_see("roles= ");
    // Pruning keeps assignments that ended less than `age` ago.
    let pruned = app
        .at_travelled_time(permissions::prune_ended_assignments(db, 3 * DAY))
        .await
        .unwrap();
    assert_eq!(pruned, 1, "only the store role ended more than 3 days ago");
    app.at_travelled_time(app.kernel().call("permissions:prune", ["--days", "0"]))
        .await
        .unwrap();
    assert!(ana.assignments(db).await.unwrap().is_empty());
}

#[renox::test]
async fn scoped_assignments_are_managed_apart_from_global_ones() {
    let (app, _views) = boot().await;
    let db = app.db();
    let ana = user(&app, "ana@example.com").await;
    let bo = user(&app, "bo@example.com").await;
    ana.assign_role(db, "clerk").await.unwrap();
    ana.assign_role_in(db, "manager", &store(1)).await.unwrap();
    ana.assign_role_in(db, "manager", &store(1)).await.unwrap(); // twice is fine
    ana.assign_role_in(db, "manager", &store(2)).await.unwrap();
    bo.assign_role(db, "manager").await.unwrap();

    let roles = |list: Vec<Assignment>| -> Vec<String> {
        list.into_iter()
            .map(|a| format!("{}@{}", a.role, a.scope))
            .collect()
    };
    assert_eq!(
        roles(ana.assignments(db).await.unwrap()),
        ["clerk@global", "manager@stores:1", "manager@stores:2"]
    );
    // Global managers count in every store; `users_with_role` is global only.
    let ids = |users: Vec<User>| users.into_iter().map(|u| u.id).collect::<Vec<_>>();
    assert_eq!(
        ids(permissions::users_with_role_in(db, "manager", &store(1))
            .await
            .unwrap()),
        [ana.id, bo.id]
    );
    assert_eq!(
        ids(permissions::users_with_role(db, "manager").await.unwrap()),
        [bo.id]
    );

    // The global calls leave scoped roles alone, and the other way round.
    ana.sync_roles(db, &[]).await.unwrap();
    ana.remove_role(db, "manager").await.unwrap();
    assert_eq!(
        roles(ana.assignments(db).await.unwrap()),
        ["manager@stores:1", "manager@stores:2"]
    );
    ana.sync_roles_in(db, &["clerk"], &store(2)).await.unwrap();
    ana.remove_role_in(db, "manager", &store(1)).await.unwrap();
    assert_eq!(
        roles(ana.assignments(db).await.unwrap()),
        ["clerk@stores:2"]
    );
    // Deleting a role takes its assignments with it.
    permissions::delete_role(db, "clerk").await.unwrap();
    assert!(ana.assignments(db).await.unwrap().is_empty());

    // Scopes name records stably: the model's table and its key.
    let scope = store(7);
    assert_eq!((scope.kind(), scope.id()), ("stores", "7"));
    assert_eq!(scope.key::<Store>(), Some(7));
    assert_eq!(scope.key::<Transfer>(), None);
    assert_eq!(Scope::new("stores", 7), scope);
    assert!(Scope::global().is_global() && !scope.is_global());
    assert_eq!(permissions::active_scope(), None);
}

/// Runs a migration file's statements one by one (they hold no `;` inside).
async fn run_script(db: &Db, script: &str) {
    for statement in script.split(';') {
        let code: String = statement
            .lines()
            .filter(|line| !line.trim_start().starts_with("--"))
            .collect::<Vec<_>>()
            .join("\n");
        if !code.trim().is_empty() {
            renox::db::sql(code).execute(db).await.unwrap();
        }
    }
}

#[renox::test]
async fn the_scope_migration_keeps_global_roles_and_rolls_back() {
    let (app, _views) = boot().await;
    let db = app.db();
    let ana = user(&app, "ana@example.com").await;
    ana.assign_role(db, "manager").await.unwrap();
    ana.assign_role_in(db, "clerk", &store(1)).await.unwrap();
    let migration = &Permissions.migrations()[1];
    assert_eq!(migration.name(), "00010101000510_add_scope_to_role_user");
    let count = || async {
        renox::db::sql("SELECT COUNT(*) FROM role_user")
            .scalar::<i64>(db)
            .await
            .unwrap()
    };

    // Down: scoped rows go, global ones stay, and so do the old columns only.
    run_script(db, migration.down_for(db.dialect()).unwrap()).await;
    assert_eq!(count().await, 1);
    assert!(
        renox::db::sql("SELECT scope_type FROM role_user")
            .execute(db)
            .await
            .is_err()
    );

    // Up again: the old row is a global assignment, with no dates.
    run_script(db, migration.up_for(db.dialect())).await;
    assert_eq!(
        ana.assignments(db)
            .await
            .unwrap()
            .into_iter()
            .map(|a| (a.role, a.scope, a.starts_at, a.ends_at))
            .collect::<Vec<_>>(),
        [("manager".to_owned(), Scope::global(), None, None)]
    );
    // (role, user, global) stays unique: empty strings, not NULLs.
    let duplicate = renox::db::sql(
        "INSERT INTO role_user (role_id, user_id) SELECT role_id, user_id FROM role_user",
    )
    .execute(db)
    .await;
    assert!(duplicate.is_err(), "a second global row is refused");
    ana.assign_role_in(db, "manager", &store(1)).await.unwrap();
    ana.assign_role_in(db, "manager", &store(1)).await.unwrap();
    assert_eq!(count().await, 2);
}
