//! Full-text search (#154): `#[model(search = …)]`, `renox::db::search`,
//! `Query::search`, kept in sync by the database, and the grid's search
//! box; on SQLite (FTS5) and, with TEST_DATABASE_URL, PostgreSQL (tsvector).

use renox::db::{Dialect, Migration, search};
use renox::grid::{Column, Grid, GridRequest};
use renox::prelude::*;
use renox::testing::TestApp;

const POSTS: Migration = Migration::new("20300101000000_posts", "", Some("DROP TABLE posts"))
    .sqlite(
        "CREATE TABLE posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL,
             body TEXT, author_id INTEGER NOT NULL DEFAULT 0, deleted_at TEXT)",
        None,
    )
    .postgres(
        "CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL,
             body TEXT, author_id BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMPTZ)",
        None,
    );

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "posts", search = "title, body", soft_deletes)]
struct Post {
    id: i64,
    title: String,
    body: Option<String>,
    author_id: i64,
    deleted_at: Option<DateTime>,
}

/// The same table, seen through a default scope (author 1's posts).
#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(
    table = "posts",
    search = "title, body",
    default_scope = "first_author"
)]
struct ScopedPost {
    id: i64,
    title: String,
    body: Option<String>,
    author_id: i64,
    deleted_at: Option<DateTime>,
}

fn first_author(query: renox::db::Query<ScopedPost>) -> renox::db::Query<ScopedPost> {
    query.where_eq("author_id", 1)
}

/// Not searchable.
#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "posts")]
struct PlainPost {
    id: i64,
    title: String,
}

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "posts", search = "body", search_language = "simple")]
struct SimplePost {
    id: i64,
    body: Option<String>,
}

async fn app() -> TestApp {
    let app = TestApp::new(App::new().migrations(&[
        POSTS,
        search::migration::<Post>("20300101000001_search_posts"),
    ]))
    .await;
    for (title, body, author) in [
        ("Roasting coffee at home", "Beans, heat and patience.", 1),
        (
            "Brewing tea",
            "Green tea wants cooler water than coffee.",
            1,
        ),
        ("Kitchen tools", "A grinder, a kettle and a scale.", 2),
        ("Café culture", "Espresso bars across the city.", 2),
    ] {
        Post {
            title: title.into(),
            body: Some(body.into()),
            author_id: author,
            ..Default::default()
        }
        .save(app.db())
        .await
        .unwrap();
    }
    app
}

fn titles(posts: &[Post]) -> Vec<&str> {
    posts.iter().map(|p| p.title.as_str()).collect()
}

#[renox::test]
async fn search_ranks_matches_and_combines_with_filters() {
    let app = app().await;
    let db = app.db();

    // A title match ranks above a body match.
    let found = Post::search("coffee").get(db).await.unwrap();
    assert_eq!(titles(&found), ["Roasting coffee at home", "Brewing tea"]);

    // Every word must match; prefixes and other word forms count; case doesn't.
    assert_eq!(
        titles(&Post::search("TEA cool").get(db).await.unwrap()),
        ["Brewing tea"]
    );
    assert_eq!(
        titles(&Post::search("grind").get(db).await.unwrap()),
        ["Kitchen tools"]
    );
    assert_eq!(
        titles(&Post::search("roasted").get(db).await.unwrap()),
        ["Roasting coffee at home"]
    );
    assert_eq!(
        titles(&Post::search("café").get(db).await.unwrap()),
        ["Café culture"]
    );
    if db.dialect() == Dialect::Sqlite {
        // SQLite also ignores accents (PostgreSQL needs `unaccent` for that).
        assert_eq!(
            titles(&Post::search("cafe").get(db).await.unwrap()),
            ["Café culture"]
        );
    }
    assert!(
        Post::search("coffee kettle")
            .get(db)
            .await
            .unwrap()
            .is_empty()
    );

    // With other filters, counts and pages.
    let by_two = Post::search("a").where_eq("author_id", 2).count(db).await;
    assert!(by_two.is_ok());
    let page = Post::search("coffee").paginate(db, 1, 1).await.unwrap();
    assert_eq!((page.total, page.items.len()), (2, 1));
    assert_eq!(page.items[0].title, "Roasting coffee at home");
    let page2 = Post::search("coffee").paginate(db, 2, 1).await.unwrap();
    assert_eq!(page2.items[0].title, "Brewing tea");
    let filtered = Post::query()
        .where_search("coffee")
        .where_eq("author_id", 1)
        .order_by_desc("id")
        .get(db)
        .await
        .unwrap();
    assert_eq!(
        titles(&filtered),
        ["Brewing tea", "Roasting coffee at home"]
    );
    let first = Post::search("coffee").first(db).await.unwrap().unwrap();
    assert_eq!(first.title, "Roasting coffee at home");
    let plucked: Vec<String> = Post::search("coffee").pluck(db, "title").await.unwrap();
    assert_eq!(plucked, ["Roasting coffee at home", "Brewing tea"]);

    // Default scopes apply.
    let scoped = ScopedPost::search("espresso coffee").get(db).await.unwrap();
    assert!(scoped.is_empty());
    assert_eq!(ScopedPost::search("coffee").count(db).await.unwrap(), 2);

    // Bulk updates and deletes through the search.
    let changed = Post::query()
        .where_search("kettle")
        .update(db, &[("author_id", &3)])
        .await
        .unwrap();
    assert_eq!(changed, 1);
}

#[renox::test]
async fn user_input_never_breaks_a_search() {
    let app = app().await;
    let db = app.db();
    for input in [
        "\"",
        "'",
        "*",
        "coffee*",
        "coffee OR tea",
        "NEAR(coffee tea)",
        "-coffee",
        "title:coffee",
        "coffee & tea",
        "!coffee",
        "\\",
        "coffee'); DROP TABLE posts; --",
        "a:* | b",
        "(",
        "^tea",
        "AND",
        "NOT",
        "café's",
        "東京",
    ] {
        let result = Post::search(input).get(db).await;
        assert!(result.is_ok(), "{input:?}: {result:?}");
    }
    // Operators are words like any other: "NEAR" must appear too.
    assert!(
        Post::search("coffee NEAR")
            .get(db)
            .await
            .unwrap()
            .is_empty()
    );
    assert_eq!(Post::search("-coffee").count(db).await.unwrap(), 2);
    assert_eq!(Post::search("coffee'); DROP").count(db).await.unwrap(), 0);
    // No words: no filter.
    assert_eq!(Post::search("  ...  ").count(db).await.unwrap(), 4);
    assert_eq!(Post::search("").count(db).await.unwrap(), 4);
    app.assert_database_count("posts", 4).await;
}

#[renox::test]
async fn the_index_follows_every_write() {
    let app = app().await;
    let db = app.db();

    // save: insert, then change the title.
    let mut post = Post::create(
        db,
        Post {
            title: "Sourdough starter".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    assert_eq!(Post::search("sourdough").count(db).await.unwrap(), 1);
    post.title = "Rye bread".into();
    post.save(db).await.unwrap();
    assert_eq!(Post::search("sourdough").count(db).await.unwrap(), 0);
    assert_eq!(Post::search("rye").count(db).await.unwrap(), 1);

    // Bulk writes skip model hooks, not the index.
    Post::where_eq("id", post.id)
        .update(db, &[("body", &"Caraway seeds")])
        .await
        .unwrap();
    assert_eq!(Post::search("caraway").count(db).await.unwrap(), 1);
    Post::insert_many(
        db,
        vec![Post {
            title: "Matcha latte".into(),
            ..Default::default()
        }],
    )
    .await
    .unwrap();
    assert_eq!(Post::search("matcha").count(db).await.unwrap(), 1);
    renox::db::sql("INSERT INTO posts (title) VALUES (?)")
        .bind("Oolong notes")
        .execute(db)
        .await
        .unwrap();
    assert_eq!(Post::search("oolong").count(db).await.unwrap(), 1);

    // Soft deletes: hidden like everywhere else, back with with_trashed.
    post.delete(db).await.unwrap();
    assert_eq!(Post::search("rye").count(db).await.unwrap(), 0);
    assert_eq!(
        Post::search("rye").with_trashed().count(db).await.unwrap(),
        1
    );
    assert_eq!(
        Post::search("rye").only_trashed().count(db).await.unwrap(),
        1
    );
    post.force_delete(db).await.unwrap();
    assert_eq!(
        Post::search("rye").with_trashed().count(db).await.unwrap(),
        0
    );
    Post::query()
        .where_search("matcha")
        .force_delete(db)
        .await
        .unwrap();
    assert_eq!(
        Post::search("matcha")
            .with_trashed()
            .count(db)
            .await
            .unwrap(),
        0
    );
    assert_eq!(Post::search("coffee").count(db).await.unwrap(), 2);

    // In a transaction.
    let mut tx = db.begin().await.unwrap();
    Post::create(
        &mut tx,
        Post {
            title: "Cold brew".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    assert_eq!(Post::search("cold brew").count(&mut tx).await.unwrap(), 1);
    tx.rollback().await.unwrap();
    assert_eq!(Post::search("cold brew").count(db).await.unwrap(), 0);

    // rebuild refills an index emptied behind its back (SQLite; a no-op on
    // PostgreSQL, whose column is always current).
    if db.dialect() == Dialect::Sqlite {
        renox::db::sql("INSERT INTO posts_search (posts_search) VALUES ('delete-all')")
            .execute(db)
            .await
            .unwrap();
        assert_eq!(Post::search("coffee").count(db).await.unwrap(), 0);
    }
    search::rebuild::<Post>(db).await.unwrap();
    assert_eq!(Post::search("coffee").count(db).await.unwrap(), 2);
}

#[renox::test]
async fn unsearchable_models_and_rollbacks_are_errors() {
    let app = app().await;
    let db = app.db();
    let err = PlainPost::search("coffee").get(db).await.unwrap_err();
    assert!(format!("{err:?}").contains("add #[model(search"), "{err:?}");
    assert!(search::rebuild::<PlainPost>(db).await.is_err());
    assert!(
        PlainPost::query()
            .order_by_relevance("x")
            .count(db)
            .await
            .is_err()
    );

    // Rolling the migration back removes the index; migrating again
    // restores it, with the rows already there.
    app.kernel().rollback(1).await.unwrap();
    app.kernel().migrate().await.unwrap();
    // (Both migrations ran in one batch, so the table came back empty.)
    Post::create(
        db,
        Post {
            title: "Iced coffee".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    assert_eq!(Post::search("iced").count(db).await.unwrap(), 1);

    // A second migration under a new name replaces the index and fills it.
    let again = search::migration::<Post>("20300101000002_search_posts_again");
    let app2 = TestApp::new(App::new().migrations(&[
        POSTS,
        search::migration::<Post>("20300101000001_search_posts"),
        again,
    ]))
    .await;
    Post::create(
        app2.db(),
        Post {
            title: "Iced tea".into(),
            ..Default::default()
        },
    )
    .await
    .unwrap();
    assert_eq!(Post::search("iced").count(app2.db()).await.unwrap(), 1);
    assert!(
        app2.kernel().fresh().await.is_ok(),
        "migrate:fresh drops the index"
    );
    assert_eq!(Post::search("iced").count(app2.db()).await.unwrap(), 0);
}

#[renox::test]
async fn the_language_decides_stemming() {
    let english = search::migration::<Post>("x");
    let simple = search::migration::<SimplePost>("y");
    assert!(english.up_for(Dialect::Sqlite).contains("porter unicode61"));
    assert!(!simple.up_for(Dialect::Sqlite).contains("porter"));
    assert!(
        english
            .up_for(Dialect::Postgres)
            .contains("'english'::regconfig")
    );
    assert!(
        simple
            .up_for(Dialect::Postgres)
            .contains("'simple'::regconfig")
    );
    assert!(
        english
            .down_for(Dialect::Postgres)
            .unwrap()
            .contains("DROP COLUMN")
    );
    assert!(
        english
            .down_for(Dialect::Sqlite)
            .unwrap()
            .contains("DROP TABLE IF EXISTS \"posts_search\"")
    );

    let app = TestApp::new(App::new().migrations(&[
        POSTS,
        search::migration::<SimplePost>("20300101000001_search_posts"),
    ]))
    .await;
    let db = app.db();
    renox::db::sql("INSERT INTO posts (title, body) VALUES ('a', 'roasting beans')")
        .execute(db)
        .await
        .unwrap();
    // Prefixes still match, other word forms don't.
    assert_eq!(SimplePost::search("roast").count(db).await.unwrap(), 1);
    assert_eq!(SimplePost::search("roasted").count(db).await.unwrap(), 0);
}

#[renox::test]
async fn the_grid_search_box_uses_the_index() {
    let app = app().await;
    let db = app.db();
    let grid = || {
        Grid::new("posts")
            .column(Column::text("title", "Title").searchable())
            .column(Column::number("author_id", "Author"))
            .sort_by("-id")
    };
    // The body isn't a grid column, but it is in the index.
    let request = GridRequest::new(db, "/posts", &[("search", "kettle")]);
    let page = grid().page(Post::query(), &request).await.unwrap();
    assert_eq!(titles(page.items()), ["Kitchen tools"]);
    // Best match first while the user hasn't sorted…
    let request = GridRequest::new(db, "/posts", &[("search", "coffee")]);
    let page = grid().page(Post::query(), &request).await.unwrap();
    assert_eq!(
        titles(page.items()),
        ["Roasting coffee at home", "Brewing tea"]
    );
    // …the user's sort once they have.
    let request = GridRequest::new(db, "/posts", &[("search", "coffee"), ("sort", "-id")]);
    let page = grid().page(Post::query(), &request).await.unwrap();
    assert_eq!(
        titles(page.items()),
        ["Brewing tea", "Roasting coffee at home"]
    );
    // Punctuation only searches nothing away.
    let request = GridRequest::new(db, "/posts", &[("search", "!!")]);
    assert_eq!(
        grid().page(Post::query(), &request).await.unwrap().total(),
        4
    );

    // A searchable column outside the index is still matched as text:
    // every word in the index or in that column.
    let mixed = grid().column(Column::number("id", "Id").searchable());
    let request = GridRequest::new(db, "/posts", &[("search", "tea 2")]);
    let page = mixed.page(Post::query(), &request).await.unwrap();
    assert_eq!(titles(page.items()), ["Brewing tea"]);
}

const RECIPES: Migration = Migration::new("20300101000010_recipes", "", Some("DROP TABLE recipes"))
    .sqlite(
        "CREATE TABLE recipes (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL,
             summary TEXT NOT NULL, steps TEXT NOT NULL)",
        None,
    )
    .postgres(
        "CREATE TABLE recipes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             title TEXT NOT NULL, summary TEXT NOT NULL, steps TEXT NOT NULL)",
        None,
    );

/// Three searched columns: the third gets the third weight (C on
/// PostgreSQL), below the first two.
#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "recipes", search = "title, summary, steps")]
struct Recipe {
    id: i64,
    title: String,
    summary: String,
    steps: String,
}

#[renox::test]
async fn a_third_searched_column_ranks_below_the_first_two() {
    let app = TestApp::new(App::new().migrations(&[
        RECIPES,
        search::migration::<Recipe>("20300101000011_search_recipes"),
    ]))
    .await;
    let db = app.db();
    for (title, summary, steps) in [
        (
            "Bread",
            "A plain loaf.",
            "Knead the dough, then bake with garlic.",
        ),
        ("Garlic butter", "For toast.", "Mix and chill."),
        ("Soup", "Garlic and onion soup.", "Simmer."),
    ] {
        Recipe {
            title: title.into(),
            summary: summary.into(),
            steps: steps.into(),
            ..Default::default()
        }
        .save(db)
        .await
        .unwrap();
    }
    let found: Vec<String> = Recipe::query()
        .search("garlic")
        .order_by_relevance("garlic")
        .get(db)
        .await
        .unwrap()
        .into_iter()
        .map(|r| r.title)
        .collect();
    assert_eq!(found, ["Garlic butter", "Soup", "Bread"]);
    search::rebuild::<Recipe>(db).await.unwrap();
    assert_eq!(Recipe::search("knead").count(db).await.unwrap(), 1);
}
