//! Typed columns (`Col`, `Condition`, `Query::where_`) against the string API.

use renox::db::{Col, Migration};
use renox::prelude::*;
use renox::testing::TestApp;

const SCHEMA: Migration = Migration::new("20300101000000_typed", "", None)
    .sqlite("CREATE TABLE typed_products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, price INTEGER NOT NULL, note TEXT);", None)
    .postgres("CREATE TABLE typed_products (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, price BIGINT NOT NULL, note TEXT);", None);

#[derive(Model, serde::Serialize, Default, Debug, Clone)]
#[model(table = "typed_products")]
struct Product {
    id: i64,
    name: String,
    price: i64,
    note: Option<String>,
}

impl Product {
    const ID: Col<Product, i64> = Col::new("id");
    const NAME: Col<Product, String> = Col::new("name");
    const PRICE: Col<Product, i64> = Col::new("price");
    const NOTE: Col<Product, Option<String>> = Col::new("note");
}

async fn seed() -> TestApp {
    let app = TestApp::new(App::new().migrations(&[SCHEMA])).await;
    for (name, price, note) in [
        ("Apple", 10_000, Some("x")),
        ("Banana", 20_000, None),
        ("Cherry", 30_000, Some("y")),
        ("Date", 1, None),
    ] {
        Product::create(
            app.db(),
            Product {
                name: name.into(),
                price,
                note: note.map(Into::into),
                ..Default::default()
            },
        )
        .await
        .unwrap();
    }
    app
}

fn names(rows: &[Product]) -> Vec<&str> {
    rows.iter().map(|p| p.name.as_str()).collect()
}

#[renox::test]
async fn comparisons_match_the_string_api() {
    let app = seed().await;
    let db = app.db();
    let typed = |q: renox::db::Query<Product>| q.order_by("id");

    let got = typed(Product::query().where_(Product::PRICE.lt(20_000)))
        .get(db)
        .await
        .unwrap();
    let want = typed(Product::query().where_op("price", "<", 20_000))
        .get(db)
        .await
        .unwrap();
    assert_eq!(names(&got), names(&want));
    assert_eq!(names(&got), ["Apple", "Date"]);

    for (cond, op, value) in [
        (Product::PRICE.eq(20_000), "=", 20_000),
        (Product::PRICE.ne(20_000), "!=", 20_000),
        (Product::PRICE.lte(20_000), "<=", 20_000),
        (Product::PRICE.gt(20_000), ">", 20_000),
        (Product::PRICE.gte(20_000), ">=", 20_000),
    ] {
        let got = typed(Product::query().where_(cond)).get(db).await.unwrap();
        let want = typed(Product::query().where_op("price", op, value))
            .get(db)
            .await
            .unwrap();
        assert_eq!(names(&got), names(&want), "{op}");
    }
}

#[renox::test]
async fn optional_columns_take_the_inner_type() {
    let app = seed().await;
    let db = app.db();
    let got = Product::query()
        .where_(Product::NOTE.eq("x"))
        .get(db)
        .await
        .unwrap();
    assert_eq!(names(&got), ["Apple"]);
    let got = Product::query()
        .where_(Product::NOTE.is_null())
        .order_by("id")
        .get(db)
        .await
        .unwrap();
    assert_eq!(names(&got), ["Banana", "Date"]);
    let got = Product::query()
        .where_(Product::NOTE.is_not_null())
        .order_by("id")
        .get(db)
        .await
        .unwrap();
    assert_eq!(names(&got), ["Apple", "Cherry"]);
}

#[renox::test]
async fn like_and_in() {
    let app = seed().await;
    let db = app.db();
    let got = Product::query()
        .where_(Product::NAME.like("%A%"))
        .order_by("id")
        .get(db)
        .await
        .unwrap();
    let want = Product::query()
        .where_like("name", "%A%")
        .order_by("id")
        .get(db)
        .await
        .unwrap();
    assert_eq!(names(&got), names(&want));
    assert_eq!(names(&got), ["Apple", "Banana", "Date"]);

    let got = Product::query()
        .where_(Product::ID.is_in([1, 2]))
        .order_by("id")
        .get(db)
        .await
        .unwrap();
    assert_eq!(names(&got), ["Apple", "Banana"]);
    let none = Product::query()
        .where_(Product::ID.is_in(Vec::<i64>::new()))
        .get(db)
        .await
        .unwrap();
    assert!(none.is_empty());
}

#[renox::test]
async fn an_unknown_column_is_the_usual_error() {
    let app = seed().await;
    let missing: Col<Product, i64> = Col::new("nope");
    let err = Product::query()
        .where_(missing.eq(1))
        .get(app.db())
        .await
        .unwrap_err();
    assert!(err.to_string().contains("has no column"), "{err}");
}
