//! Every endpoint of the JSON API, explained: what `/about/api` shows and
//! what `tests/api.rs` checks against the app's routes (every `/api/v1`
//! route has an entry here, and every entry a route), like the "About this
//! page" walker does for pages.

use serde::Serialize;

/// One endpoint.
#[derive(Debug, Clone, Copy, Serialize)]
pub struct Endpoint {
    /// The route's name.
    pub route: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    /// Who calls it: `kiosk` or `customer`.
    pub client: &'static str,
    /// The token ability it needs.
    pub ability: &'static str,
    pub purpose: &'static str,
    /// What to send (empty for nothing).
    pub request: &'static str,
    /// What comes back.
    pub answer: &'static str,
    /// A `curl` example (`$TOKEN`, `$URL`).
    pub curl: &'static str,
}

/// Every endpoint, kiosk first.
pub const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        route: "api.kiosk.bikes",
        method: "GET",
        path: "/api/v1/kiosk/bikes",
        client: "kiosk",
        ability: "rentals:read",
        purpose: "The bikes free at the kiosk's store for the next hour, cheapest first.",
        request: "",
        answer: "`{\"store_id\", \"data\": [{\"id\", \"frame_number\", \"model\", \"size\", \"hourly_rate\", \"daily_rate\"}]}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/kiosk/bikes",
    },
    Endpoint {
        route: "api.kiosk.rental",
        method: "GET",
        path: "/api/v1/kiosk/rentals/{code}",
        client: "kiosk",
        ability: "rentals:read",
        purpose: "A reservation of the kiosk's store, by the code the customer shows (a `Ulid`). Another store's code answers 404.",
        request: "",
        answer: "`{\"data\": {\"code\", \"status\", \"bike_id\", \"starts_at\", \"due_at\", \"price\", \"deposit\", \"deposit_status\", …}}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/kiosk/rentals/01JA2…",
    },
    Endpoint {
        route: "api.kiosk.checkout",
        method: "POST",
        path: "/api/v1/kiosk/rentals/{code}/checkout",
        client: "kiosk",
        ability: "rentals:checkout",
        purpose: "Hands the reserved bike over: the counter's own rule (the customer verified, the price and an unpaid deposit taken by card).",
        request: "JSON `{\"checklist\": [\"frame\", \"brakes\", …], \"method\": \"card\"}`",
        answer: "The rental, now `active`; 409 when it isn't reserved, 422 when the customer isn't verified.",
        curl: "curl -X POST -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' -d '{\"checklist\":[\"frame\",\"brakes\"],\"method\":\"card\"}' $URL/api/v1/kiosk/rentals/01JA2…/checkout",
    },
    Endpoint {
        route: "api.kiosk.return",
        method: "POST",
        path: "/api/v1/kiosk/rentals/{code}/return",
        client: "kiosk",
        ability: "rentals:return",
        purpose: "Takes the bike back at the kiosk's store: minutes ridden, the late fee and the deposit settled, as at the counter. Damage is reported here too, with photos (multipart).",
        request: "JSON `{\"method\": \"card\"}`, or multipart with `damaged=true`, `damage_note`, `damage_fee`, `photos`",
        answer: "`{\"data\": rental, \"settlement\": {\"fees\", \"kept\", \"refund\", \"due\"}}`; 409 when it isn't out.",
        curl: "curl -X POST -H \"Authorization: Bearer $TOKEN\" -F method=card -F damaged=true -F 'damage_note=Bent rim' -F photos=@rim.jpg $URL/api/v1/kiosk/rentals/01JA2…/return",
    },
    Endpoint {
        route: "api.me",
        method: "GET",
        path: "/api/v1/me",
        client: "customer",
        ability: "read",
        purpose: "Who the token belongs to and what it may do: what an app asks first.",
        request: "",
        answer: "`{\"data\": {\"name\", \"email\", \"verified_for_rentals\", \"abilities\"}}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me",
    },
    Endpoint {
        route: "api.products",
        method: "GET",
        path: "/api/v1/products",
        client: "customer",
        ability: "read",
        purpose: "The catalogue, or what `?q=` finds (the website's full-text search), 20 a page.",
        request: "`?q=helmet&page=2`",
        answer: "`{\"data\": [{\"slug\", \"name\", \"brand\", \"category\", \"price_from\", \"url\"}], \"meta\": {\"page\", \"per_page\", \"total\", \"last_page\"}, \"links\": {\"first\", \"last\", \"prev\", \"next\"}}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" \"$URL/api/v1/products?q=helmet\"",
    },
    Endpoint {
        route: "api.products.show",
        method: "GET",
        path: "/api/v1/products/{slug}",
        client: "customer",
        ability: "read",
        purpose: "A product, its variants and how many of each each store has.",
        request: "",
        answer: "`{\"data\": {\"slug\", \"name\", \"variants\": [{\"sku\", \"size\", \"colour\", \"price\", \"stock\": [{\"store_id\", \"store\", \"available\"}]}]}}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/products/trek-fx-3",
    },
    Endpoint {
        route: "api.me.bikes",
        method: "GET",
        path: "/api/v1/me/bikes",
        client: "customer",
        ability: "read",
        purpose: "The customer's own bikes.",
        request: "",
        answer: "`{\"data\": [{\"id\", \"name\", \"brand\", \"size\", \"frame_number\"}]}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me/bikes",
    },
    Endpoint {
        route: "api.me.work_orders",
        method: "GET",
        path: "/api/v1/me/work-orders",
        client: "customer",
        ability: "read",
        purpose: "The work orders on the customer's bikes, newest first, with their status.",
        request: "`?page=`",
        answer: "A page of `{\"number\", \"bike_id\", \"store_id\", \"source\", \"status\", \"scheduled_for\", \"total\", \"paid\"}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me/work-orders",
    },
    Endpoint {
        route: "api.me.plan",
        method: "GET",
        path: "/api/v1/me/plan",
        client: "customer",
        ability: "read",
        purpose: "The service plans on the customer's bikes, with the next visit.",
        request: "",
        answer: "`{\"data\": [{\"bike_id\", \"plan\", \"status\", \"store_id\", \"next_visit_on\", \"monthly_price\"}]}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me/plan",
    },
    Endpoint {
        route: "api.me.rentals",
        method: "GET",
        path: "/api/v1/me/rentals",
        client: "customer",
        ability: "rent",
        purpose: "The customer's rentals, newest first.",
        request: "`?page=`",
        answer: "A page of rentals (as the kiosk sees them).",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me/rentals",
    },
    Endpoint {
        route: "api.me.rentals.store",
        method: "POST",
        path: "/api/v1/me/rentals",
        client: "customer",
        ability: "rent",
        purpose: "Reserves a bike, with the website's rules: the period, the overlap (checked twice), the ID check.",
        request: "JSON `{\"store\": 1, \"bike\": 12, \"starts_at\": \"2026-10-09T10:00:00\", \"ends_at\": \"2026-10-09T14:00:00\"}` (local times)",
        answer: "201 with the rental and its code; 422 `{\"message\", \"errors\"}` when a rule refuses.",
        curl: "curl -X POST -H \"Authorization: Bearer $TOKEN\" -H 'Content-Type: application/json' -d '{\"store\":1,\"bike\":12,\"starts_at\":\"2026-10-09T10:00:00\",\"ends_at\":\"2026-10-09T14:00:00\"}' $URL/api/v1/me/rentals",
    },
    Endpoint {
        route: "api.me.rentals.destroy",
        method: "DELETE",
        path: "/api/v1/me/rentals/{code}",
        client: "customer",
        ability: "rent",
        purpose: "Cancels a reservation until an hour before it starts (a paid deposit comes back whole).",
        request: "",
        answer: "The rental, `cancelled`; 409 when it's too late.",
        curl: "curl -X DELETE -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me/rentals/01JA2…",
    },
    Endpoint {
        route: "api.me.orders",
        method: "GET",
        path: "/api/v1/me/orders",
        client: "customer",
        ability: "order",
        purpose: "The customer's orders, newest first.",
        request: "`?page=`",
        answer: "A page of `{\"number\", \"status\", \"fulfilment\", \"store_id\", \"total\", \"placed_at\", \"paid_at\"}`",
        curl: "curl -H \"Authorization: Bearer $TOKEN\" $URL/api/v1/me/orders",
    },
];
