-- The books between stores: an entry whenever the store that owns a bike or goods isn't the
-- one that did the work (who owes whom, why, for what), and the monthly settlements.

CREATE TABLE settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_store_id BIGINT NOT NULL REFERENCES stores(id),
    creditor_store_id BIGINT NOT NULL REFERENCES stores(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    amount BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    settled_at TIMESTAMPTZ,
    settled_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX settlements_debtor_store_id_creditor_store_id_period_start_unique ON settlements (debtor_store_id, creditor_store_id, period_start);

CREATE TABLE intercompany_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_store_id BIGINT NOT NULL REFERENCES stores(id),
    creditor_store_id BIGINT NOT NULL REFERENCES stores(id),
    amount BIGINT NOT NULL,
    kind TEXT NOT NULL,
    fee_rate_bp BIGINT,
    source_type TEXT NOT NULL,
    source_id BIGINT NOT NULL,
    settlement_id BIGINT REFERENCES settlements(id) ON DELETE SET NULL,
    booked_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX intercompany_entries_debtor_store_id_creditor_store_id_index ON intercompany_entries (debtor_store_id, creditor_store_id);
CREATE INDEX intercompany_entries_source_type_source_id_index ON intercompany_entries (source_type, source_id);
CREATE INDEX intercompany_entries_settlement_id_index ON intercompany_entries (settlement_id);
CREATE INDEX intercompany_entries_booked_at_index ON intercompany_entries (booked_at);
