-- Store kiosks (#241): a self-service kiosk next to a store's bike racks, acting through
-- its own user (no password anyone knows) and that user's API token, limited to the
-- rental abilities a manager gave it. Revoked kiosks keep their row for the history.

CREATE TABLE kiosks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    token_id BIGINT,
    abilities TEXT NOT NULL DEFAULT '[]',
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX kiosks_store_id_index ON kiosks (store_id);
CREATE UNIQUE INDEX kiosks_user_id_unique ON kiosks (user_id);
