-- Service plans billed as subscriptions (#237): a plan's parts discount; a subscription's
-- billing owner and gateway, its visit counter, a plan change waiting for the next period,
-- a pause, a hold after a failed payment and the day a cancellation takes effect; each visit
-- (made ahead as a work order), and each payment the gateway reported.

ALTER TABLE service_plans ADD COLUMN parts_discount_bp BIGINT NOT NULL DEFAULT 0;

ALTER TABLE plan_subscriptions ADD COLUMN user_id BIGINT;
ALTER TABLE plan_subscriptions ADD COLUMN gateway TEXT NOT NULL DEFAULT '';
ALTER TABLE plan_subscriptions ADD COLUMN visit_seq BIGINT NOT NULL DEFAULT 0;
ALTER TABLE plan_subscriptions ADD COLUMN next_plan_id BIGINT;
ALTER TABLE plan_subscriptions ADD COLUMN swap_on DATE;
ALTER TABLE plan_subscriptions ADD COLUMN paused_at TIMESTAMPTZ;
ALTER TABLE plan_subscriptions ADD COLUMN held_at TIMESTAMPTZ;
ALTER TABLE plan_subscriptions ADD COLUMN ends_on DATE;
CREATE INDEX plan_subscriptions_user_id_index ON plan_subscriptions (user_id);

CREATE TABLE plan_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_subscription_id BIGINT NOT NULL REFERENCES plan_subscriptions(id) ON DELETE CASCADE,
    seq BIGINT NOT NULL,
    due_on DATE NOT NULL,
    work_order_id BIGINT REFERENCES work_orders(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    UNIQUE (plan_subscription_id, seq)
);
CREATE INDEX plan_visits_work_order_id_index ON plan_visits (work_order_id);
CREATE INDEX plan_visits_status_index ON plan_visits (status);

CREATE TABLE plan_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_subscription_id BIGINT NOT NULL REFERENCES plan_subscriptions(id) ON DELETE CASCADE,
    gateway TEXT NOT NULL,
    payment_id TEXT NOT NULL,
    amount BIGINT NOT NULL,
    currency TEXT NOT NULL,
    paid BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    UNIQUE (gateway, payment_id)
);
CREATE INDEX plan_invoices_plan_subscription_id_index ON plan_invoices (plan_subscription_id);
