DROP TABLE IF EXISTS part_fits;
DROP TABLE IF EXISTS product_photos;
DROP TABLE IF EXISTS product_variants;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS categories;
