-- The workshop: customers' bikes, the tasks a mechanic does, and work orders for a
-- customer's bike or a rental bike of the fleet (billed to its owner store).

CREATE TABLE customer_bikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    name TEXT NOT NULL,
    frame_number TEXT,
    order_id BIGINT REFERENCES orders(id),
    bought_on DATE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX customer_bikes_customer_id_index ON customer_bikes (customer_id);

CREATE TABLE service_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    minutes BIGINT NOT NULL,
    price BIGINT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_bike_id BIGINT REFERENCES customer_bikes(id),
    rental_bike_id BIGINT REFERENCES rental_bikes(id),
    store_id BIGINT NOT NULL REFERENCES stores(id),
    mechanic_id BIGINT REFERENCES staff(id),
    source TEXT NOT NULL,
    plan_subscription_id BIGINT,
    billed_store_id BIGINT REFERENCES stores(id),
    scheduled_for TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked',
    labour BIGINT NOT NULL DEFAULT 0,
    parts BIGINT NOT NULL DEFAULT 0,
    total BIGINT NOT NULL DEFAULT 0,
    customer_note TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX work_orders_store_id_status_index ON work_orders (store_id, status);
CREATE INDEX work_orders_customer_bike_id_index ON work_orders (customer_bike_id);
CREATE INDEX work_orders_rental_bike_id_index ON work_orders (rental_bike_id);
CREATE INDEX work_orders_scheduled_for_index ON work_orders (scheduled_for);

CREATE TABLE work_order_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    service_task_id BIGINT NOT NULL REFERENCES service_tasks(id),
    minutes BIGINT NOT NULL,
    price BIGINT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX work_order_tasks_work_order_id_index ON work_order_tasks (work_order_id);
