-- Orders (online and at the counter), their lines with the owner store of the goods sold
-- (consigned goods belong to another store), and payments for orders, rentals and work orders.

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number TEXT NOT NULL UNIQUE,
    customer_id BIGINT REFERENCES customers(id),
    operating_store_id BIGINT NOT NULL REFERENCES stores(id),
    channel TEXT NOT NULL,
    fulfilment TEXT NOT NULL DEFAULT 'pickup',
    status TEXT NOT NULL DEFAULT 'pending',
    subtotal BIGINT NOT NULL DEFAULT 0,
    discount BIGINT NOT NULL DEFAULT 0,
    delivery_fee BIGINT NOT NULL DEFAULT 0,
    total BIGINT NOT NULL DEFAULT 0,
    delivery_address_id BIGINT REFERENCES addresses(id),
    placed_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    served_by BIGINT REFERENCES staff(id),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX orders_operating_store_id_status_index ON orders (operating_store_id, status);
CREATE INDEX orders_customer_id_index ON orders (customer_id);
CREATE INDEX orders_placed_at_index ON orders (placed_at);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    owner_store_id BIGINT NOT NULL REFERENCES stores(id),
    quantity BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    total BIGINT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX order_items_order_id_index ON order_items (order_id);
CREATE INDEX order_items_variant_id_index ON order_items (variant_id);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    payable_type TEXT NOT NULL,
    payable_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    amount BIGINT NOT NULL,
    method TEXT NOT NULL,
    gateway_reference TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    paid_at TIMESTAMPTZ,
    received_by BIGINT REFERENCES staff(id),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX payments_payable_type_payable_id_index ON payments (payable_type, payable_id);
CREATE INDEX payments_store_id_paid_at_index ON payments (store_id, paid_at);
CREATE INDEX payments_customer_id_index ON payments (customer_id);
