-- Saved carts (#234): a logged-in customer's cart, kept between visits and devices.
-- A guest's cart lives in the session; at the first visit after logging in it is
-- merged into this row. `lines` is JSON: [{"variant_id": 7, "quantity": 2}, …].

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    store_id BIGINT REFERENCES stores(id),
    lines JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
