-- Stock, consignment and purchasing (#240): a barcode on variants, what each supplier sells
-- (their price list), the received quantity of consignment lines (partial receipt), who asked
-- for and approved a shipment, a purchase order's note and whether the daily reorder check
-- suggested it, and `stock_overview`: one row per stock level with its variant, product and
-- category, so the stock grid can filter, group and sum them as plain columns.

ALTER TABLE product_variants ADD COLUMN barcode TEXT;

CREATE TABLE supplier_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    cost BIGINT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX supplier_items_supplier_id_variant_id_unique ON supplier_items (supplier_id, variant_id);
CREATE INDEX supplier_items_variant_id_index ON supplier_items (variant_id);

ALTER TABLE consignment_shipment_lines ADD COLUMN received_quantity BIGINT NOT NULL DEFAULT 0;
UPDATE consignment_shipment_lines SET received_quantity = quantity
    WHERE shipment_id IN (SELECT id FROM consignment_shipments WHERE status IN ('received', 'recalled'));
ALTER TABLE consignment_shipments ADD COLUMN requested_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE consignment_shipments ADD COLUMN approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE consignment_shipments ADD COLUMN approved_at TIMESTAMPTZ;

ALTER TABLE purchase_orders ADD COLUMN note TEXT;
ALTER TABLE purchase_orders ADD COLUMN suggested BOOLEAN NOT NULL DEFAULT FALSE;

CREATE VIEW stock_overview AS
SELECT l.id, l.variant_id, l.owner_store_id, l.location_store_id, l.on_hand, l.reserved,
       l.on_hand - l.reserved AS available,
       v.sku, v.size, v.colour, v.cost, v.reorder_level,
       l.on_hand * v.cost AS value_at_cost,
       p.id AS product_id, p.name AS product, c.name AS category, c.kind AS category_kind,
       l.updated_at
FROM stock_levels l
JOIN product_variants v ON v.id = l.variant_id
JOIN products p ON p.id = v.product_id
JOIN categories c ON c.id = p.category_id;
