-- The workshop (#236): a customer bike's brand, size and photo; a work order's booked
-- minutes (the day's capacity), reminders, cancellation and payment; the parts used (taken
-- from stock, or waited for), the mechanic's notes and photos, and extra work proposed to
-- the customer and approved or refused through a signed link.

ALTER TABLE customer_bikes ADD COLUMN brand TEXT;
ALTER TABLE customer_bikes ADD COLUMN size TEXT;
ALTER TABLE customer_bikes ADD COLUMN photo_path TEXT;

ALTER TABLE work_orders ADD COLUMN minutes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE work_orders ADD COLUMN package TEXT;
ALTER TABLE work_orders ADD COLUMN reminded_at TIMESTAMPTZ;
ALTER TABLE work_orders ADD COLUMN cancelled_at TIMESTAMPTZ;
ALTER TABLE work_orders ADD COLUMN paid_at TIMESTAMPTZ;

CREATE TABLE work_order_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    quantity BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    total BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'used',
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX work_order_parts_work_order_id_index ON work_order_parts (work_order_id);

CREATE TABLE work_order_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    staff_id BIGINT REFERENCES staff(id),
    kind TEXT NOT NULL DEFAULT 'note',
    body TEXT,
    photo_path TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX work_order_notes_work_order_id_index ON work_order_notes (work_order_id);

CREATE TABLE extra_work_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    total BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ NOT NULL,
    decided_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES staff(id),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX extra_work_requests_work_order_id_index ON extra_work_requests (work_order_id);
