-- Customers belong to the company, not to a store. Walk-ins have no user account.
-- id_number is sealed with APP_KEY (Encrypted<String>): unreadable in the table.

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address_id BIGINT REFERENCES addresses(id),
    id_number TEXT,
    id_verified_at TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX customers_user_id_index ON customers (user_id);
CREATE INDEX customers_email_index ON customers (email);
