-- The rental fleet (Pagila's inventory) with an owner store and a location store, bikes
-- placed at other stores, and rentals (Pagila's rental) with the store that served them.

CREATE TABLE rental_bikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    owner_store_id BIGINT NOT NULL REFERENCES stores(id),
    location_store_id BIGINT NOT NULL REFERENCES stores(id),
    frame_number TEXT NOT NULL UNIQUE,
    condition TEXT NOT NULL DEFAULT 'good',
    status TEXT NOT NULL DEFAULT 'available',
    hourly_rate BIGINT NOT NULL,
    daily_rate BIGINT NOT NULL,
    deposit BIGINT NOT NULL,
    asset_value BIGINT NOT NULL DEFAULT 0,
    ridden_hours BIGINT NOT NULL DEFAULT 0,
    purchased_on DATE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX rental_bikes_location_store_id_status_index ON rental_bikes (location_store_id, status);
CREATE INDEX rental_bikes_owner_store_id_index ON rental_bikes (owner_store_id);

CREATE TABLE bike_placements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_bike_id BIGINT NOT NULL REFERENCES rental_bikes(id) ON DELETE CASCADE,
    from_store_id BIGINT NOT NULL REFERENCES stores(id),
    to_store_id BIGINT NOT NULL REFERENCES stores(id),
    status TEXT NOT NULL DEFAULT 'requested',
    requested_at TIMESTAMPTZ NOT NULL,
    approved_at TIMESTAMPTZ,
    moved_at TIMESTAMPTZ,
    recalled_at TIMESTAMPTZ,
    requested_by BIGINT REFERENCES staff(id),
    approved_by BIGINT REFERENCES staff(id),
    note TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX bike_placements_rental_bike_id_index ON bike_placements (rental_bike_id);
CREATE INDEX bike_placements_to_store_id_status_index ON bike_placements (to_store_id, status);

CREATE TABLE rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_code TEXT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    rental_bike_id BIGINT NOT NULL REFERENCES rental_bikes(id),
    owner_store_id BIGINT NOT NULL REFERENCES stores(id),
    operating_store_id BIGINT NOT NULL REFERENCES stores(id),
    return_store_id BIGINT REFERENCES stores(id),
    rate TEXT NOT NULL DEFAULT 'daily',
    starts_at TIMESTAMPTZ NOT NULL,
    due_at TIMESTAMPTZ NOT NULL,
    picked_up_at TIMESTAMPTZ,
    returned_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'reserved',
    price BIGINT NOT NULL DEFAULT 0,
    deposit BIGINT NOT NULL DEFAULT 0,
    late_fee BIGINT NOT NULL DEFAULT 0,
    damage_fee BIGINT NOT NULL DEFAULT 0,
    served_by BIGINT REFERENCES staff(id),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX rentals_operating_store_id_status_index ON rentals (operating_store_id, status);
CREATE INDEX rentals_customer_id_index ON rentals (customer_id);
CREATE INDEX rentals_rental_bike_id_index ON rentals (rental_bike_id);
CREATE INDEX rentals_due_at_index ON rentals (due_at);
