-- The three stores and the people who work in them. No role column on staff: roles are
-- given per store by the Permissions module (role_user.scope_type = 'stores').

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    address_id BIGINT NOT NULL REFERENCES addresses(id),
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    opening_hours JSONB NOT NULL DEFAULT '[]'::jsonb,
    workshop_minutes_per_day BIGINT NOT NULL DEFAULT 960,
    fee_rate_bp BIGINT NOT NULL DEFAULT 2000,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    home_store_id BIGINT NOT NULL REFERENCES stores(id),
    phone TEXT,
    hired_on DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX staff_home_store_id_index ON staff (home_store_id);

CREATE TABLE staff_help_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_store_id BIGINT NOT NULL REFERENCES stores(id),
    to_store_id BIGINT NOT NULL REFERENCES stores(id),
    staff_id BIGINT NOT NULL REFERENCES staff(id),
    role TEXT NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested',
    requested_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX staff_help_requests_to_store_id_status_index ON staff_help_requests (to_store_id, status);
CREATE INDEX staff_help_requests_staff_id_index ON staff_help_requests (staff_id);

CREATE TABLE staff_help_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    help_request_id BIGINT NOT NULL REFERENCES staff_help_requests(id) ON DELETE CASCADE,
    staff_id BIGINT NOT NULL REFERENCES staff(id),
    store_id BIGINT NOT NULL REFERENCES stores(id),
    worked_on DATE NOT NULL,
    minutes BIGINT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX staff_help_hours_help_request_id_index ON staff_help_hours (help_request_id);
CREATE INDEX staff_help_hours_store_id_worked_on_index ON staff_help_hours (store_id, worked_on);
