-- Service plans (a set of tasks every week, month…), and customers' bikes subscribed to them.

CREATE TABLE service_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    frequency TEXT NOT NULL,
    price BIGINT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE plan_tasks (
    service_plan_id BIGINT NOT NULL REFERENCES service_plans(id) ON DELETE CASCADE,
    service_task_id BIGINT NOT NULL REFERENCES service_tasks(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    PRIMARY KEY (service_plan_id, service_task_id)
);

CREATE TABLE plan_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_bike_id BIGINT NOT NULL REFERENCES customer_bikes(id) ON DELETE CASCADE,
    service_plan_id BIGINT NOT NULL REFERENCES service_plans(id),
    store_id BIGINT NOT NULL REFERENCES stores(id),
    preferred_weekday BIGINT NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'active',
    starts_on DATE NOT NULL,
    next_visit_on DATE,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX plan_subscriptions_store_id_status_index ON plan_subscriptions (store_id, status);
CREATE INDEX plan_subscriptions_customer_bike_id_index ON plan_subscriptions (customer_bike_id);
CREATE INDEX plan_subscriptions_next_visit_on_index ON plan_subscriptions (next_visit_on);
