-- Stock with two store attributes: who owns the goods (owner_store_id, their books) and
-- where they are (location_store_id). stock_movements is the ledger; stock_levels the sums.

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address_id BIGINT REFERENCES addresses(id),
    lead_days BIGINT NOT NULL DEFAULT 7,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE stock_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    owner_store_id BIGINT NOT NULL REFERENCES stores(id),
    location_store_id BIGINT NOT NULL REFERENCES stores(id),
    on_hand BIGINT NOT NULL DEFAULT 0,
    reserved BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX stock_levels_variant_id_owner_store_id_location_store_id_unique ON stock_levels (variant_id, owner_store_id, location_store_id);
CREATE INDEX stock_levels_location_store_id_index ON stock_levels (location_store_id);
CREATE INDEX stock_levels_owner_store_id_index ON stock_levels (owner_store_id);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES suppliers(id),
    store_id BIGINT NOT NULL REFERENCES stores(id),
    status TEXT NOT NULL DEFAULT 'draft',
    ordered_at TIMESTAMPTZ,
    expected_on DATE,
    received_at TIMESTAMPTZ,
    total BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT REFERENCES staff(id),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX purchase_orders_store_id_status_index ON purchase_orders (store_id, status);
CREATE INDEX purchase_orders_supplier_id_index ON purchase_orders (supplier_id);

CREATE TABLE purchase_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    quantity BIGINT NOT NULL,
    received_quantity BIGINT NOT NULL DEFAULT 0,
    unit_cost BIGINT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX purchase_order_lines_purchase_order_id_index ON purchase_order_lines (purchase_order_id);

CREATE TABLE consignment_shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_store_id BIGINT NOT NULL REFERENCES stores(id),
    location_store_id BIGINT NOT NULL REFERENCES stores(id),
    status TEXT NOT NULL DEFAULT 'draft',
    sent_at TIMESTAMPTZ,
    received_at TIMESTAMPTZ,
    recalled_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES staff(id),
    note TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX consignment_shipments_owner_store_id_index ON consignment_shipments (owner_store_id);
CREATE INDEX consignment_shipments_location_store_id_index ON consignment_shipments (location_store_id);

CREATE TABLE consignment_shipment_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES consignment_shipments(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    quantity BIGINT NOT NULL,
    sold_quantity BIGINT NOT NULL DEFAULT 0,
    returned_quantity BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX consignment_shipment_lines_shipment_id_index ON consignment_shipment_lines (shipment_id);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    owner_store_id BIGINT NOT NULL REFERENCES stores(id),
    location_store_id BIGINT NOT NULL REFERENCES stores(id),
    quantity BIGINT NOT NULL,
    reason TEXT NOT NULL,
    reference_type TEXT,
    reference_id BIGINT,
    staff_id BIGINT REFERENCES staff(id),
    note TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX stock_movements_variant_id_index ON stock_movements (variant_id);
CREATE INDEX stock_movements_location_store_id_created_at_index ON stock_movements (location_store_id, created_at);
CREATE INDEX stock_movements_reference_type_reference_id_index ON stock_movements (reference_type, reference_id);
