CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    quantity BIGINT NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL,
    status TEXT NOT NULL,
    tags JSONB NOT NULL,
    extra JSONB,
    opens_at TIME,
    starts_at TIMESTAMP,
    released_on DATE,
    thumbnail BYTEA,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
