CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products (id) ON DELETE CASCADE,
    body TEXT NOT NULL
);
CREATE INDEX notes_product_id ON notes (product_id);
