CREATE TABLE catatan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produk_id BIGINT REFERENCES produk (id) ON DELETE CASCADE,
    isi TEXT NOT NULL
);
CREATE INDEX catatan_produk_id ON catatan (produk_id);
