-- API tokens for a device (a kiosk, a till, a sensor) instead of a user.
-- `device` is the app's own key for the owner, e.g. 'kiosk:3'.
CREATE TABLE device_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device TEXT NOT NULL,
    name TEXT NOT NULL,
    token TEXT NOT NULL UNIQUE,
    abilities TEXT,
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX device_tokens_device ON device_tokens (device);
