//! Turns a list of schema changes into SQL: the writing half of `db:diff`.

use super::quote;
use super::schema_check::kind_fits;
use super::schema_diff::Change;
use super::{ColumnKind, Dialect, ModelColumn};

/// The SQL type of a column kind; `None` for [`ColumnKind::Unknown`].
pub(crate) fn sql_type(kind: ColumnKind, dialect: Dialect) -> Option<&'static str> {
    use ColumnKind as K;
    let pg = dialect == Dialect::Postgres;
    let (lite, postgres) = match kind {
        K::BigInt => ("INTEGER", "BIGINT"),
        K::Int => ("INTEGER", "INTEGER"),
        K::SmallInt => ("INTEGER", "SMALLINT"),
        K::Double => ("REAL", "DOUBLE PRECISION"),
        K::Real => ("REAL", "REAL"),
        K::Text => ("TEXT", "TEXT"),
        K::Blob => ("BLOB", "BYTEA"),
        K::Bool => ("INTEGER", "BOOLEAN"),
        K::DateTime => ("TEXT", "TIMESTAMPTZ"),
        K::NaiveDateTime => ("TEXT", "TIMESTAMP"),
        K::Date => ("TEXT", "DATE"),
        K::Time => ("TEXT", "TIME"),
        K::Json => ("TEXT", "JSONB"),
        K::Uuid => ("BLOB", "UUID"),
        K::Unknown => return None,
    };
    Some(if pg { postgres } else { lite })
}

/// `"name" TYPE [NOT NULL] [DEFAULT x] [REFERENCES "t" ("id")]`; the `id`
/// column is the primary key.
pub(crate) fn column_def(c: &ModelColumn, dialect: Dialect) -> String {
    let name = quote(c.name);
    let ty = sql_type(c.kind, dialect).unwrap_or("TEXT");
    if c.name == "id" {
        return match (c.kind, dialect) {
            (ColumnKind::BigInt | ColumnKind::Int, Dialect::Sqlite) => {
                format!("{name} INTEGER PRIMARY KEY AUTOINCREMENT")
            }
            (ColumnKind::BigInt | ColumnKind::Int, Dialect::Postgres) => {
                format!("{name} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            }
            _ => format!("{name} {ty} PRIMARY KEY"),
        };
    }
    let mut out = format!("{name} {ty}");
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(default) = c.default {
        out.push_str(&format!(" DEFAULT {default}"));
    }
    if let Some(table) = c.references {
        out.push_str(&format!(" REFERENCES {} (\"id\")", quote(table)));
    }
    out
}

fn columns_list(columns: &[String]) -> String {
    columns
        .iter()
        .map(|c| quote(c))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The PostgreSQL `(up, down)` SQL for `changes`: up in order, down in
/// reverse order, every statement ending in `;\n`.
pub(crate) fn postgres(changes: &[Change]) -> (String, String) {
    let d = Dialect::Postgres;
    let mut up = String::new();
    let mut downs: Vec<String> = Vec::new();
    for change in changes {
        let mut down = String::new();
        match change {
            Change::CreateTable { model } => {
                let defs: Vec<String> = model.columns.iter().map(|c| column_def(c, d)).collect();
                up.push_str(&format!(
                    "CREATE TABLE {} (\n    {}\n);\n",
                    quote(model.table),
                    defs.join(",\n    ")
                ));
                down.push_str(&format!("DROP TABLE {};\n", quote(model.table)));
            }
            Change::AddColumn { table, column } => {
                up.push_str(&format!(
                    "ALTER TABLE {} ADD COLUMN {};\n",
                    quote(table),
                    column_def(column, d)
                ));
                down.push_str(&format!(
                    "ALTER TABLE {} DROP COLUMN {};\n",
                    quote(table),
                    quote(column.name)
                ));
            }
            Change::DropColumn { table, old } => {
                up.push_str(&format!(
                    "ALTER TABLE {} DROP COLUMN {};\n",
                    quote(table),
                    quote(&old.name)
                ));
                let mut def = format!("{} {}", quote(&old.name), old.sql_type);
                if old.not_null {
                    def.push_str(" NOT NULL");
                }
                if let Some(default) = &old.default {
                    def.push_str(&format!(" DEFAULT {default}"));
                }
                down.push_str(&format!("ALTER TABLE {} ADD COLUMN {def};\n", quote(table)));
            }
            Change::AlterColumn { table, old, new } => {
                let t = quote(table);
                let c = quote(new.name);
                let new_ty = sql_type(new.kind, d).unwrap_or("TEXT");
                if !kind_fits(d, new.kind, &old.sql_type) {
                    up.push_str(&format!(
                        "ALTER TABLE {t} ALTER COLUMN {c} TYPE {new_ty} USING {c}::{new_ty};\n"
                    ));
                    down.push_str(&format!(
                        "ALTER TABLE {t} ALTER COLUMN {c} TYPE {0} USING {c}::{0};\n",
                        old.sql_type
                    ));
                }
                if new.nullable == old.not_null {
                    let (to, back) = if new.nullable {
                        ("DROP", "SET")
                    } else {
                        ("SET", "DROP")
                    };
                    up.push_str(&format!(
                        "ALTER TABLE {t} ALTER COLUMN {c} {to} NOT NULL;\n"
                    ));
                    down.insert_str(
                        0,
                        &format!("ALTER TABLE {t} ALTER COLUMN {c} {back} NOT NULL;\n"),
                    );
                }
            }
            Change::RenameColumn { table, from, to } => {
                up.push_str(&format!(
                    "ALTER TABLE {} RENAME COLUMN {} TO {};\n",
                    quote(table),
                    quote(from),
                    quote(to)
                ));
                down.push_str(&format!(
                    "ALTER TABLE {} RENAME COLUMN {} TO {};\n",
                    quote(table),
                    quote(to),
                    quote(from)
                ));
            }
            Change::CreateIndex {
                table,
                name,
                columns,
                unique,
            } => {
                up.push_str(&format!(
                    "CREATE {}INDEX {} ON {} ({});\n",
                    if *unique { "UNIQUE " } else { "" },
                    quote(name),
                    quote(table),
                    columns_list(columns)
                ));
                down.push_str(&format!("DROP INDEX {};\n", quote(name)));
            }
            Change::DropIndex { old, .. } => {
                up.push_str(&format!("DROP INDEX {};\n", quote(&old.name)));
                if let Some(sql) = &old.sql {
                    down.push_str(sql.trim_end_matches(';'));
                    down.push_str(";\n");
                }
            }
        }
        downs.push(down);
    }
    downs.reverse();
    (up, downs.concat())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::ModelIndex;
    use crate::db::schema_check::{TableColumn, TableIndex};
    use crate::db::schema_diff::ModelState;

    fn col(name: &'static str, kind: ColumnKind, nullable: bool) -> ModelColumn {
        ModelColumn::new(name, "T", kind, nullable)
    }

    fn old(name: &str, ty: &str, not_null: bool) -> TableColumn {
        TableColumn {
            name: name.into(),
            sql_type: ty.into(),
            not_null,
            default: None,
            primary_key: false,
            identity: false,
        }
    }

    #[test]
    fn types_follow_the_table() {
        assert_eq!(sql_type(ColumnKind::Json, Dialect::Postgres), Some("JSONB"));
        assert_eq!(sql_type(ColumnKind::Json, Dialect::Sqlite), Some("TEXT"));
        assert_eq!(
            sql_type(ColumnKind::SmallInt, Dialect::Postgres),
            Some("SMALLINT")
        );
        assert_eq!(
            sql_type(ColumnKind::Int, Dialect::Postgres),
            Some("INTEGER")
        );
        assert_eq!(sql_type(ColumnKind::Real, Dialect::Postgres), Some("REAL"));
        assert_eq!(sql_type(ColumnKind::Uuid, Dialect::Sqlite), Some("BLOB"));
        assert_eq!(sql_type(ColumnKind::Unknown, Dialect::Postgres), None);
    }

    #[test]
    fn create_table_and_index() {
        let model = ModelState {
            table: "posts",
            columns: vec![
                col("id", ColumnKind::BigInt, false),
                col("user_id", ColumnKind::BigInt, false).references("users"),
                col("views", ColumnKind::BigInt, false).default_sql("0"),
                col("note", ColumnKind::Text, true),
            ],
            indexes: vec![ModelIndex::new(&["user_id"], false)],
        };
        let changes = [
            Change::CreateTable { model },
            Change::CreateIndex {
                table: "posts".into(),
                name: "posts_user_id_index".into(),
                columns: vec!["user_id".into()],
                unique: false,
            },
        ];
        let (up, down) = postgres(&changes);
        assert_eq!(
            up,
            "CREATE TABLE \"posts\" (\n    \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    \"user_id\" BIGINT NOT NULL REFERENCES \"users\" (\"id\"),\n    \"views\" BIGINT NOT NULL DEFAULT 0,\n    \"note\" TEXT\n);\nCREATE INDEX \"posts_user_id_index\" ON \"posts\" (\"user_id\");\n"
        );
        assert_eq!(
            down,
            "DROP INDEX \"posts_user_id_index\";\nDROP TABLE \"posts\";\n"
        );
    }

    #[test]
    fn columns_alter_rename_and_drop() {
        let changes = [
            Change::AddColumn {
                table: "t".into(),
                column: col("a", ColumnKind::Bool, false).default_sql("false"),
            },
            Change::DropColumn {
                table: "t".into(),
                old: TableColumn {
                    default: Some("'x'::text".into()),
                    ..old("b", "text", true)
                },
            },
            Change::AlterColumn {
                table: "t".into(),
                old: old("c", "integer", true),
                new: col("c", ColumnKind::Text, true),
            },
            Change::AlterColumn {
                table: "t".into(),
                old: old("d", "text", false),
                new: col("d", ColumnKind::Text, false),
            },
            Change::RenameColumn {
                table: "t".into(),
                from: "e".into(),
                to: "f".into(),
            },
        ];
        let (up, down) = postgres(&changes);
        assert_eq!(
            up,
            "ALTER TABLE \"t\" ADD COLUMN \"a\" BOOLEAN NOT NULL DEFAULT false;\n\
             ALTER TABLE \"t\" DROP COLUMN \"b\";\n\
             ALTER TABLE \"t\" ALTER COLUMN \"c\" TYPE TEXT USING \"c\"::TEXT;\n\
             ALTER TABLE \"t\" ALTER COLUMN \"c\" DROP NOT NULL;\n\
             ALTER TABLE \"t\" ALTER COLUMN \"d\" SET NOT NULL;\n\
             ALTER TABLE \"t\" RENAME COLUMN \"e\" TO \"f\";\n"
        );
        assert_eq!(
            down,
            "ALTER TABLE \"t\" RENAME COLUMN \"f\" TO \"e\";\n\
             ALTER TABLE \"t\" ALTER COLUMN \"d\" DROP NOT NULL;\n\
             ALTER TABLE \"t\" ALTER COLUMN \"c\" SET NOT NULL;\n\
             ALTER TABLE \"t\" ALTER COLUMN \"c\" TYPE integer USING \"c\"::integer;\n\
             ALTER TABLE \"t\" ADD COLUMN \"b\" text NOT NULL DEFAULT 'x'::text;\n\
             ALTER TABLE \"t\" DROP COLUMN \"a\";\n"
        );
    }

    #[test]
    fn indexes_drop_and_unique() {
        let idx = TableIndex {
            name: "t_a_index".into(),
            columns: vec!["a".into()],
            unique: false,
            sql: Some("CREATE INDEX t_a_index ON public.t USING btree (a)".into()),
        };
        let changes = [
            Change::DropIndex {
                table: "t".into(),
                old: idx,
            },
            Change::CreateIndex {
                table: "t".into(),
                name: "t_a_b_unique".into(),
                columns: vec!["a".into(), "b".into()],
                unique: true,
            },
        ];
        let (up, down) = postgres(&changes);
        assert_eq!(
            up,
            "DROP INDEX \"t_a_index\";\nCREATE UNIQUE INDEX \"t_a_b_unique\" ON \"t\" (\"a\", \"b\");\n"
        );
        assert_eq!(
            down,
            "DROP INDEX \"t_a_b_unique\";\nCREATE INDEX t_a_index ON public.t USING btree (a);\n"
        );
    }

    /// Up then down returns to the starting columns (PostgreSQL only).
    #[tokio::test]
    async fn up_then_down_restores_the_columns_on_postgres() {
        use crate::db::schema_check::table_columns;
        let db = crate::db::connect(&crate::Config::default()).await.unwrap();
        if db.dialect() != Dialect::Postgres {
            return;
        }
        crate::db::script(
            &db,
            "CREATE TABLE rt_posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
             a INTEGER NOT NULL, b TEXT, c TEXT NOT NULL DEFAULT 'x', d TEXT);",
        )
        .await
        .unwrap();
        let before = table_columns(&db, "rt_posts").await.unwrap();
        let changes = [
            Change::AddColumn {
                table: "rt_posts".into(),
                column: col("e", ColumnKind::Bool, false).default_sql("false"),
            },
            Change::DropColumn {
                table: "rt_posts".into(),
                old: before.iter().find(|c| c.name == "c").unwrap().clone(),
            },
            Change::AlterColumn {
                table: "rt_posts".into(),
                old: before.iter().find(|c| c.name == "a").unwrap().clone(),
                new: col("a", ColumnKind::Text, true),
            },
            Change::AlterColumn {
                table: "rt_posts".into(),
                old: before.iter().find(|c| c.name == "b").unwrap().clone(),
                new: col("b", ColumnKind::Text, false),
            },
            Change::RenameColumn {
                table: "rt_posts".into(),
                from: "d".into(),
                to: "f".into(),
            },
            Change::CreateIndex {
                table: "rt_posts".into(),
                name: "rt_posts_a_index".into(),
                columns: vec!["a".into()],
                unique: false,
            },
        ];
        let (up, down) = postgres(&changes);
        for text in [&up, &down] {
            for stmt in text.split(";\n").filter(|s| !s.trim().is_empty()) {
                crate::db::sql(stmt).execute(&db).await.unwrap();
            }
            if text == &up {
                let mid = table_columns(&db, "rt_posts").await.unwrap();
                assert_ne!(mid.len(), 0);
                assert!(mid.iter().any(|c| c.name == "f" && c.name != "d"));
            }
        }
        let after = table_columns(&db, "rt_posts").await.unwrap();
        let key = |v: &[crate::db::schema_check::TableColumn]| {
            v.iter()
                .map(|c| (c.name.clone(), c.sql_type.to_lowercase(), c.not_null))
                .collect::<Vec<_>>()
        };
        let mut b = key(&before);
        let mut a = key(&after);
        b.sort();
        a.sort();
        assert_eq!(b, a);
    }
}
