-- The jobs to run after this one (a JSON array), and the batch it belongs to.
ALTER TABLE jobs ADD COLUMN chain TEXT;
ALTER TABLE jobs ADD COLUMN batch_id BIGINT;
ALTER TABLE failed_jobs ADD COLUMN chain TEXT;
ALTER TABLE failed_jobs ADD COLUMN batch_id BIGINT;

CREATE TABLE job_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    total BIGINT NOT NULL,
    pending BIGINT NOT NULL,
    failed BIGINT NOT NULL DEFAULT 0,
    allow_failures BOOLEAN NOT NULL DEFAULT FALSE,
    then_job TEXT,
    catch_job TEXT,
    finally_job TEXT,
    created_at BIGINT NOT NULL,
    cancelled_at BIGINT,
    finished_at BIGINT
);
