CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue TEXT NOT NULL,
    job TEXT NOT NULL,
    payload TEXT NOT NULL,
    attempts BIGINT NOT NULL DEFAULT 0,
    max_attempts BIGINT NOT NULL,
    available_at BIGINT NOT NULL,
    reserved_at BIGINT,
    created_at BIGINT NOT NULL
);
CREATE INDEX jobs_queue_available_at ON jobs (queue, available_at);

CREATE TABLE failed_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue TEXT NOT NULL,
    job TEXT NOT NULL,
    payload TEXT NOT NULL,
    max_attempts BIGINT NOT NULL,
    error TEXT NOT NULL,
    failed_at BIGINT NOT NULL
);
