-- Related tables for the grid's relationship columns.
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    tier TEXT NOT NULL DEFAULT 'bronze'
);
ALTER TABLE orders ADD COLUMN customer_id BIGINT REFERENCES customers (id);
CREATE TABLE order_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    body TEXT NOT NULL
);
CREATE INDEX order_notes_order_id_index ON order_notes (order_id);
