CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number TEXT NOT NULL,
    customer TEXT NOT NULL,
    email TEXT NOT NULL,
    region TEXT NOT NULL,
    city TEXT NOT NULL,
    status TEXT NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    items BIGINT NOT NULL DEFAULT 0,
    total BIGINT NOT NULL DEFAULT 0,
    discount DOUBLE PRECISION NOT NULL DEFAULT 0,
    ordered_on DATE NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    trend JSONB NOT NULL DEFAULT '[]'::jsonb,
    fulfilled BIGINT NOT NULL DEFAULT 0,
    created_by TEXT NOT NULL DEFAULT '',
    updated_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX orders_ordered_on_index ON orders (ordered_on);
