CREATE TABLE webhook_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    event_id TEXT NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL,
    error TEXT,
    received_at BIGINT NOT NULL,
    processed_at BIGINT,
    UNIQUE (provider, event_id)
);
CREATE INDEX webhook_calls_status ON webhook_calls (status);
